// POST /api/tenders/[id]/regenerate-cvs
//
// One-shot maintenance endpoint that regenerates every Expert CV DOCX
// for a tender WITHOUT re-running the whole proposal engine. Used to
// retro-fix CVs that were rendered with forbidden-trace artifacts
// (PDF "=PAGE N=" markers, AI prep notes) before the trace-stripper
// landed in expert-cv-docx.ts.
//
// Body: {} (empty — endpoint scopes to selected experts on the tender)
// Returns: { regenerated: number, skipped: number, errors: Array<...> }

import { NextResponse } from "next/server";
import { requireUser, unauthorizedResponse, forbiddenResponse } from "../../../../../lib/auth";
import { rateLimit, AI_RATE_LIMIT } from "../../../../../lib/rate-limit";
import { prisma, prismaReady } from "../../../../../lib/prisma";
import { generateExpertCvDocx, expertCvFileName } from "../../../../../lib/engine/expert-cv-docx";
import { logAction } from "../../../../../lib/audit";

export const maxDuration = 60;
export const dynamic = "force-dynamic";

export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  let actor;
  try { actor = await requireUser(); } catch { return unauthorizedResponse(); }
  if (!["ADMIN", "PROPOSAL_MANAGER"].includes(actor.role)) return forbiddenResponse();

  const rl = rateLimit(`regen-cvs:${actor.id}`, AI_RATE_LIMIT);
  if (!rl.allowed) return NextResponse.json({ error: "Too many requests. Please wait before regenerating again.", code: "RATE_LIMITED", resetAt: rl.resetAt }, { status: 429 });

  await prismaReady;
  const { id: tenderId } = await params;

  const tender = await prisma.tender.findFirst({
    where: { id: tenderId, userId: actor.id },
    select: { id: true, title: true },
  });
  if (!tender) return NextResponse.json({ error: "Tender not found" }, { status: 404 });

  // Pull selected experts (the same set the engine picks for the proposal).
  const matches = await prisma.tenderExpertMatch.findMany({
    where: { tenderId, isSelected: true },
    include: { expert: true },
    orderBy: { score: "desc" },
    take: 12,
  });
  if (matches.length === 0) {
    return NextResponse.json({
      regenerated: 0,
      skipped: 0,
      errors: [],
      note: "No selected experts on this tender — nothing to regenerate.",
    });
  }

  let regenerated = 0;
  const errors: Array<{ expertId: string; fullName: string; error: string }> = [];

  for (const m of matches) {
    const expert = m.expert;
    try {
      const fileName = expertCvFileName(expert.fullName);
      const cvBuffer = await generateExpertCvDocx({
        fullName: expert.fullName,
        title: expert.title,
        email: expert.email,
        phone: expert.phone,
        yearsExperience: expert.yearsExperience,
        disciplines: expert.disciplines,
        sectors: expert.sectors,
        certifications: expert.certifications,
        profile: expert.profile,
      });
      const cvContent = cvBuffer.toString("base64");

      const existing = await prisma.generatedDocument.findFirst({
        where: { tenderId, exactFileName: fileName },
      });
      if (existing) {
        await prisma.generatedDocument.update({
          where: { id: existing.id },
          data: {
            fileContent: cvContent,
            generationStatus: "GENERATED",
            // Reset to PENDING so the next download/export call re-validates
            // with the fresh content.
            validationStatus: "PENDING",
            reviewNotes: "Regenerated by /regenerate-cvs maintenance endpoint after trace-stripper fix.",
            updatedAt: new Date(),
          },
        });
      } else {
        await prisma.generatedDocument.create({
          data: {
            tenderId,
            name: `CV — ${expert.fullName}`,
            documentType: "EXPERT_CV_PACKAGE",
            format: "DOCX",
            exactFileName: fileName,
            fileContent: cvContent,
            generationStatus: "GENERATED",
            validationStatus: "PENDING",
            contentSummary: `Professional CV for ${expert.fullName}${expert.title ? `, ${expert.title}` : ""}.`,
          },
        });
      }
      regenerated += 1;
    } catch (err) {
      errors.push({
        expertId: expert.id,
        fullName: expert.fullName,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  await logAction({
    userId: actor.id,
    action: "EXPERT_CV_REGENERATE",
    entityType: "Tender",
    entityId: tenderId,
    description: `${actor.email} regenerated ${regenerated} expert CV(s) on "${tender.title}"`,
    metadata: { tenderId, regenerated, errorCount: errors.length },
  });

  return NextResponse.json({
    success: true,
    regenerated,
    skipped: 0,
    errors,
    note: regenerated > 0
      ? `Regenerated ${regenerated} CV(s). Each is now PENDING re-validation; the next ZIP download triggers it automatically.`
      : "No CVs regenerated. Check the errors array.",
  });
}
