import { NextResponse } from "next/server";
import { requireRole, forbiddenResponse, unauthorizedResponse } from "../../../../../lib/auth";
import { prisma, prismaReady } from "../../../../../lib/prisma";
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import { logAction } from "../../../../../lib/audit";
import { buildSubmissionPlan, findExtraGeneratedDocuments, findMissingGeneratedDocuments, hasExplicitSubmissionScope, plannedSubmissionTargetFiles } from "../../../../../lib/engine/submission-plan";
import { safeFileBaseName } from "../../../../../lib/engine/proposal-labels";
import { checkExportReadiness, checkFullExportReadiness, exportReadinessError } from "../../../../../lib/engine/export-readiness";
import { getCompanyIngestionReadiness } from "../../../../../lib/company-ingestion-readiness";
import { getTenderGenerationReadiness } from "../../../../../lib/tender-generation-readiness";
import { readGeneratedDocumentContent, generatedDocumentHasContent } from "../../../../../lib/generated-document-content";
// Strict final-ZIP scope resolver — single source of truth for what
// enters the final submission ZIP. See lib/engine/final-zip-scope.ts.
import { buildFinalZipEntries } from "../../../../../lib/engine/final-zip-scope";
// PDF-required + branding/signature/stamp policy. See
// lib/engine/export-format-policy.ts.
import {
  checkTenderFormatCoverage,
  detectBrandingPolicy,
  detectTenderFormatPolicy,
  resolveExportAssetStatus,
  validateFileSignature,
} from "../../../../../lib/engine/export-format-policy";

function safeParseArr(v: unknown): string[] {
  try {
    const parsed = JSON.parse(v as string);
    return Array.isArray(parsed) ? parsed.map(String).filter(Boolean) : [];
  } catch { return []; }
}

function normalizeName(value: string): string {
  return value.trim().toLowerCase();
}

function generatedFileName(name: string): string {
  return `${name.replace(/[^a-zA-Z0-9]/g, "-")}.docx`;
}

function visibleXmlText(xml: string): string {
  return xml
    .replace(/<w:tab\/>/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function forbiddenFinalOutputPatterns(): RegExp[] {
  return [/AI_DRAFT/i, /REGEX_DRAFT/i, /remove before submission/i, /\b(TODO|TBD|FIXME|PLACEHOLDER)\b/i, /\bChatGPT\b/i, /\bOpenAI\b/i, /\bAnthropic\b/i, /\bClaude\b/i, /\bGemini\b/i, /\bDeepSeek\b/i, /\bgenerated by ai\b/i, /\bprompt\b/i, /\bsource snippet\b/i, /\bsource quote\b/i, /\bsource[-_\s]grounded\b/i, /\btraceability map\b/i, /\binternal use only\b/i, /\breviewer note\b/i, /\bmatch score\b/i, /\bevaluator score\b/i, /\bwin probability\b/i, /\bevidence id\b/i, /\baudit metadata\b/i, /\bsource id\b/i, /\bdeterministic safety import\b/i];
}

function extractPdfVisibleText(buffer: Buffer): string | null {
  const ascii = buffer.toString("latin1");
  const chunks = ascii.match(/\(([^)]{2,500})\)/g) ?? [];
  const text = chunks.map((m) => m.slice(1, -1)).join(" ").replace(/\s+/g, " ").trim();
  return text.length >= 20 ? text : null;
}

async function validateGeneratedDocx(doc: {
  id: string;
  name: string;
  exactFileName: string | null;
  generationStatus: string;
  validationStatus: string;
  fileContent: string | null;
  draftExpertCount: number | null;
  draftProjectCount: number | null;
  reviewedExpertCount: number | null;
  reviewedProjectCount: number | null;
}) {
  const errors: string[] = [];
  const filename = doc.exactFileName ?? generatedFileName(doc.name);

  if (doc.generationStatus !== "GENERATED") errors.push("Document is not generated.");
  if (!doc.fileContent) errors.push("Document file content is missing.");
  if (!filename.toLowerCase().endsWith(".docx")) errors.push("Generated document is not DOCX.");
  if ((doc.draftExpertCount ?? 0) > 0 || (doc.draftProjectCount ?? 0) > 0) errors.push("Document references draft/unreviewed sources.");

  let text = "";
  if (doc.fileContent) {
    try {
      const buffer = Buffer.from(doc.fileContent, "base64");
      if (buffer.length < 500) errors.push("DOCX file is unexpectedly small.");
      if (buffer[0] !== 0x50 || buffer[1] !== 0x4b) errors.push("DOCX package signature is invalid.");

      const JSZip = (await import("jszip")).default;
      const zip = await JSZip.loadAsync(buffer);
      const documentXml = await zip.file("word/document.xml")?.async("string");
      if (!documentXml) {
        errors.push("DOCX word/document.xml is missing.");
      } else {
        text = visibleXmlText(documentXml);
        if (text.length < 100) errors.push("Document text is too short for final submission.");
      }
    } catch (error) {
      errors.push(`DOCX validation failed: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  // Gap 4: internal-traceability leakage scan. Final submission DOCX
  // must NEVER expose: source IDs, internal evidence IDs, scoring
  // rationale, match scores, audit metadata, AI provider names,
  // "source quote" / "source-grounded" / "traceability map" markers,
  // or "internal use" notes. These are valid internally but cannot
  // ever reach the evaluator. See product rule #8 in the original
  // prompt.
  const forbiddenPatterns = forbiddenFinalOutputPatterns();
  for (const pattern of forbiddenPatterns) {
    if (pattern.test(text) || pattern.test(doc.name) || pattern.test(filename)) {
      errors.push(`Forbidden final-output trace detected: ${pattern.source}`);
    }
  }

  const status = errors.length === 0 ? "VALIDATED" : "FAILED";
  if (doc.validationStatus !== status) {
    await prisma.generatedDocument.update({
      where: { id: doc.id },
      data: {
        validationStatus: status,
        reviewNotes: errors.length > 0 ? errors.join("\n") : "Passed deterministic final export validation.",
      },
    });
  }

  return { ok: errors.length === 0, errors, filename };
}


async function validateGeneratedPdf(doc: { id: string; name: string; exactFileName: string | null; generationStatus: string; validationStatus: string; fileContent: string | null; draftExpertCount: number | null; draftProjectCount: number | null; }) {
  const errors: string[] = [];
  const filename = doc.exactFileName ?? generatedFileName(doc.name);
  if (doc.generationStatus !== "GENERATED") errors.push("Document is not generated.");
  if (!doc.fileContent) errors.push("Document file content is missing.");
  if (!filename.toLowerCase().endsWith(".pdf")) errors.push("Generated document is not PDF.");
  if ((doc.draftExpertCount ?? 0) > 0 || (doc.draftProjectCount ?? 0) > 0) errors.push("Document references draft/unreviewed sources.");
  let text = "";
  if (doc.fileContent) {
    const buffer = Buffer.from(doc.fileContent, "base64");
    if (buffer.length < 300) errors.push("PDF file is unexpectedly small.");
    if (!buffer.slice(0, 4).equals(Buffer.from("%PDF"))) errors.push("PDF signature is invalid.");
    const extracted = extractPdfVisibleText(buffer);
    if (!extracted) errors.push("PDF_REQUIRED_TEXT_SCAN_UNAVAILABLE");
    else text = extracted;
  }
  for (const pattern of forbiddenFinalOutputPatterns()) if (pattern.test(text) || pattern.test(doc.name) || pattern.test(filename)) errors.push(`Forbidden final-output trace detected: ${pattern.source}`);
  return { ok: errors.length === 0, errors, filename };
}

async function validateGeneratedFileForExport(doc: any) {
  const withContent = await readGeneratedDocumentContent(doc);
  const hydrated = { ...doc, fileContent: withContent.base64, exactFileName: withContent.filename };
  const filename = (hydrated.exactFileName ?? generatedFileName(hydrated.name)).toLowerCase();
  if (filename.endsWith(".docx")) return validateGeneratedDocx(hydrated);
  if (filename.endsWith(".pdf")) return validateGeneratedPdf(hydrated);
  return { ok: false, errors: ["UNSUPPORTED_EXPORT_FORMAT"], filename };
}

async function validateDocsForExport(docs: Array<{
  id: string;
  name: string;
  exactFileName: string | null;
  generationStatus: string;
  validationStatus: string;
  fileContent: string | null;
  draftExpertCount: number | null;
  draftProjectCount: number | null;
  reviewedExpertCount: number | null;
  reviewedProjectCount: number | null;
}>) {
  const failures: Array<{ id: string; name: string; errors: string[] }> = [];
  for (const doc of docs) {
    const result = await validateGeneratedFileForExport(doc);
    if (!result.ok) failures.push({ id: doc.id, name: doc.name, errors: result.errors });
  }
  return failures;
}

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  let actor;
  try { actor = await requireRole("ADMIN", "PROPOSAL_MANAGER", "REVIEWER"); } catch (e) { return e instanceof Error && e.message === "Forbidden" ? forbiddenResponse() : unauthorizedResponse(); }
  const userId = actor.id;

  await prismaReady;
  const { id } = await params;
  const { searchParams } = new URL(req.url);
  const type = searchParams.get("type") || "proposal";
  const docId = searchParams.get("docId");

  const tender = await prisma.tender.findFirst({
    where: { id, userId },
    include: {
      requirements: true,
      complianceGaps: true,
      generatedDocuments: true,
      exportPackages: true,
      expertMatches: { where: { isSelected: true }, include: { expert: { select: { disciplines: true, sectors: true, yearsExperience: true } } } },
      projectMatches: { where: { isSelected: true }, include: { project: { select: { sectors: true, contractValue: true } } } },
    },
  });
  if (!tender) return NextResponse.json({ error: "Tender not found" }, { status: 404 });

  const company = await prisma.company.findUnique({ where: { userId }, select: { id: true } });
  if (!company) return NextResponse.json({ error: "Company profile required before download." }, { status: 422 });
  const ingestion = await getCompanyIngestionReadiness(company.id, { requireDocuments: true, requireReviewedExperts: tender.requirements.some((r) => r.requirementType === "EXPERT"), requireReviewedProjects: tender.requirements.some((r) => r.requirementType === "PROJECT_EXPERIENCE") });
  if (!ingestion.ingestionReady) return NextResponse.json({ error: "Export blocked: company knowledge ingestion is not ready.", code: "INGESTION_NOT_READY", blockers: ingestion.blockers, totals: ingestion.totals }, { status: 422 });

  if (docId || type === "zip") {
    const generationReadiness = await getTenderGenerationReadiness(prisma, userId, id);
    if (!generationReadiness) return NextResponse.json({ error: "Tender not found" }, { status: 404 });
    if (!generationReadiness.ready) {
      return NextResponse.json({
        error: "Final export blocked by generation-readiness blockers",
        blockers: generationReadiness.blockers,
        warnings: generationReadiness.warnings,
        nextAction: "OPEN_GENERATION_READINESS",
      }, { status: 409 });
    }
  }

  const blockingGaps = tender.complianceGaps.filter((g) => !g.isResolved && g.severity === "CRITICAL");
  if ((docId || type === "zip") && blockingGaps.length > 0) {
    return NextResponse.json({ error: "Final export blocked by unresolved CRITICAL compliance gaps", reasons: blockingGaps.map((g) => g.title) }, { status: 409 });
  }

  const untracedMandatoryRequirements = tender.requirements.filter((req) => req.priority === "MANDATORY" && ((req.sourceConfidence ?? 0) <= 0));
  if ((docId || type === "zip") && untracedMandatoryRequirements.length > 0) {
    return NextResponse.json({ error: `Final export blocked: ${untracedMandatoryRequirements.length} mandatory requirement(s) are not source-grounded yet.`, code: "UNTRACED_MANDATORY_REQUIREMENTS", requirements: untracedMandatoryRequirements.slice(0, 20).map((req) => ({ id: req.id, title: req.title })) }, { status: 422 });
  }

  if (type === "proposal" && !docId) {
    return NextResponse.json({
      error: "Direct proposal export is disabled",
      detail: "Run the tender engine and generate the required documents first. Then download a generated document or the ZIP package. This prevents unvalidated proposal files from bypassing compliance and review guardrails.",
    }, { status: 409 });
  }

  if (docId) {
    const doc = tender.generatedDocuments.find((d) => d.id === docId);
    if (!doc || doc.generationStatus !== "GENERATED") {
      return NextResponse.json({ error: "Document not found or not yet generated" }, { status: 404 });
    }

    if (!generatedDocumentHasContent(doc)) {
      return NextResponse.json({ error: "Document content is unavailable — neither storage path nor inline content is present.", code: "MISSING_CONTENT" }, { status: 409 });
    }

    const validation = await validateGeneratedFileForExport(doc);
    if (!validation.ok) {
      return NextResponse.json({ error: "Document export blocked by final validation", reasons: validation.errors }, { status: 409 });
    }

    const readiness = checkExportReadiness([{ ...doc, validationStatus: "VALIDATED" }], { requireFileContent: false });
    if (!readiness.ok) {
      return NextResponse.json({ error: exportReadinessError(readiness.failures), failures: readiness.failures }, { status: 409 });
    }

    const content = await readGeneratedDocumentContent(doc);
    const buffer = content.buffer;
    await logAction({ userId, action: "EXPORT_PACKAGE_DOWNLOAD", entityType: "GeneratedDocument", entityId: docId, description: `Downloaded reviewed and validated generated document "${validation.filename}"` });
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": validation.filename.toLowerCase().endsWith(".pdf") ? "application/pdf" : "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${validation.filename}"`,
      },
    });
  }

  if (type === "zip") {
    const JSZip = (await import("jszip")).default;
    const zip = new JSZip();

    const generatedDocs = tender.generatedDocuments
      .filter((d) => d.generationStatus === "GENERATED")
      .sort((a, b) => (a.exactOrder ?? 99) - (b.exactOrder ?? 99));

    if (generatedDocs.length === 0) {
      return NextResponse.json({ error: "No generated documents to package. Run generation first." }, { status: 400 });
    }

    const validationFailures = await validateDocsForExport(generatedDocs);
    if (validationFailures.length > 0) {
      return NextResponse.json({ error: "ZIP export blocked by final validation", failures: validationFailures }, { status: 409 });
    }

    const readiness = await checkFullExportReadiness({
      tenderId: tender.id,
      docs: generatedDocs.map((doc) => ({ ...doc, validationStatus: "VALIDATED" })),
      requireFileContent: false,
    });
    if (!readiness.ok) {
      return NextResponse.json({ error: exportReadinessError(readiness.failures, readiness.tenderLevelBlockers), failures: readiness.failures, tenderLevelBlockers: readiness.tenderLevelBlockers ?? [] }, { status: 409 });
    }

    const requiredNames = safeParseArr(tender.exactFileNaming).map(normalizeName);
    const requiredOrder = safeParseArr(tender.exactFileOrder).map(normalizeName);
    const generatedNames = generatedDocs.map((d) => normalizeName(d.exactFileName ?? generatedFileName(d.name)));

    if (hasExplicitSubmissionScope(tender)) {
      const submissionPlan = buildSubmissionPlan({
        id: tender.id,
        title: tender.title,
        exactFileNaming: tender.exactFileNaming,
        exactFileOrder: tender.exactFileOrder,
        pageLimit: tender.pageLimit,
        requirements: tender.requirements,
      });
      const missingPlanFiles = findMissingGeneratedDocuments(submissionPlan, generatedDocs);
      const extraGeneratedDocs = findExtraGeneratedDocuments(submissionPlan, generatedDocs);
      if (missingPlanFiles.length > 0 || extraGeneratedDocs.length > 0) {
        return NextResponse.json({
          error: "ZIP export blocked by submission plan mismatch",
          missing: missingPlanFiles.map((file) => file.exactFileName),
          extras: extraGeneratedDocs.map((doc) => doc.exactFileName ?? generatedFileName(doc.name ?? doc.documentType ?? doc.id ?? "document")),
          requiredCount: plannedSubmissionTargetFiles(submissionPlan).length,
          generatedCount: generatedDocs.length,
        }, { status: 409 });
      }
    } else {
      if (requiredNames.length > 0) {
        const missing = requiredNames.filter((name) => !generatedNames.includes(name));
        const extras = generatedNames.filter((name) => !requiredNames.includes(name));
        if (missing.length > 0 || extras.length > 0 || generatedDocs.length !== requiredNames.length) {
          return NextResponse.json(
            { error: "Generated package does not match tender-required file naming scope.", missing, extras, requiredCount: requiredNames.length, generatedCount: generatedDocs.length },
            { status: 400 },
          );
        }
      }

      if (requiredOrder.length > 0) {
        const outOfOrder = requiredOrder.some((name, index) => generatedNames[index] !== name);
        if (outOfOrder) {
          return NextResponse.json({ error: "Generated package order does not match tender-required file order.", requiredOrder, generatedOrder: generatedNames }, { status: 400 });
        }
      }
    }

    // ─── GAP 2 — PDF-REQUIRED FORMAT COVERAGE ──────────────────────────
    // Tender's submission plan may explicitly require .pdf output.
    // Don't silently ship DOCX renamed to .pdf or block-and-confuse the
    // user — return PDF_REQUIRED_CONVERSION_UNAVAILABLE with a clear
    // message when the format gap is real. See export-format-policy.ts.
    const formatPolicy = detectTenderFormatPolicy({
      exactFileNaming: tender.exactFileNaming,
      exactFileOrder: tender.exactFileOrder,
      requirements: tender.requirements.map((r) => ({ exactFileName: r.exactFileName ?? null })),
    });
    if (formatPolicy.requiredFormats.length > 0) {
      const generatedExts = generatedDocs.map((d) => {
        const fn = d.exactFileName ?? generatedFileName(d.name);
        return fn.toLowerCase().split(".").pop() ?? "";
      });
      const coverage = checkTenderFormatCoverage(formatPolicy, generatedExts);
      if (!coverage.ok) {
        return NextResponse.json({
          error: coverage.reason,
          code: coverage.code,
          missing: coverage.missing,
          requiredFormats: formatPolicy.requiredFormats,
        }, { status: 422 });
      }
    }

    // Per-file signature validation — catches renamed DOCX→.pdf or
    // PDF→.docx accidents. Each generated doc must have its binary
    // signature match its declared extension.
    for (const doc of generatedDocs) {
      const filename = doc.exactFileName ?? generatedFileName(doc.name);
      const content = await readGeneratedDocumentContent(doc);
      const signatureCheck = validateFileSignature(filename, content.base64);
      if (!signatureCheck.ok) {
        return NextResponse.json({
          error: `Final export blocked: file signature mismatch on "${filename}".`,
          code: "FILE_SIGNATURE_MISMATCH",
          reason: signatureCheck.reason,
        }, { status: 422 });
      }
    }

    // ─── GAP 3 — BRANDING / SIGNATURE / STAMP POLICY ───────────────────
    // Scan tender text for restriction language and reject the export
    // when the firm would apply an asset the tender explicitly
    // prohibits. The asset-status object is also returned to the UI so
    // the readiness panel can show what was allowed vs blocked.
    const tenderText = [
      tender.title ?? "",
      tender.description ?? "",
      tender.intakeSummary ?? "",
      tender.analysisSummary ?? "",
      tender.evaluationMethodology ?? "",
      ...tender.requirements.map((r) => `${r.title ?? ""} ${r.description ?? ""} ${r.restrictions ?? ""}`),
    ].join("\n\n");
    const brandingPolicy = detectBrandingPolicy(tenderText);
    // AppSettings is keyed by companyId (one settings row per
    // company). `company.id` was loaded above when checking ingestion.
    const appSettings = await prisma.appSettings.findFirst({ where: { companyId: company.id } });
    const assetStatus = resolveExportAssetStatus(brandingPolicy, {
      allowBrandingDefault: appSettings?.allowBrandingDefault,
      allowSignatureDefault: appSettings?.allowSignatureDefault,
      allowStampDefault: appSettings?.allowStampDefault,
    });
    // If the tender prohibits an asset BUT the firm's default is to
    // apply it, block. The route doesn't currently strip DOCX assets
    // mid-flight — that's a separate strip-pass follow-up. Until then,
    // failing closed is the safe choice.
    const conflictingAssets: string[] = [];
    if (!brandingPolicy.brandingAllowed && (appSettings?.allowBrandingDefault !== false)) {
      conflictingAssets.push("branding/letterhead");
    }
    if (!brandingPolicy.signatureAllowed && (appSettings?.allowSignatureDefault !== false)) {
      conflictingAssets.push("signature");
    }
    if (!brandingPolicy.stampAllowed && (appSettings?.allowStampDefault !== false)) {
      conflictingAssets.push("stamp");
    }
    if (conflictingAssets.length > 0) {
      return NextResponse.json({
        error: `Final export blocked: tender prohibits ${conflictingAssets.join(", ")} but the firm's AppSettings would apply it. Toggle off the relevant default in Settings, OR remove the asset from the generated documents, then retry.`,
        code: "BRANDING_POLICY_CONFLICT",
        assetStatus,
        policyBlockers: brandingPolicy.blockers,
      }, { status: 409 });
    }

    // ─── STRICT FINAL ZIP SCOPE (PR follow-up to #422) ─────────────────
    // Build the canonical entry list in ONE place. The same list drives
    // zip.file() calls, ExportPackage.fileList, and the audit log so the
    // three can never drift. See lib/engine/final-zip-scope.ts for the
    // policy (no auto Win-Probability, no duplicate CVs/, only what the
    // tender explicitly requires).
    const zipScopeResult = buildFinalZipEntries({
      tender: {
        exactFileNaming: tender.exactFileNaming,
        exactFileOrder: tender.exactFileOrder,
        requirements: tender.requirements.map((r) => ({ exactFileName: r.exactFileName ?? null })),
      },
      generatedDocs: generatedDocs.map((d) => ({
        id: d.id,
        name: d.name,
        exactFileName: d.exactFileName,
        exactOrder: d.exactOrder,
        documentType: d.documentType,
      })),
    });

    // Map each entry to its actual document content. Filter out any
    // entry that doesn't resolve to a generated doc with fileContent
    // (defence-in-depth — finalZipEntries should never reference a
    // missing source under normal flow).
    const docById = new Map(generatedDocs.map((d) => [d.id, d]));
    const finalZipEntries = zipScopeResult.entries.filter((entry) => {
      if (!entry.generatedDocId) return false;
      const doc = docById.get(entry.generatedDocId);
      return Boolean(doc);
    });

    if (finalZipEntries.length === 0) {
      return NextResponse.json({
        error: "Final ZIP has no entries after strict-scope filtering. Verify the tender's submission plan and the generated document set.",
        exclusions: zipScopeResult.exclusions,
      }, { status: 409 });
    }

    for (const entry of finalZipEntries) {
      const doc = docById.get(entry.generatedDocId!);
      if (!doc) continue;
      const content = await readGeneratedDocumentContent(doc);
      const buffer = content.buffer;
      zip.file(entry.name, buffer);
    }

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    const zipName = `${safeFileBaseName(tender.title)}-submission-package.zip`;
    // fileList is now the SAME list as the actual ZIP entries — no
    // win-probability addition, no CV duplication mismatch. The
    // ExportPackage.fileList row in the DB always reflects the real ZIP.
    const fileList = finalZipEntries.map((entry) => entry.name);

    const existingPackage = tender.exportPackages[0];
    if (existingPackage) {
      await prisma.exportPackage.update({ where: { id: existingPackage.id }, data: { status: "READY", fileList: JSON.stringify(fileList), downloadCount: { increment: 1 } } });
    } else {
      await prisma.exportPackage.create({ data: { tenderId: id, status: "READY", fileList: JSON.stringify(fileList), downloadCount: 1 } });
    }

    await logAction({
      userId,
      action: "EXPORT_PACKAGE_DOWNLOAD",
      entityType: "Tender",
      entityId: id,
      description: `Downloaded reviewed and validated ZIP package for "${tender.title}" (${finalZipEntries.length} file(s))`,
      metadata: {
        fileCount: finalZipEntries.length,
        hasExplicitScope: zipScopeResult.hasExplicitScope,
        exclusionCount: zipScopeResult.exclusions.length,
      },
    });

    return new NextResponse(new Uint8Array(zipBuffer), { headers: { "Content-Type": "application/zip", "Content-Disposition": `attachment; filename="${zipName}"` } });
  }

  const children: Paragraph[] = [];

  if (type === "compliance") {
    children.push(new Paragraph({ children: [new TextRun({ text: `Internal Compliance Report: ${tender.title}`, bold: true, size: 48 })], spacing: { after: 300 } }));
    if (tender.complianceGaps.length === 0) {
      children.push(new Paragraph({ children: [new TextRun({ text: "No compliance gaps identified.", color: "22c55e" })] }));
    } else {
      for (const gap of tender.complianceGaps) {
        children.push(
          new Paragraph({ children: [new TextRun({ text: `[${gap.severity}] `, bold: true, color: gap.severity === "CRITICAL" ? "dc2626" : gap.severity === "HIGH" ? "ea580c" : "ca8a04" }), new TextRun({ text: gap.title, bold: true })], spacing: { before: 160, after: 60 } }),
          new Paragraph({ children: [new TextRun({ text: gap.description, color: "555555" })], spacing: { after: 60 } }),
          ...(gap.mitigationPlan ? [new Paragraph({ children: [new TextRun({ text: `Mitigation: ${gap.mitigationPlan}`, italics: true })] })] : []),
        );
      }
    }
  } else if (type === "requirements") {
    children.push(new Paragraph({ children: [new TextRun({ text: `Internal Requirements Review: ${tender.title}`, bold: true, size: 48 })], spacing: { after: 300 } }));
    for (const req of tender.requirements) {
      children.push(
        new Paragraph({ children: [new TextRun({ text: `[${req.priority}] ${req.requirementType}  `, bold: true, color: req.priority === "MANDATORY" ? "dc2626" : "2563eb" }), new TextRun({ text: req.title, bold: true })], spacing: { before: 120, after: 60 } }),
        new Paragraph({ children: [new TextRun({ text: req.description })], spacing: { after: 120 } }),
      );
    }
  } else {
    return NextResponse.json({ error: "Unsupported download type" }, { status: 400 });
  }

  const doc = new Document({ sections: [{ properties: {}, children }], styles: { default: { document: { run: { font: "Calibri", size: 22 }, paragraph: { spacing: { line: 276 } } } } } });
  const buffer = await Packer.toBuffer(doc);
  const filename = `${safeFileBaseName(tender.title)}-${type}-internal.docx`;

  await logAction({ userId, action: "EXPORT_PACKAGE_DOWNLOAD", entityType: "Tender", entityId: id, description: `Downloaded internal ${type} report for "${tender.title}"` });
  return new NextResponse(new Uint8Array(buffer), { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "Content-Disposition": `attachment; filename="${filename}"` } });
}
