// A client file's properties are the bidder's. The technical proposal's DOCX
// said "Client-ready technical proposal generated by Hope Tender Engine" under
// File → Properties, the PDF named its PDF library as Creator and Producer,
// and the financial proposal's author was the library default, "Un-named".
import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import JSZip from "jszip";
import { PDFDocument } from "pdf-lib";
import { buildFinancialProposalDocx } from "../lib/engine/financial-proposal";
import { generateProposalPdf } from "../lib/engine/proposal-pdf";

const TOOL = /hope tender|tender engine|generated by|pdf-lib|un-named|docx/i;

describe("a client file names the bidder, not the tool", () => {
  it("the technical proposal's DOCX properties", () => {
    const src = readFileSync("lib/engine/generate-elite.ts", "utf8");
    const block = src.slice(src.indexOf("return new Document({"), src.indexOf("return new Document({") + 600);
    assert.match(block, /creator: params\.companyName/);
    assert.match(block, /lastModifiedBy: params\.companyName/);
    assert.doesNotMatch(block, /Hope Tender Engine|generated by/i);
  });

  it("the financial proposal's DOCX properties", async () => {
    const b64 = await buildFinancialProposalDocx({
      title: "Financial Proposal", tenderTitle: "Design of a Library", companyName: "Northgate PLC",
      settings: { currency: "ETB", validityDays: 90, vatPercent: 15, contingencyPct: 0, withholdingPct: 0 },
      lines: [{ category: "PERSONNEL", label: "Team Leader", quantity: 10, unit: "DAY", rate: 5000 }],
    });
    const core = await (await JSZip.loadAsync(Buffer.from(b64, "base64"))).file("docProps/core.xml")!.async("string");
    assert.match(core, /<dc:creator>Northgate PLC<\/dc:creator>/);
    assert.match(core, /<cp:lastModifiedBy>Northgate PLC<\/cp:lastModifiedBy>/);
    assert.doesNotMatch(core, TOOL);
  });

  it("the proposal PDF's document information", async () => {
    const bytes = await generateProposalPdf({ title: "Design of a Library", companyName: "Northgate PLC", markdown: "# Technical Proposal\n\nOur approach is set out below." });
    const pdf = await PDFDocument.load(bytes, { updateMetadata: false });
    assert.equal(pdf.getTitle(), "Design of a Library");
    assert.equal(pdf.getAuthor(), "Northgate PLC");
    assert.equal(pdf.getCreator(), "Northgate PLC");
    assert.equal(pdf.getProducer(), "Northgate PLC");
  });
});
