import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  runAuthorityReview,
  type DocumentInput,
  type ManifestEntry,
} from "../lib/engine/authority-review";

// ── Helpers ───────────────────────────────────────────────────────────────────

function makeDoc(overrides: Partial<DocumentInput> = {}): DocumentInput {
  return {
    id: "doc-1",
    name: "Technical Proposal",
    documentType: "TECHNICAL_PROPOSAL",
    contentSummary: "A clean technical proposal with methodology and work plan.",
    reviewNotes: null,
    exactFileName: "Technical-Proposal.docx",
    ...overrides,
  };
}

function makeManifest(exactFileName = "Technical-Proposal.docx"): ManifestEntry[] {
  return [{ exactFileName, documentType: "TECHNICAL_PROPOSAL" }];
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("authority-review — AI trace detection", () => {
  it("AI trace in contentSummary blocks export with code AI_TRACE", () => {
    const doc = makeDoc({
      contentSummary: "As an AI language model, I cannot provide real project data.",
    });
    const result = runAuthorityReview([doc], makeManifest(), []);
    assert.equal(result.status, "BLOCKED");
    const blocker = result.blockers.find((b) => b.code === "AI_TRACE");
    assert.ok(blocker, "expected AI_TRACE blocker");
    assert.equal(blocker?.severity, "CRITICAL");
  });

  it("ChatGPT mention triggers AI_TRACE blocker", () => {
    const doc = makeDoc({ contentSummary: "Generated by ChatGPT for testing." });
    const result = runAuthorityReview([doc], makeManifest(), []);
    const blocker = result.blockers.find((b) => b.code === "AI_TRACE");
    assert.ok(blocker, "expected AI_TRACE blocker");
  });
});

describe("authority-review — placeholder detection", () => {
  it("[TBD] placeholder blocks export with code PLACEHOLDER", () => {
    const doc = makeDoc({
      contentSummary: "Company founded in [TBD] with extensive experience.",
    });
    const result = runAuthorityReview([doc], makeManifest(), []);
    assert.equal(result.status, "BLOCKED");
    const blocker = result.blockers.find((b) => b.code === "PLACEHOLDER");
    assert.ok(blocker, "expected PLACEHOLDER blocker");
    assert.equal(blocker?.severity, "CRITICAL");
  });

  it("[INSERT] placeholder triggers PLACEHOLDER blocker", () => {
    const doc = makeDoc({ contentSummary: "Contact [INSERT] for more details." });
    const result = runAuthorityReview([doc], makeManifest(), []);
    const blocker = result.blockers.find((b) => b.code === "PLACEHOLDER");
    assert.ok(blocker, "expected PLACEHOLDER blocker");
  });
});

describe("authority-review — Bid-Team stub detection", () => {
  it("'Bid-Team to confirm' blocks export with code BID_TEAM_STUB", () => {
    const doc = makeDoc({
      contentSummary: "Client name: Bid-Team to confirm. Address: TBD.",
    });
    const result = runAuthorityReview([doc], makeManifest(), []);
    assert.equal(result.status, "BLOCKED");
    const blocker = result.blockers.find((b) => b.code === "BID_TEAM_STUB");
    assert.ok(blocker, "expected BID_TEAM_STUB blocker");
  });

  it("MISSING_SOURCE triggers INTERNAL_NOTE blocker", () => {
    const doc = makeDoc({
      contentSummary: "Submission deadline: MISSING_SOURCE. Contact: unknown.",
    });
    const result = runAuthorityReview([doc], makeManifest(), []);
    const blocker = result.blockers.find((b) => b.code === "INTERNAL_NOTE");
    assert.ok(blocker, "expected INTERNAL_NOTE blocker");
  });
});

describe("authority-review — TODO/FIXME detection", () => {
  it("TODO in content blocks export with code TODO_FIXME_IN_CONTENT", () => {
    const doc = makeDoc({
      contentSummary: "TODO complete the methodology section here.",
    });
    const result = runAuthorityReview([doc], makeManifest(), []);
    const blocker = result.blockers.find((b) => b.code === "TODO_FIXME_IN_CONTENT");
    assert.ok(blocker, "expected TODO_FIXME_IN_CONTENT blocker");
    assert.equal(blocker?.severity, "HIGH");
  });

  it("FIXME in reviewNotes triggers TODO_FIXME_IN_CONTENT blocker", () => {
    const doc = makeDoc({ contentSummary: "Clean content.", reviewNotes: "FIXME: wrong section heading" });
    const result = runAuthorityReview([doc], makeManifest(), []);
    const blocker = result.blockers.find((b) => b.code === "TODO_FIXME_IN_CONTENT");
    assert.ok(blocker, "expected TODO_FIXME_IN_CONTENT blocker");
  });
});

describe("authority-review — pricing in technical envelope", () => {
  it("pricing content in TECHNICAL document blocks with PRICING_IN_TECHNICAL", () => {
    const doc = makeDoc({
      documentType: "TECHNICAL_PROPOSAL",
      contentSummary: "Unit cost: $500 per day. Bid price includes all taxes.",
    });
    const result = runAuthorityReview([doc], makeManifest(), []);
    assert.equal(result.status, "BLOCKED");
    const blocker = result.blockers.find((b) => b.code === "PRICING_IN_TECHNICAL");
    assert.ok(blocker, "expected PRICING_IN_TECHNICAL blocker");
    assert.equal(blocker?.severity, "CRITICAL");
  });

  it("pricing content in non-TECHNICAL document does not trigger PRICING_IN_TECHNICAL", () => {
    const doc = makeDoc({
      documentType: "FINANCIAL_PROPOSAL",
      contentSummary: "Unit cost: $500 per day. Bid price includes all taxes.",
      exactFileName: "Financial-Proposal.docx",
    });
    const manifest = [{ exactFileName: "Financial-Proposal.docx", documentType: "FINANCIAL_PROPOSAL" }];
    const result = runAuthorityReview([doc], manifest, []);
    const blocker = result.blockers.find((b) => b.code === "PRICING_IN_TECHNICAL");
    assert.equal(blocker, undefined, "should NOT trigger PRICING_IN_TECHNICAL for financial doc");
  });
});

describe("authority-review — methodology in financial envelope", () => {
  it("technical methodology in FINANCIAL document blocks with METHODOLOGY_IN_FINANCIAL", () => {
    const doc = makeDoc({
      documentType: "FINANCIAL_PROPOSAL",
      contentSummary: "Technical approach and implementation methodology described below.",
      exactFileName: "Financial-Proposal.docx",
    });
    const manifest = [{ exactFileName: "Financial-Proposal.docx", documentType: "FINANCIAL_PROPOSAL" }];
    const result = runAuthorityReview([doc], manifest, []);
    const blocker = result.blockers.find((b) => b.code === "METHODOLOGY_IN_FINANCIAL");
    assert.ok(blocker, "expected METHODOLOGY_IN_FINANCIAL blocker");
    assert.equal(blocker?.severity, "CRITICAL");
  });
});

describe("authority-review — extra document not in manifest", () => {
  it("document not listed in manifest triggers EXTRA_DOCUMENT_NOT_IN_MANIFEST", () => {
    const doc = makeDoc({
      exactFileName: "Extra-Document.docx",
    });
    // Manifest only contains a different file
    const manifest = [{ exactFileName: "Technical-Proposal.docx", documentType: "TECHNICAL_PROPOSAL" }];
    const result = runAuthorityReview([doc], manifest, []);
    const blocker = result.blockers.find((b) => b.code === "EXTRA_DOCUMENT_NOT_IN_MANIFEST");
    assert.ok(blocker, "expected EXTRA_DOCUMENT_NOT_IN_MANIFEST blocker");
    assert.equal(blocker?.severity, "HIGH");
  });
});

describe("authority-review — missing required section", () => {
  it("required section with no matching document triggers MISSING_REQUIRED_SECTION", () => {
    const doc = makeDoc({ name: "Technical Proposal", documentType: "TECHNICAL_PROPOSAL" });
    const manifest = makeManifest();
    const result = runAuthorityReview([doc], manifest, ["Financial Proposal"]);
    const blocker = result.blockers.find((b) => b.code === "MISSING_REQUIRED_SECTION");
    assert.ok(blocker, "expected MISSING_REQUIRED_SECTION blocker");
    assert.equal(blocker?.severity, "CRITICAL");
    assert.equal(blocker?.sectionName, "Financial Proposal");
  });
});

describe("authority-review — clean document", () => {
  it("clean document with no issues passes with status AUTHORITY_READY and score >= 85", () => {
    const doc = makeDoc({
      contentSummary:
        "A comprehensive technical proposal covering work methodology, team qualifications, and project timeline.",
      reviewNotes: "Reviewed and approved.",
    });
    const manifest = makeManifest();
    const result = runAuthorityReview([doc], manifest, ["Technical Proposal"]);
    assert.equal(result.status, "AUTHORITY_READY");
    assert.ok(result.overallScore >= 85, `expected score >= 85, got ${result.overallScore}`);
    assert.equal(result.blockers.length, 0);
  });
});

describe("authority review gate wiring — download route", () => {
  const source = readFileSync("app/api/tenders/[id]/download/route.ts", "utf8");

  it("imports runAuthorityReview", () => {
    assert.match(source, /runAuthorityReview/);
  });

  it("returns AUTHORITY_REVIEW_BLOCKED on blocked status", () => {
    assert.match(source, /AUTHORITY_REVIEW_BLOCKED/);
  });

  it("METADATA_CONTAMINATED is advisory only (unified runtime model)", () => {
    assert.doesNotMatch(source, /warnings\.push\(\{[\s\S]*?METADATA_CONTAMINATED/);
  });
});

describe("authority-review API route — does not leak a stale 'ready' recommendedFix when outer ok is false", () => {
  // Confirmed by a real Playwright screenshot: for a tender with zero
  // generated documents and no confirmed Build Plan, runAuthorityReview's
  // own internal status is AUTHORITY_READY (no document-level blockers to
  // find), so it pushes "All authority review checks pass. Document is
  // ready for final export." into recommendedFixes. The route then
  // overrides status to BLOCKED (via canonicalBlockers / buildPlan.confirmed)
  // but was spreading the stale recommendedFixes array unchanged — so the
  // response said BLOCKED and "ready for final export" at the same time.
  const source = readFileSync("app/api/tenders/[id]/authority-review/route.ts", "utf8");

  it("computes a corrected recommendedFixes gated on the outer ok flag", () => {
    assert.match(source, /const recommendedFixes = ok\s*\n\s*\? result\.recommendedFixes\s*\n\s*: result\.recommendedFixes\.filter\(/);
  });

  it("filters out the misleading ready-for-export fix when ok is false", () => {
    assert.match(source, /fix !== "All authority review checks pass\. Document is ready for final export\."/);
  });

  it("the response uses the corrected recommendedFixes, not the raw result spread", () => {
    const authorityReviewObjMatch = source.match(/authorityReview:\s*\{([\s\S]*?)\n\s*\},/);
    assert.ok(authorityReviewObjMatch, "authorityReview response object must exist");
    assert.match(authorityReviewObjMatch![1], /recommendedFixes,/);
  });
});
