import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import { Document, Packer, Paragraph, TextRun } from "docx";

import {
  cleanDocxHygieneIssues,
  type RepairDoc,
} from "../lib/engine/export-gap-repair";
import {
  documentHygieneIssues,
  extractDocxVisibleText,
} from "../lib/engine/export-readiness";

async function makeTechnicalDocx(): Promise<string> {
  const buffer = await Packer.toBuffer(new Document({
    sections: [{
      children: [
        // The good sentence, unsafe pricing sentence, and safe envelope sentence
        // deliberately share ONE paragraph. Word also splits the unsafe phrase
        // across formatting runs. Repair must remove only the unsafe sentence.
        new Paragraph({
          children: [
            new TextRun("Our technical methodology covers quality assurance and implementation sequencing. "),
            new TextRun({ text: "Financial ", bold: true }),
            new TextRun({ text: "proposal includes USD ", italics: true }),
            new TextRun("500,000 for consultancy services. "),
            new TextRun("The financial offer is submitted separately in the designated commercial envelope."),
          ],
        }),
        // AI/meta traces can also be split across runs.
        new Paragraph({
          children: [
            new TextRun("Generated by "),
            new TextRun({ text: "AI", bold: true }),
            new TextRun(" from an internal prompt."),
          ],
        }),
      ],
    }],
  }));
  return buffer.toString("base64");
}

const DOC: RepairDoc = {
  id: "doc-technical",
  name: "Technical Proposal",
  exactFileName: "Technical-Proposal.docx",
  exactOrder: 1,
  documentType: "TECHNICAL_PROPOSAL",
  format: "DOCX",
  generationStatus: "GENERATED",
  validationStatus: "PENDING",
  reviewStatus: "PENDING",
  reviewNotes: null,
  fileContent: null,
  storagePath: null,
};

describe("auto-finalize paragraph-aware DOCX hygiene repair", () => {
  it("removes split-run violations while preserving safe sentences in the same paragraph", async () => {
    const original = await makeTechnicalDocx();
    const originalText = await extractDocxVisibleText(original, DOC.exactFileName!);
    assert.ok(originalText);
    assert.ok(
      documentHygieneIssues(originalText, DOC).length > 0,
      "fixture must fail the canonical hygiene gate before repair",
    );

    const repaired = await cleanDocxHygieneIssues(original, DOC);
    assert.ok(repaired, "repair should rewrite the unsafe paragraph content");

    const repairedText = await extractDocxVisibleText(repaired, DOC.exactFileName!);
    assert.ok(repairedText);
    assert.deepEqual(
      documentHygieneIssues(repairedText, DOC),
      [],
      "the same canonical detector that blocked export must accept the repaired DOCX",
    );

    assert.match(repairedText, /technical methodology covers quality assurance/i);
    assert.match(repairedText, /financial offer is submitted separately/i);
    assert.doesNotMatch(repairedText, /USD\s*500,000/i);
    assert.doesNotMatch(repairedText, /financial\s+proposal\s+includes/i);
    assert.doesNotMatch(repairedText, /generated by\s+AI/i);
    assert.doesNotMatch(repairedText, /internal prompt/i);
  });
});
