// Tests for the centralised client-facing text sanitiser (Gap 8).
//
// Locks in the contract: every banned trace listed in the gap spec is
// removed; tender-quoted spans are preserved; non-exportable control
// placeholders are still blocked from export by other gates.

import { describe, it } from "node:test";
import { strict as assert } from "node:assert";

import {
  sanitizeClientFacingText,
  findClientFacingViolations,
} from "../lib/engine/metadata/client-text-sanitizer";
import { humanizeDeterministic } from "../lib/engine/generation/humanize";

describe("Gap 8 — forbidden tokens are removed from exportable text", () => {
  const banned = [
    "ChatGPT",
    "OpenAI",
    "Claude",
    "Gemini",
    "as an AI",
    "language model",
    "generated by",
    "deterministic fallback",
    "Submission note:",
    "TODO",
    "TBD",
    "FIXME",
    "PLACEHOLDER",
  ];

  for (const token of banned) {
    it(`removes banned token: ${token}`, () => {
      const input = `Some prose ${token} should not survive.`;
      const cleaned = sanitizeClientFacingText(input);
      assert.equal(cleaned.toLowerCase().includes(token.toLowerCase().replace(":", "")), false,
        `expected "${token}" to be removed; got: ${cleaned}`);
    });
  }

  it("sanitises long em-dashes outside quoted spans", () => {
    const cleaned = sanitizeClientFacingText("a—b");
    assert.match(cleaned, / — /);
  });

  it("findClientFacingViolations returns vendor descriptions", () => {
    const violations = findClientFacingViolations("Generated by ChatGPT for the client.");
    assert.ok(violations.some((v) => /ChatGPT/i.test(v)));
    assert.ok(violations.some((v) => /generated by/i.test(v)));
  });
});

describe("Gap 8 — tender quote preservation", () => {
  it("preserves quoted form names with brackets and dashes", () => {
    const input = 'The tender requires "Form A — Bid Letter (with Power of Attorney)" be submitted.';
    const cleaned = sanitizeClientFacingText(input, { preserveTenderQuotes: true });
    assert.ok(cleaned.includes('"Form A — Bid Letter (with Power of Attorney)"'),
      `expected the tender-quote to survive; got: ${cleaned}`);
  });

  it("still removes banned tokens OUTSIDE quoted spans even when preserveTenderQuotes=true", () => {
    const input = 'ChatGPT wrote: "Form A — Bid Letter" is required.';
    const cleaned = sanitizeClientFacingText(input, { preserveTenderQuotes: true });
    assert.equal(/ChatGPT/i.test(cleaned), false);
    assert.ok(cleaned.includes('"Form A — Bid Letter"'));
  });

  it("preserves quoted Claude-as-tender-text only when in quotes (rare)", () => {
    // Edge case: the tender literally names "Claude vs. Trustees" as a
    // legal precedent in quotes. We should leave it alone.
    const input = 'See "Claude vs. Trustees (1998)" for jurisdiction.';
    const cleaned = sanitizeClientFacingText(input, { preserveTenderQuotes: true });
    assert.ok(cleaned.includes('"Claude vs. Trustees (1998)"'));
  });

  it("when preserveTenderQuotes=false, all spans are sanitised", () => {
    const input = 'The tender quotes "ChatGPT was helpful".';
    const cleaned = sanitizeClientFacingText(input, { preserveTenderQuotes: false });
    assert.equal(/ChatGPT/i.test(cleaned), false);
  });
});

describe("Gap 8 — idempotence", () => {
  it("running the sanitiser twice yields the same result", () => {
    const input = "TODO: ChatGPT — Submission note: rewrite this — language model output.";
    const once = sanitizeClientFacingText(input);
    const twice = sanitizeClientFacingText(once);
    assert.equal(once, twice);
  });
});

describe("Gap 8 — humanizeDeterministic still applies the centralised sanitiser", () => {
  it("humanizeDeterministic output contains no banned vendor names", () => {
    const cleaned = humanizeDeterministic(
      "Generated by Claude and ChatGPT — see Submission note: refine.",
    );
    assert.equal(/ChatGPT/i.test(cleaned), false);
    assert.equal(/\bClaude\b/i.test(cleaned), false);
    assert.equal(/Submission note:/i.test(cleaned), false);
  });
});

describe("Gap 8 — non-exportable control placeholders remain blocked", () => {
  // The sanitiser REMOVES tokens from text we ship. The blocker on
  // remaining placeholders (i.e. preventing export when the AI emitted
  // a `[INSERT NAME]` token) is enforced by document-output-state.ts.
  // We just confirm here that the sanitiser does NOT silently mask the
  // structural [INSERT ...] form so the blocker can still see it.
  it("does not remove [INSERT ...] forms that the export gate uses to block release", () => {
    const input = "Hello [INSERT CLIENT NAME], please reply.";
    const cleaned = sanitizeClientFacingText(input);
    // The legacy humanize() pass strips `[insert ...]` but the new
    // sanitiser by itself only removes the documented banned tokens —
    // structural placeholders flow through unchanged so the export
    // gate keeps blocking.
    assert.ok(cleaned.includes("[INSERT CLIENT NAME]"));
  });
});
