// G7 — export readiness pure-function tests.
// Covers checkExportReadiness + exportReadinessError. The DB-dependent
// checkTenderLevelExportBlockers is integration-level and not covered
// here.

import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import JSZip from "jszip";
import { checkDocxHygieneReadiness, checkExportReadiness, documentHygieneIssues, exportReadinessError, filePlanBlockersFromLists, isReadyForFinalExport } from "../lib/engine/export-readiness";

// Minimal base64 with ZIP/PK magic bytes (0x50 0x4B) — passes looksLikeBase64Docx check.
const MINIMAL_DOCX_B64 = "UEsDBA==";
const READY = { id: "doc-1", name: "Cover Letter", exactFileName: "Cover-Letter.docx", generationStatus: "GENERATED", validationStatus: "VALIDATED", reviewStatus: "READY_FOR_EXPORT", fileContent: MINIMAL_DOCX_B64 };
const READY_TEXT = { ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent: "Technical Proposal\nThis document addresses the tender requirements with reviewed company evidence and approved submission content." };

async function fakeDocxBase64(visibleText: string): Promise<string> {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"xml\" ContentType=\"application/xml\"/></Types>");
  zip.folder("word")?.file("document.xml", `<?xml version=\"1.0\" encoding=\"UTF-8\"?><w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:body><w:p><w:r><w:t>${visibleText}</w:t></w:r></w:p></w:body></w:document>`);
  const buffer = await zip.generateAsync({ type: "nodebuffer" });
  return buffer.toString("base64");
}

describe("isReadyForFinalExport", () => {
  it("returns true when all three statuses are correct", () => {
    assert.equal(isReadyForFinalExport(READY), true);
  });
  it("returns true when reviewStatus is PENDING but validationStatus is VALIDATED (Gap C: VALIDATED is sufficient)", () => {
    // Gap C: per Gap 5, VALIDATED is sufficient for the automatic path.
    // A document with VALIDATED validationStatus and PENDING reviewStatus
    // passes isReadyForFinalExport — the canonical validator is the
    // machine-safe authority, not the human reviewStatus.
    assert.equal(isReadyForFinalExport({ ...READY, reviewStatus: "PENDING" }), true);
  });
  it("returns false when both validationStatus and reviewStatus are PENDING", () => {
    assert.equal(isReadyForFinalExport({ ...READY, validationStatus: "PENDING", reviewStatus: "PENDING" }), false);
  });
});

describe("checkExportReadiness", () => {
  it("returns ok=true for a single ready doc", () => {
    const res = checkExportReadiness([READY]);
    assert.equal(res.ok, true);
    assert.equal(res.failures.length, 0);
  });

  it("returns ok=true for clean inspectable generated text in a real DOCX", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal This submission text is clean and contains reviewed company evidence only approved content.");
    const res = checkExportReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }], { requireFileContent: true });
    assert.equal(res.ok, true);
    assert.equal(res.failures.length, 0);
  });

  it("flags every wrong status with a clear reason", () => {
    // Gap C: VALIDATED is sufficient for the automatic path — reviewStatus
    // is not required when validationStatus is VALIDATED. Use PENDING
    // validationStatus so the reviewStatus reason is still flagged.
    const bad = { ...READY, generationStatus: "FAILED", reviewStatus: "PENDING", validationStatus: "PENDING" };
    const res = checkExportReadiness([bad]);
    assert.equal(res.ok, false);
    assert.equal(res.failures.length, 1);
    const reasons = res.failures[0].reasons;
    assert.ok(reasons.some((r) => r.includes("generationStatus")));
    assert.ok(reasons.some((r) => r.includes("reviewStatus")));
  });

  it("requires fileContent when option is set", () => {
    const noContent = { ...READY, fileContent: null };
    const res = checkExportReadiness([noContent], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => r.includes("fileContent is missing")));
  });

  it("accepts storage-backed documents when fileContent is absent", () => {
    const storageBacked = { ...READY, fileContent: null, storagePath: "/tmp/generated.docx" };
    const res = checkExportReadiness([storageBacked], { requireFileContent: true });
    assert.equal(res.ok, true);
  });

  it("blocks AI/meta-preparation traces", () => {
    const res = checkExportReadiness([{ ...READY_TEXT, fileContent: "Technical Proposal\nSubmission note: this document was generated by AI and must be checked before submission." }], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => /AI\/meta-preparation trace/i.test(r)));
  });

  it("blocks placeholders and unresolved drafting instructions", () => {
    const res = checkExportReadiness([{ ...READY_TEXT, fileContent: "Technical Proposal\n[INSERT authorized signatory name here]\nThe consultant shall provide the required services." }], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => /Placeholder/i.test(r)));
  });

  it("blocks likely pricing leakage inside technical content", () => {
    const res = checkExportReadiness([{ ...READY_TEXT, fileContent: "Technical Proposal\nThe technical methodology includes a total price of USD 25,000 for the technical proposal envelope." }], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => /pricing language/i.test(r)));
  });

  it("does not block safe no-price-control wording in technical content", () => {
    const issues = documentHygieneIssues("Technical Proposal\nThis technical proposal does not include any fee, rate, unit price, total price, or financial offer values.", READY_TEXT);
    assert.equal(issues.some((r) => /pricing language/i.test(r)), false);
  });

  it("does not treat financial/commercial documents as technical for pricing hygiene", () => {
    const financialDoc = { ...READY_TEXT, name: "Financial Proposal", exactFileName: "Financial-Proposal.docx", fileContent: "Financial Proposal\nThe total price is USD 25,000." };
    const issues = documentHygieneIssues(financialDoc.fileContent, financialDoc);
    assert.equal(issues.some((r) => /pricing language/i.test(r)), false);
  });
});

describe("checkDocxHygieneReadiness", () => {
  it("passes clean DOCX visible text", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal This submission text is clean and contains reviewed company evidence only.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }]);
    assert.deepEqual(failures, []);
  });

  it("blocks AI traces inside DOCX visible text", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal Submission note: this document was generated by AI and must be checked before submission.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }]);
    assert.equal(failures.length, 1);
    assert.ok(failures[0].reasons.some((r) => /inside DOCX visible text/i.test(r)));
  });

  it("blocks placeholders inside DOCX visible text", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal [INSERT authorized signatory name here] The consultant shall provide the required services.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }]);
    assert.equal(failures.length, 1);
    assert.ok(failures[0].reasons.some((r) => /Placeholder/i.test(r)));
  });

  it("does not block safe no-price-control wording inside DOCX visible text", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal This technical proposal does not include fee amounts, rates, unit prices, total price, or financial offer values.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }]);
    assert.equal(failures.length, 0);
  });

  it("does not treat financial/commercial DOCX content as technical for pricing hygiene", async () => {
    const fileContent = await fakeDocxBase64("Financial Proposal The total price is USD 25,000.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Financial Proposal", exactFileName: "Financial-Proposal.docx", fileContent }]);
    assert.equal(failures.length, 0);
  });

  it("inspects storage-backed DOCX and blocks AI/meta traces", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal Submission note: this document was generated by AI.");
    const tmp = await mkdtemp(path.join(os.tmpdir(), "export-readiness-"));
    const p = path.join(tmp, "doc.docx");
    await writeFile(p, Buffer.from(fileContent, "base64"));
    const failures = await checkDocxHygieneReadiness([{ ...READY, fileContent: null, storagePath: p }]);
    assert.equal(failures.length, 1);
  });
});

describe("exportReadinessError", () => {
  it("returns empty string when nothing is wrong", () => {
    assert.equal(exportReadinessError([]), "");
  });
  it("includes blocker title and recommended action", () => {
    const msg = exportReadinessError([], [{
      category: "EVALUATOR_EVAL_CRITERION_MISS",
      severity: "HIGH",
      title: "Healthcare design depth not demonstrated",
      recommendedAction: "Add IPC and clinical workflow paragraphs to Section C",
    }]);
    assert.ok(msg.includes("Healthcare design depth"));
    assert.ok(msg.includes("Action: Add IPC"));
  });
  it("includes file-level reasons when failures present", () => {
    const msg = exportReadinessError([{
      documentId: "doc-1", name: "Cover Letter", fileName: "Cover-Letter.docx",
      reasons: ["reviewStatus is PENDING, expected READY_FOR_EXPORT"],
    }]);
    assert.ok(msg.includes("Cover-Letter.docx"));
    assert.ok(msg.includes("reviewStatus"));
  });
});

describe("filePlanBlockersFromLists", () => {
  it("does not treat a retained editable DOCX as an extra attachment after its required PDF exists", () => {
    const blockers = filePlanBlockersFromLists([
      { ...READY, exactOrder: 1, exactFileName: "Technical Proposal.docx", format: "DOCX" },
      { ...READY, id: "pdf", exactOrder: 1, exactFileName: "Technical Proposal.pdf", format: "PDF" },
    ], JSON.stringify(["Technical Proposal.pdf"]), JSON.stringify(["Technical Proposal.pdf"]));
    assert.deepEqual(blockers, []);
  });

  it("blocks extra generated files when tender exact naming is explicit", () => {
    const blockers = filePlanBlockersFromLists([
      { ...READY, exactFileName: "Technical-Proposal.docx" },
      { ...READY, id: "doc-2", exactFileName: "Financial-Proposal.docx" },
      { ...READY, id: "doc-3", exactFileName: "Annex-Extra.docx" },
    ], JSON.stringify(["Technical-Proposal.docx", "Financial-Proposal.docx"]), null);
    assert.ok(blockers.some((b) => b.category === "EXTRA_FILES" && b.severity === "HIGH"));
  });

  it("treats file-order mismatch as a HIGH blocker", () => {
    const blockers = filePlanBlockersFromLists([
      { ...READY, exactOrder: 1, exactFileName: "Financial-Proposal.docx" },
      { ...READY, id: "doc-2", exactOrder: 2, exactFileName: "Technical-Proposal.docx" },
    ], null, JSON.stringify(["Technical-Proposal.docx", "Financial-Proposal.docx"]));
    assert.ok(blockers.some((b) => b.category === "FILE_ORDER" && b.severity === "HIGH"));
  });

  it("flags duplicate exactOrder values as DUPLICATE_EXACT_ORDER HIGH blocker", () => {
    const blockers = filePlanBlockersFromLists([
      { ...READY, exactOrder: 1, exactFileName: "Technical-Proposal.docx" },
      { ...READY, id: "doc-2", exactOrder: 1, exactFileName: "Financial-Proposal.docx" },
      { ...READY, id: "doc-3", exactOrder: 2, exactFileName: "CV-Lead-Expert.docx" },
    ], null, null);
    assert.ok(
      blockers.some((b) => b.category === "DUPLICATE_EXACT_ORDER" && b.severity === "HIGH"),
      "Expected DUPLICATE_EXACT_ORDER HIGH blocker when two docs share exactOrder=1",
    );
  });

  it("does not flag DUPLICATE_EXACT_ORDER when all exactOrder values are unique", () => {
    const blockers = filePlanBlockersFromLists([
      { ...READY, exactOrder: 1, exactFileName: "Technical-Proposal.docx" },
      { ...READY, id: "doc-2", exactOrder: 2, exactFileName: "Financial-Proposal.docx" },
    ], null, null);
    assert.ok(
      !blockers.some((b) => b.category === "DUPLICATE_EXACT_ORDER"),
      "Should not flag DUPLICATE_EXACT_ORDER when all positions are unique",
    );
  });

  it("does not flag DUPLICATE_EXACT_ORDER when exactOrder is null/undefined", () => {
    const blockers = filePlanBlockersFromLists([
      { ...READY, exactOrder: null, exactFileName: "Technical-Proposal.docx" },
      { ...READY, id: "doc-2", exactOrder: null, exactFileName: "Financial-Proposal.docx" },
    ], null, null);
    assert.ok(
      !blockers.some((b) => b.category === "DUPLICATE_EXACT_ORDER"),
      "Null exactOrder values should not be flagged as duplicates",
    );
  });
});
