// G7 — export readiness pure-function tests.
// Covers checkExportReadiness + exportReadinessError. The DB-dependent
// checkTenderLevelExportBlockers is integration-level and not covered
// here.

import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import JSZip from "jszip";
import { checkDocxHygieneReadiness, checkExportReadiness, exportReadinessError, isReadyForFinalExport } from "../lib/engine/export-readiness";

const READY = { id: "doc-1", name: "Cover Letter", exactFileName: "Cover-Letter.docx", generationStatus: "GENERATED", validationStatus: "VALIDATED", reviewStatus: "READY_FOR_EXPORT", fileContent: "AA==" };
const READY_TEXT = { ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent: "Technical Proposal\nThis document addresses the tender requirements with reviewed company evidence and approved submission content." };

async function fakeDocxBase64(visibleText: string): Promise<string> {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"xml\" ContentType=\"application/xml\"/></Types>");
  zip.folder("word")?.file("document.xml", `<?xml version=\"1.0\" encoding=\"UTF-8\"?><w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:body><w:p><w:r><w:t>${visibleText}</w:t></w:r></w:p></w:body></w:document>`);
  const buffer = await zip.generateAsync({ type: "nodebuffer" });
  return buffer.toString("base64");
}

describe("isReadyForFinalExport", () => {
  it("returns true when all three statuses are correct", () => {
    assert.equal(isReadyForFinalExport(READY), true);
  });
  it("returns false when reviewStatus is PENDING", () => {
    assert.equal(isReadyForFinalExport({ ...READY, reviewStatus: "PENDING" }), false);
  });
});

describe("checkExportReadiness", () => {
  it("returns ok=true for a single ready doc", () => {
    const res = checkExportReadiness([READY]);
    assert.equal(res.ok, true);
    assert.equal(res.failures.length, 0);
  });

  it("returns ok=true for clean inspectable generated text", () => {
    const res = checkExportReadiness([READY_TEXT], { requireFileContent: true });
    assert.equal(res.ok, true);
    assert.equal(res.failures.length, 0);
  });

  it("flags every wrong status with a clear reason", () => {
    const bad = { ...READY, generationStatus: "FAILED", reviewStatus: "PENDING" };
    const res = checkExportReadiness([bad]);
    assert.equal(res.ok, false);
    assert.equal(res.failures.length, 1);
    const reasons = res.failures[0].reasons;
    assert.ok(reasons.some((r) => r.includes("generationStatus")));
    assert.ok(reasons.some((r) => r.includes("reviewStatus")));
  });

  it("requires fileContent when option is set", () => {
    const noContent = { ...READY, fileContent: null };
    const res = checkExportReadiness([noContent], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => r.includes("fileContent is missing")));
  });

  it("blocks AI/meta-preparation traces", () => {
    const res = checkExportReadiness([{ ...READY_TEXT, fileContent: "Technical Proposal\nSubmission note: this document was generated by AI and must be checked before submission." }], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => /AI\/meta-preparation trace/i.test(r)));
  });

  it("blocks placeholders and unresolved drafting instructions", () => {
    const res = checkExportReadiness([{ ...READY_TEXT, fileContent: "Technical Proposal\n[INSERT authorized signatory name here]\nThe consultant shall provide the required services." }], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => /Placeholder/i.test(r)));
  });

  it("blocks likely pricing leakage inside technical content", () => {
    const res = checkExportReadiness([{ ...READY_TEXT, fileContent: "Technical Proposal\nThe technical methodology includes a total price of USD 25,000 for the technical proposal envelope." }], { requireFileContent: true });
    assert.equal(res.ok, false);
    assert.ok(res.failures[0].reasons.some((r) => /pricing language/i.test(r)));
  });
});

describe("checkDocxHygieneReadiness", () => {
  it("passes clean DOCX visible text", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal This submission text is clean and contains reviewed company evidence only.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }]);
    assert.deepEqual(failures, []);
  });

  it("blocks AI traces inside DOCX visible text", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal Submission note: this document was generated by AI and must be checked before submission.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }]);
    assert.equal(failures.length, 1);
    assert.ok(failures[0].reasons.some((r) => /inside DOCX visible text/i.test(r)));
  });

  it("blocks placeholders inside DOCX visible text", async () => {
    const fileContent = await fakeDocxBase64("Technical Proposal [INSERT authorized signatory name here] The consultant shall provide the required services.");
    const failures = await checkDocxHygieneReadiness([{ ...READY, name: "Technical Proposal", exactFileName: "Technical-Proposal.docx", fileContent }]);
    assert.equal(failures.length, 1);
    assert.ok(failures[0].reasons.some((r) => /Placeholder/i.test(r)));
  });
});

describe("exportReadinessError", () => {
  it("returns empty string when nothing is wrong", () => {
    assert.equal(exportReadinessError([]), "");
  });
  it("includes blocker title and recommended action", () => {
    const msg = exportReadinessError([], [{
      category: "EVALUATOR_EVAL_CRITERION_MISS",
      severity: "HIGH",
      title: "Healthcare design depth not demonstrated",
      recommendedAction: "Add IPC and clinical workflow paragraphs to Section C",
    }]);
    assert.ok(msg.includes("Healthcare design depth"));
    assert.ok(msg.includes("Action: Add IPC"));
  });
  it("includes file-level reasons when failures present", () => {
    const msg = exportReadinessError([{
      documentId: "doc-1", name: "Cover Letter", fileName: "Cover-Letter.docx",
      reasons: ["reviewStatus is PENDING, expected READY_FOR_EXPORT"],
    }]);
    assert.ok(msg.includes("Cover-Letter.docx"));
    assert.ok(msg.includes("reviewStatus"));
  });
});
