/**
 * Owner UAT deadlock (Preview, tender 0b0e1dcd).
 *
 * Requirements and Evidence showed the two outstanding mandatory requirements
 * as PARTIAL, each carrying a BUILD_PLAN_ITEM link reading "planned output
 * pending generated bytes" — they were waiting for a document to be generated.
 * Generation Readiness simultaneously refused to generate that document:
 * "Automatic matching found release-qualified FULL/SUBSTANTIAL coverage for
 * 2/4 mandatory requirements." Neither side could move first.
 *
 * canonical-workflow-decision already carries an allowance for exactly this —
 * requirements waiting only on a file this workflow generates count as
 * satisfied AT THE GENERATION GATE AND NOWHERE ELSE. It was querying
 * `evidenceType: "AUTO_PLANNED_ARTIFACT"`, but automatic-requirement-coverage
 * persists that value in `evidenceSource` and puts the recordType
 * ("BUILD_PLAN_ITEM") in `evidenceType`. The filter matched no row ever
 * written, so the allowance was dead code and the deadlock was structural.
 */

import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { buildCanonicalWorkflowDecision } from "../lib/engine/canonical-workflow-decision";

function decisionWith(overrides: Partial<Parameters<typeof buildCanonicalWorkflowDecision>[0]>) {
  return buildCanonicalWorkflowDecision({
    hasFiles: true,
    extractionUnsafe: false,
    extractionCorrupted: false,
    ocrRequired: false,
    aiAnalysisExists: true,
    aiAnalysisTrusted: true,
    aiAnalysisPartial: false,
    aiAnalysisStale: false,
    resumableAnalysisAvailable: false,
    criticalTenderDetailsValid: true,
    requirementsExist: true,
    requirementsTrusted: true,
    mandatoryRequirementCount: 4,
    mandatoryTracedCount: 4,
    mandatoryComplianceRowsCount: 4,
    mandatoryFullOrSubstantialCoverageCount: 2,
    mandatoryAwaitingPlannedOutputCount: 2,
    confirmedBuildPlanExists: true,
    requiredDocumentsTotal: 1,
    generatedDocumentsTotal: 0,
    exportReadyDocumentsTotal: 0,
    documentsValidated: false,
    documentsApproved: false,
    pdfRequiredButUnavailable: false,
    finalExportAllowed: false,
    authorityOrQualityBlockers: false,
    ...overrides,
  });
}

describe("evidence awaiting planned output never blocks generation", () => {
  it("2 covered + 2 awaiting generated bytes does not raise the coverage blocker", () => {
    const decision = decisionWith({});
    assert.ok(
      !decision.blockerCodes.includes("MANDATORY_NO_FULL_SUBSTANTIAL_COVERAGE"),
      "requirements waiting only on the file this gate produces must not block that gate",
    );
  });

  it("the deadlock reproduces when the allowance is lost", () => {
    // This is the shape the broken evidenceType filter produced: the allowance
    // counted 0 because it matched no persisted row.
    const decision = decisionWith({ mandatoryAwaitingPlannedOutputCount: 0 });
    assert.ok(
      decision.blockerCodes.includes("MANDATORY_NO_FULL_SUBSTANTIAL_COVERAGE"),
      "fixture must reproduce the deadlock the allowance exists to prevent",
    );
  });

  it("genuinely uncovered requirements still block — the allowance is not a bypass", () => {
    // One requirement is neither covered nor awaiting a planned output.
    const decision = decisionWith({
      mandatoryFullOrSubstantialCoverageCount: 2,
      mandatoryAwaitingPlannedOutputCount: 1,
    });
    assert.ok(
      decision.blockerCodes.includes("MANDATORY_NO_FULL_SUBSTANTIAL_COVERAGE"),
      "evidence that is missing for real must still fail closed",
    );
  });
});

describe("the planned-output allowance queries the column the writer fills", () => {
  const decisionSrc = readFileSync("lib/engine/canonical-workflow-decision.ts", "utf8");
  const writerSrc = readFileSync("lib/engine/automatic-requirement-coverage.ts", "utf8");

  it("filters evidenceSource, not evidenceType", () => {
    assert.match(
      decisionSrc,
      /complianceMatrixRows: \{ some: \{ evidenceSource: "AUTO_PLANNED_ARTIFACT" \} \}/,
    );
    assert.doesNotMatch(
      decisionSrc,
      /complianceMatrixRows: \{ some: \{ evidenceType: "AUTO_PLANNED_ARTIFACT" \} \}/,
      "AUTO_PLANNED_ARTIFACT is never written to evidenceType",
    );
  });

  it("the writer still puts AUTO_PLANNED_ARTIFACT in evidenceSource", () => {
    // If this ever moves, the query above must move with it.
    assert.match(writerSrc, /evidenceType: item\.candidate\.recordType/);
    assert.match(writerSrc, /evidenceSource: automaticEvidenceSource\(item\.candidate\.recordType\)/);
    assert.match(writerSrc, /if \(recordType === "BUILD_PLAN_ITEM"\) return "AUTO_PLANNED_ARTIFACT";/);
  });
});
