import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";

// The implementation of this route now lives in
// lib/engine/missing-plan-file-generation.ts so the auto-finalize worker can
// run the same code with the same gates. Read both halves of the path — the
// assertions here are about what the path does, not which file holds it.
const source = readFileSync("app/api/tenders/[id]/generate-missing-plan-files/route.ts", "utf8")
  + readFileSync("lib/engine/missing-plan-file-generation.ts", "utf8");

describe("missing-plan transactional persistence safety", () => {
  it("rechecks readiness under the shared tender lock", () => {
    assert.match(source, /prisma\.\$transaction\(async \(tx\) => \{/);
    assert.match(source, /withTransactionalGenerationGate\(\{/);
    assert.match(source, /purpose: "generate-missing-plan-files"/);
    assert.match(source, /write: async \(lockedTx\) => \{/);
  });

  it("persists all document mutations through the locked transaction client", () => {
    const lockedRegion = source.slice(source.indexOf("write: async (lockedTx)"));
    assert.ok(lockedRegion.length > 0, "locked write callback must exist");
    assert.doesNotMatch(lockedRegion, /await prisma\.generatedDocument\.(create|update|upsert)/);
    assert.match(lockedRegion, /lockedTx\.generatedDocument\.findFirst/);
    assert.match(lockedRegion, /lockedTx\.generatedDocument\.create/);
    assert.match(lockedRegion, /lockedTx\.generatedDocument\.update/);
  });

  it("revalidates the confirmed Build Plan before persistence", () => {
    assert.match(source, /expectedPlanFingerprint/);
    assert.match(source, /BUILD_PLAN_CHANGED_BEFORE_PERSISTENCE/);
    // The implementation moved into lib/engine/missing-plan-file-generation.ts,
    // where the tender and user arrive as parameters rather than being read off
    // the request actor. The property — the confirmed plan is re-read inside the
    // locked write and compared against the fingerprint captured before it — is
    // unchanged.
    assert.match(source, /getCurrentConfirmedBuildPlan\(prisma, tenderId, userId\)/);
  });

  it("keeps the whole batch atomic when readiness changes", () => {
    assert.match(source, /No batch document writes were committed/);
    assert.match(source, /error instanceof GenerationPersistenceBlockedError/);
    const transactionRegion = source.slice(source.indexOf("await prisma.$transaction"), source.indexOf("await logAction", source.indexOf("await prisma.$transaction")));
    assert.match(transactionRegion, /for \(const document of preparedMissing\)/);
    assert.match(transactionRegion, /for \(const document of preparedPlanned\)/);
  });

  it("resets stale approval whenever generated bytes change", () => {
    assert.match(source, /reviewedBy: null/);
    assert.match(source, /reviewedAt: null/);
    assert.match(source, /validationStatus: document\.validationStatus/);
    assert.match(source, /reviewStatus: document\.reviewStatus/);
  });
});
