import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";

const forgotPage = readFileSync("app/forgot-password/page.tsx", "utf8");
const resetPage = readFileSync("app/reset-password/page.tsx", "utf8");
const forgotRoute = readFileSync("app/api/auth/forgot-password/route.ts", "utf8");

describe("password reset client contract", () => {
  it("forgot-password UI requests instructions without claiming it generates a link", () => {
    assert.match(forgotPage, /request password reset instructions/i);
    assert.match(forgotPage, /Request reset instructions/);
    assert.doesNotMatch(forgotPage, /generate a reset link/i);
    assert.doesNotMatch(forgotPage, /Generate Reset Link/);
  });

  it("forgot-password UI never renders or copies a raw reset token link", () => {
    assert.doesNotMatch(forgotPage, /resetLink/);
    assert.doesNotMatch(forgotPage, /clipboard\.writeText/);
    assert.doesNotMatch(forgotPage, /Copy to clipboard/);
    assert.doesNotMatch(forgotPage, /expiresInMinutes/);
  });

  it("server route also does not return resetLink or expiresInMinutes fields", () => {
    assert.doesNotMatch(forgotRoute, /resetLink/);
    assert.doesNotMatch(forgotRoute, /expiresInMinutes/);
  });

  it("reset-password page accepts the token-only link generated by the server", () => {
    assert.match(forgotRoute, /reset-password\?token=\$\{encodeURIComponent\(token\)\}/);
    assert.doesNotMatch(resetPage, /params\.get\("uid"\)/);
    assert.doesNotMatch(resetPage, /!uid/);
    assert.match(resetPage, /body: JSON\.stringify\(\{ token, password \}\)/);
    assert.match(resetPage, /disabled=\{loading \|\| !token\}/);
  });
});
