import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { CANONICAL_AI_PROVIDER_ORDER } from "../lib/ai-provider-registry";
import { computeFileHash, isStrictBase64, toBuffer, validateGeneratedFileBytes, validatePackageManifest } from "../lib/engine/generated-file-integrity";
import { buildFinalPackageManifest, manifestFingerprint } from "../lib/engine/final-package-manifest";
import { computeTenderSourceFingerprint, isWorkflowOutputStale } from "../lib/engine/tender-source-fingerprint";
import { deriveIdempotencyKey, extractWorkflowIdempotencyKey, runTenderWorkflow, WorkflowError } from "../lib/engine/tender-workflow-runner";

type Run = any;

function createMockPrisma(options: { failCreateOnceWithUnique?: boolean } = {}) {
  const runs: Run[] = [];
  const documents: any[] = [];
  const audits: any[] = [];
  let failedCreateOnce = false;
  return {
    runs,
    documents,
    audits,
    tenderWorkflowRun: {
      findUnique: async ({ where }: any) => runs.find((r) => r.companyId === where.companyId_tenderId_operation_idempotencyKey.companyId && r.tenderId === where.companyId_tenderId_operation_idempotencyKey.tenderId && r.operation === where.companyId_tenderId_operation_idempotencyKey.operation && r.idempotencyKey === where.companyId_tenderId_operation_idempotencyKey.idempotencyKey) ?? null,
      findFirst: async ({ where }: any) => runs.find((r) => r.companyId === where.companyId && r.tenderId === where.tenderId && (!where.operation || r.operation === where.operation) && where.status.in.includes(r.status)) ?? null,
      create: async ({ data }: any) => { if (options.failCreateOnceWithUnique && !failedCreateOnce) { failedCreateOnce = true; const err: any = new Error("unique conflict"); err.code = "P2002"; throw err; } runs.push({ ...data, createdAt: new Date(), updatedAt: new Date() }); return data; },
      update: async ({ where, data }: any) => { const r = runs.find((x) => x.id === where.id); Object.assign(r, data); return r; },
    },
    generatedDocument: {
      create: async ({ data }: any) => { const row = { id: `doc-${documents.length + 1}`, ...data }; documents.push(row); return row; },
    },
    auditLog: {
      create: async ({ data }: any) => {
        const row = { id: `audit-${audits.length + 1}`, ...data };
        audits.push(row);
        return row;
      },
    },
    $transaction: async (fn: any) => fn({ generatedDocument: { create: async ({ data }: any) => { const row = { id: `doc-${documents.length + 1}`, ...data }; documents.push(row); return row; } } }),
  } as any;
}

describe("production tender workflow runner", () => {
  it("same Generate Draft idempotency key replays the prior result without duplicate documents", async () => {
    const prisma = createMockPrisma();
    const key = deriveIdempotencyKey({ tenantId: "tenant", tenderId: "tender", operation: "GENERATE_DRAFT", requestBody: { section: "all" } });
    const first = await runTenderWorkflow({
      prisma,
      tenantId: "tenant",
      tenderId: "tender",
      userId: "user",
      operation: "GENERATE_DRAFT",
      idempotencyKey: key,
      execute: async ({ tx }) => {
        const doc = await tx.generatedDocument.create({ data: { tenderId: "tender", name: "Technical", documentType: "TECHNICAL_PROPOSAL", fileContent: Buffer.from("valid generated bytes for docx").toString("base64") } });
        return { createdDocumentIds: [doc.id], warnings: [], blockers: [], recoverable: false };
      },
    });
    const second = await runTenderWorkflow({
      prisma,
      tenantId: "tenant",
      tenderId: "tender",
      userId: "user",
      operation: "GENERATE_DRAFT",
      idempotencyKey: key,
      execute: async () => { throw new Error("must not execute replay"); },
    });
    assert.deepEqual(second.createdDocumentIds, first.createdDocumentIds);
    assert.equal(second.replayed, true);
    assert.equal(prisma.documents.length, 1);
    assert.equal(prisma.audits.length, 1);
    assert.equal(prisma.audits[0].action, "TENDER_WORKFLOW_RUN");
    assert.equal(prisma.audits[0].userId, "user");
    assert.equal(prisma.audits[0].entityId, "tender");
    const auditMetadata = JSON.parse(prisma.audits[0].metadata);
    assert.equal(auditMetadata.tenantId, "tenant");
    assert.equal(auditMetadata.tenderId, "tender");
    assert.equal(auditMetadata.operation, "GENERATE_DRAFT");
    assert.equal(auditMetadata.status, "succeeded");
    assert.deepEqual(auditMetadata.createdDocumentIds, first.createdDocumentIds);
    assert.equal(auditMetadata.blockersCount, 0);
    assert.equal(auditMetadata.warningsCount, 0);
  });

  it("operation already running returns OPERATION_IN_PROGRESS instead of starting a duplicate", async () => {
    const prisma = createMockPrisma();
    prisma.runs.push({ id: "active-run", companyId: "tenant", tenderId: "tender", operation: "BUILD_FINAL_ZIP", idempotencyKey: "other", status: "RUNNING" });
    await assert.rejects(
      runTenderWorkflow({ prisma, tenantId: "tenant", tenderId: "tender", userId: "user", operation: "BUILD_FINAL_ZIP", idempotencyKey: "new", execute: async () => ({}) }),
      (err: any) => err instanceof WorkflowError && err.errorCode === "OPERATION_IN_PROGRESS" && err.status === 409,
    );
  });



  it("blocks a different operation while any tender workflow is already active", async () => {
    const prisma = createMockPrisma();
    prisma.runs.push({ id: "active-ai", companyId: "tenant", tenderId: "tender", operation: "AI_ANALYZE", idempotencyKey: "ai", status: "RUNNING" });
    await assert.rejects(
      runTenderWorkflow({ prisma, tenantId: "tenant", tenderId: "tender", userId: "user", operation: "GENERATE_DRAFT", idempotencyKey: "gen", execute: async () => ({}) }),
      (err: any) => err instanceof WorkflowError && err.errorCode === "OPERATION_IN_PROGRESS" && err.blockers.includes("active-ai"),
    );
    assert.equal(prisma.documents.length, 0);
  });

  it("sanitizes explicit idempotency keys and extracts them from standard headers", () => {
    const req = new Request("https://example.test", { headers: { "Idempotency-Key": " user clicked/key 1 " } });
    assert.equal(extractWorkflowIdempotencyKey(req), "user-clicked-key-1");
    assert.equal(deriveIdempotencyKey({ explicitKey: " bad/key with spaces ", tenantId: "t", tenderId: "x", operation: "GENERATE_DRAFT" }), "bad-key-with-spaces");
  });

  it("recoverable failed run can be retried with a new key without duplicate prior output", async () => {
    const prisma = createMockPrisma();
    const failed = await runTenderWorkflow({
      prisma,
      tenantId: "tenant",
      tenderId: "tender",
      userId: "user",
      operation: "AI_ANALYZE",
      idempotencyKey: "provider-timeout",
      execute: async () => { throw new WorkflowError("PROVIDER_FAILURE", "provider exhausted sk-test-secret", 503, true, "Retry AI Analyze"); },
    });
    assert.equal(failed.ok, false);
    assert.equal(failed.recoverable, true);
    assert.equal(prisma.documents.length, 0);
    const retry = await runTenderWorkflow({ prisma, tenantId: "tenant", tenderId: "tender", userId: "user", operation: "AI_ANALYZE", idempotencyKey: "retry-1", execute: async () => ({ warnings: [], blockers: [] }) });
    assert.equal(retry.ok, true);
    assert.equal(prisma.runs.length, 2);
    assert.equal(prisma.audits.length, 2);
    assert.deepEqual(
      prisma.audits.map((audit: any) => {
        const metadata = JSON.parse(audit.metadata);
        return { status: metadata.status, errorCode: metadata.errorCode };
      }),
      [
        { status: "failed", errorCode: "PROVIDER_FAILURE" },
        { status: "succeeded", errorCode: null },
      ],
    );
    assert.doesNotMatch(JSON.stringify(prisma.runs), /sk-test-secret/);
  });



  it("handles unique-key race by replaying the winner instead of executing twice", async () => {
    const prisma = createMockPrisma({ failCreateOnceWithUnique: true });
    const winningResult = {
      ok: true,
      operation: "GENERATE_DRAFT",
      tenderId: "tender",
      tenantId: "tenant",
      runId: "winner",
      idempotencyKey: "same-key",
      status: "succeeded",
      createdDocumentIds: ["doc-winner"],
      warnings: [],
      blockers: [],
      recoverable: false,
    };
    prisma.runs.push({ id: "winner", companyId: "tenant", tenderId: "tender", operation: "GENERATE_DRAFT", idempotencyKey: "same-key", status: "SUCCEEDED", resultJson: winningResult });
    const replay = await runTenderWorkflow({
      prisma,
      tenantId: "tenant",
      tenderId: "tender",
      userId: "user",
      operation: "GENERATE_DRAFT",
      idempotencyKey: "same-key",
      execute: async () => { throw new Error("must not execute after P2002 replay"); },
    });
    assert.equal(replay.replayed, true);
    assert.deepEqual(replay.createdDocumentIds, ["doc-winner"]);
    assert.equal(prisma.documents.length, 0);
  });

  it("does not persist non-JSON payloads in replayable workflow resultJson", async () => {
    const prisma = createMockPrisma();
    await runTenderWorkflow({
      prisma,
      tenantId: "tenant",
      tenderId: "tender",
      userId: "user",
      operation: "DOWNLOAD_PACKAGE",
      idempotencyKey: "download-1",
      execute: async () => ({ payload: Buffer.from("zip bytes"), packageId: "pkg-1", warnings: [], blockers: [] }),
    });
    assert.equal(prisma.runs[0].resultJson.payload, undefined);
    assert.equal(prisma.runs[0].resultJson.packageId, "pkg-1");
  });
});

describe("generated file integrity", () => {
  it("rejects zero-byte, missing, hash-mismatched, and wrong-extension files", () => {
    assert.equal(validateGeneratedFileBytes({ tenantId: "t", tenderId: "x", filename: "a.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", bytes: Buffer.alloc(0) }).problem, "ZERO_BYTE_FILE");
    assert.equal(validateGeneratedFileBytes({ tenantId: "t", tenderId: "x", filename: "a.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", bytes: null }).problem, "MISSING_BYTES");
    assert.equal(validateGeneratedFileBytes({ tenantId: "t", tenderId: "x", filename: "a.pdf", mimeType: "application/pdf", bytes: Buffer.from("enough bytes for content"), expectedExtension: "docx", minBytes: 16 }).problem, "EXTENSION_MISMATCH");
    assert.equal(validateGeneratedFileBytes({ tenantId: "t", tenderId: "x", filename: "a.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", bytes: Buffer.from("enough bytes for content"), minBytes: 16, storedSha256: "0".repeat(64) }).problem, "HASH_MISMATCH");
  });


  it("does not misclassify plain ASCII strings as base64 file bytes", () => {
    assert.equal(isStrictBase64("abcdef"), false);
    assert.equal(isStrictBase64(Buffer.from("valid bytes").toString("base64")), true);
    const plain = validateGeneratedFileBytes({ tenantId: "tenant", tenderId: "tender", filename: "a.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", bytes: "plain-ascii-document-content", minBytes: 16 });
    assert.equal(plain.ok, true);
    assert.equal(plain.byteSize, Buffer.byteLength("plain-ascii-document-content"));
  });


  it("treats plain text fileContent as UTF-8 unless it is strict base64", () => {
    assert.equal(toBuffer("abcdef").toString("utf8"), "abcdef");
    const encoded = Buffer.from("real document bytes").toString("base64");
    assert.equal(toBuffer(encoded).toString("utf8"), "real document bytes");
  });

  it("download hash matches stored hash", () => {
    const bytes = Buffer.from("valid generated document bytes");
    const hash = computeFileHash(bytes);
    const result = validateGeneratedFileBytes({ tenantId: "tenant", ownerTenantId: "tenant", tenderId: "tender", filename: "a.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", bytes, storedSha256: hash, minBytes: 16 });
    assert.equal(result.ok, true);
    assert.equal(result.sha256, hash);
  });
});

describe("final package manifest", () => {
  it("rejects invalid required items, duplicate filenames, bad hashes, and stale docs", () => {
    const validation = validatePackageManifest([
      { documentId: "1", filename: "a.docx", required: true, source: "generated", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", byteSize: 0, sha256: "", order: 1, valid: false },
      { documentId: "2", filename: "a.docx", required: true, source: "generated", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", byteSize: 10, sha256: "a".repeat(64), order: 2, valid: true, stale: true },
    ]);
    assert.equal(validation.ok, false);
    assert.ok(validation.blockers.some((b) => b.includes("duplicate filename")));
    assert.ok(validation.blockers.some((b) => b.includes("stale document")));
  });

  it("builds stable ordered manifest fingerprints from explicit manifest items", () => {
    const built = buildFinalPackageManifest([
      { id: "b", exactFileName: "B.docx", exactOrder: 2, fileContent: Buffer.from("valid bytes for b document").toString("base64"), generationStatus: "GENERATED" },
      { id: "a", exactFileName: "A.docx", exactOrder: 1, fileContent: Buffer.from("valid bytes for a document").toString("base64"), generationStatus: "GENERATED" },
    ]);
    assert.equal(built.ok, true);
    assert.deepEqual(built.items.map((i) => i.filename), ["A.docx", "B.docx"]);
    assert.match(manifestFingerprint(built.items), /^[a-f0-9]{64}$/);
  });
});

describe("source fingerprint staleness", () => {
  it("source upload, extraction, BuildPlan, or asset revision changes mark outputs stale", () => {
    const before = computeTenderSourceFingerprint({ sourceFiles: [{ id: "file-1", contentHash: "h1" }], extractionRevision: 1, analysisRevision: 1, buildPlanRevision: 1, assetRevision: 1 });
    const afterSourceUpload = computeTenderSourceFingerprint({ sourceFiles: [{ id: "file-1", contentHash: "h1" }, { id: "file-2", contentHash: "h2" }], extractionRevision: 1, analysisRevision: 1, buildPlanRevision: 1, assetRevision: 1 });
    const afterExtraction = computeTenderSourceFingerprint({ sourceFiles: [{ id: "file-1", contentHash: "h1" }], extractionRevision: 2, analysisRevision: 1, buildPlanRevision: 1, assetRevision: 1 });
    const afterPlan = computeTenderSourceFingerprint({ sourceFiles: [{ id: "file-1", contentHash: "h1" }], extractionRevision: 1, analysisRevision: 1, buildPlanRevision: 2, assetRevision: 1 });
    const afterAsset = computeTenderSourceFingerprint({ sourceFiles: [{ id: "file-1", contentHash: "h1" }], extractionRevision: 1, analysisRevision: 1, buildPlanRevision: 1, assetRevision: 2 });
    assert.equal(isWorkflowOutputStale(before, afterSourceUpload), true);
    assert.equal(isWorkflowOutputStale(before, afterExtraction), true);
    assert.equal(isWorkflowOutputStale(before, afterPlan), true);
    assert.equal(isWorkflowOutputStale(before, afterAsset), true);
  });
});


  it("bootstrap includes TenderWorkflowRun indexes required by idempotency and diagnostics", () => {
    const source = readFileSync("lib/prisma.ts", "utf8");
    assert.match(source, /CREATE TABLE IF NOT EXISTS "TenderWorkflowRun"/);
    assert.match(source, /TenderWorkflowRun_companyId_tenderId_operation_idempotencyKey_key/);
    assert.match(source, /TenderWorkflowRun_companyId_tenderId_operation_status_idx/);
    assert.match(source, /TenderWorkflowRun_tenderId_createdAt_idx/);
  });


describe("provider fallback order guard", () => {
  it("fallback order is exact and OCR is not listed as an LLM provider", () => {
    assert.deepEqual([...CANONICAL_AI_PROVIDER_ORDER], ["gemini", "groq", "mistral", "zai", "openrouter", "cerebras", "openai", "together", "deepseek", "anthropic"]);
    assert.equal(CANONICAL_AI_PROVIDER_ORDER.includes("ocr" as any), false);
  });
});
