// Tests for the final-export traceability leakage scanner.
//
// Product rule: internal traceability is kept on the server (source
// IDs, match scores, evidence IDs, AI provider names, audit notes)
// but MUST NEVER reach the final submission DOCX shown to the
// evaluator. This test set verifies the expanded forbidden-pattern
// list in app/api/tenders/[id]/download/route.ts fires on every
// canonical leakage marker.
//
// The patterns are inlined here (same approach as the existing
// export-package-flow tests) so any drift between this list and
// download/route.ts surfaces as a test diff.

import { describe, it } from "node:test";
import { strict as assert } from "node:assert";

const FORBIDDEN_PATTERNS: RegExp[] = [
  /AI_DRAFT/i,
  /REGEX_DRAFT/i,
  /remove before submission/i,
  /\[\s*(?:INSERT|TBD|TBA|TODO|FILL[-_\s]*IN|PLACEHOLDER|YOUR\s+\w+\s+HERE|DATE|NAME|CLIENT|VALUE|AMOUNT)\b[^\]]*\]/i,
  /sample text/i,
  /lorem ipsum/i,
  /=+\s*PAGE\s+\d+\s*=+/i,
  /PARSED TEXT FOR PAGE/i,
  /Company evidence available:/i,
  /Project evidence available:/i,
  /\bas an AI\b/i,
  /\bAI-generated\b/i,
  /\blanguage model\b/i,
  /\bChatGPT\b/i,
  /\bOpenAI\b/i,
  /\bAnthropic\b/i,
  /\bClaude\b/i,
  /\bGemini\b/i,
  /\bDeepSeek\b/i,
  /\bgenerated by (?:AI|Claude|Gemini|OpenAI|DeepSeek|ChatGPT|the engine)\b/i,
  /\bprompt[\s:]+/i,
  /\bsource snippet\b/i,
  /\bsource quote\b/i,
  /\bsource[-_\s]grounded\b/i,
  /\btraceability map\b/i,
  /\binternal use only\b/i,
  /\bfor internal use\b/i,
  /\breviewer note\b/i,
  /\bmatch score\s*[:=]\s*\d/i,
  /\bevaluator score\s*[:=]\s*\d/i,
  /\bwin probability\s*[:=]?\s*\d/i,
  /\bevidence id\s*[:=]\s*[a-z0-9-]/i,
  /\baudit metadata\b/i,
  /\bsource id\s*[:=]\s*[a-z0-9-]/i,
  /\bdeterministic safety import\b/i,
];

function flaggedBy(patterns: RegExp[], text: string): RegExp | null {
  for (const p of patterns) {
    if (p.test(text)) return p;
  }
  return null;
}

describe("FORBIDDEN_PATTERNS — AI / language-model self-references", () => {
  const cases = [
    "As an AI, I cannot help further.",
    "This document was AI-generated by our internal system.",
    "Note: this prompt was given to the language model.",
    "We used ChatGPT to draft the technical methodology.",
    "Powered by OpenAI's GPT-4 model.",
    "Anthropic's Claude generated the executive summary.",
    "Claude wrote the cover letter.",
    "Gemini was used as a fallback provider.",
    "DeepSeek API returned the rewrite.",
    "Generated by Claude.",
    "Generated by the engine.",
    "Prompt: rewrite this section for clarity.",
  ];
  for (const text of cases) {
    it(`flags: "${text.slice(0, 60)}..."`, () => {
      const hit = flaggedBy(FORBIDDEN_PATTERNS, text);
      assert.ok(hit, `expected a forbidden pattern to match: ${text}`);
    });
  }
});

describe("FORBIDDEN_PATTERNS — internal traceability markers", () => {
  const cases = [
    "Source snippet: 'The bidder shall provide CVs...'",
    "Source quote drawn from page 12.",
    "This claim is source-grounded against requirement TR-01.",
    "Traceability map attached for internal audit.",
    "Internal use only — do not share with client.",
    "For internal use, see appendix A.",
    "Reviewer note: confirm contract value before submission.",
    "Match score: 0.87",
    "evaluator score = 9 / 10",
    "Win probability: 78",
    "evidence id: ev-12345",
    "audit metadata included for traceability.",
    "source id: req-007",
    "deterministic safety import applied",
  ];
  for (const text of cases) {
    it(`flags: "${text.slice(0, 60)}..."`, () => {
      const hit = flaggedBy(FORBIDDEN_PATTERNS, text);
      assert.ok(hit, `expected a forbidden pattern to match: ${text}`);
    });
  }
});

describe("FORBIDDEN_PATTERNS — legacy markers still covered", () => {
  it("flags AI_DRAFT, REGEX_DRAFT, remove before submission", () => {
    assert.ok(flaggedBy(FORBIDDEN_PATTERNS, "Expert was AI_DRAFT before review."));
    assert.ok(flaggedBy(FORBIDDEN_PATTERNS, "Project entry is REGEX_DRAFT."));
    assert.ok(flaggedBy(FORBIDDEN_PATTERNS, "[REMOVE BEFORE SUBMISSION] — bid team note"));
  });
});

describe("FORBIDDEN_PATTERNS — does NOT false-positive on normal proposal prose", () => {
  // These sentences appear in real tender proposals and must NOT be
  // flagged. If any flags, the leakage scan would block legitimate
  // exports.
  const safeCases = [
    "Our firm has delivered comparable water-supply projects across East Africa.",
    "Dr. Alemu served as Team Leader on the 2022 Sebeta WASH project (ETB 18M, World Bank).",
    "We propose a three-stage quality review for every deliverable.",
    "The technical methodology is informed by EBCS-7 hydraulic standards.",
    "Section A.2 details our corporate metadata, including registration number 12345.",
    "Our 18-engineer team brings cross-disciplinary expertise.",
    "We confirm the firm's compliance with the tender's mandatory eligibility requirements.",
  ];
  for (const text of safeCases) {
    it(`does NOT flag legitimate text: "${text.slice(0, 60)}..."`, () => {
      const hit = flaggedBy(FORBIDDEN_PATTERNS, text);
      assert.equal(hit, null, `unexpected match on legitimate proposal text. Pattern: ${hit?.source}; text: "${text}"`);
    });
  }
});
