import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Regression pin: lib/engine/canonical-workflow-decision.ts carried its OWN
// definition of "a current document" — `d.generationStatus === "GENERATED"` —
// and it disagreed with the export gate in the dangerous direction.
//
// exportReadyDocumentsTotal from this file is surfaced by
// /api/tenders/[id]/workflow-status, so the workflow told the owner the package
// was export-ready while the final package gate refused it.

import { filterFinalExportCandidateDocuments } from "../lib/engine/document-output-state";

const ROOT = join(__dirname, "..");
const read = (p: string) => readFileSync(join(ROOT, p), "utf8");

/** One genuinely current row, plus one row per exclusion the gate makes. */
const ROWS = [
  { id: "real", name: "Technical Proposal.docx", generationStatus: "GENERATED", validationStatus: "PASSED", reviewStatus: "PENDING" },
  { id: "notExportable", name: "Submission Rules.docx", generationStatus: "GENERATED", validationStatus: "PASSED", reviewStatus: "NOT_EXPORTABLE" },
  { id: "awaitingOriginal", name: "Trade Licence.pdf", generationStatus: "GENERATED", validationStatus: "PASSED", reviewStatus: "REPLACE_WITH_ORIGINAL" },
  { id: "controlFormat", name: "Packaging Rules", generationStatus: "GENERATED", validationStatus: "PASSED", reviewStatus: "PENDING", format: "CONTROL" },
  { id: "submissionControl", name: "Delivery Rules", generationStatus: "GENERATED", validationStatus: "PASSED", reviewStatus: "PENDING", documentType: "SUBMISSION_CONTROL" },
  { id: "quickDraft", name: "AI Proposal (Quick Draft)", generationStatus: "GENERATED", validationStatus: "PASSED", reviewStatus: "PENDING" },
];

describe("The workflow decision counts what the export gate accepts", () => {
  it("the old private rule really did overcount — this is the defect being pinned", () => {
    const privateRule = ROWS.filter(
      (d) => d.generationStatus === "GENERATED"
        && (d.validationStatus === "PASSED" || d.validationStatus === "VALIDATED"),
    );
    const canonical = filterFinalExportCandidateDocuments(ROWS as never);
    assert.equal(canonical.length, 1, "only the real technical proposal is a current export candidate");
    assert.ok(
      privateRule.length > canonical.length,
      "the private generationStatus-only rule must be demonstrably looser than the gate",
    );
  });

  it("every row the gate refuses is refused for a stated reason", () => {
    const kept = (filterFinalExportCandidateDocuments(ROWS as never) as Array<{ id: string }>).map((d) => d.id);
    assert.deepEqual(kept, ["real"]);
  });

  it("canonical-workflow-decision.ts no longer defines its own current-document rule", () => {
    const src = read("lib/engine/canonical-workflow-decision.ts");
    assert.ok(
      src.includes("filterFinalExportCandidateDocuments(generatedDocRows)"),
      "the workflow decision must select through the canonical filter",
    );
    // The bare private rule must be gone from the counting logic. It may still
    // appear inside the comment that explains what was wrong with it, so match
    // the executable form.
    assert.ok(
      !/\.filter\(\s*\n?\s*\(d\) =>\s*\n?\s*d\.generationStatus === "GENERATED"/.test(src),
      "the private generationStatus-only filter must not drive any count",
    );
  });

  it("it selects the fields the canonical predicate needs", () => {
    const src = read("lib/engine/canonical-workflow-decision.ts");
    // Without format/documentType a CONTROL or SUBMISSION_CONTROL row is
    // invisible to the predicate and silently counts as a current output.
    for (const field of ["format: true", "documentType: true", "name: true"]) {
      assert.ok(src.includes(field), `the query must select ${field} for the canonical predicate`);
    }
  });

  it("validation and export-ready both read the canonical validation helper", () => {
    const src = read("lib/engine/canonical-workflow-decision.ts");
    assert.ok(src.includes("isValidationPassed(d.validationStatus)"),
      "validated/export-ready must use the shared validation predicate, not an inline status list");
    assert.ok(
      !/validationStatus === "PASSED" \|\| d\.validationStatus === "VALIDATED"/.test(src),
      "the inline PASSED/VALIDATED list must be gone",
    );
  });
});

describe("The ZIP builders already compose the canonical filter", () => {
  // These are the paths that actually assemble the final package. They must
  // narrow canonically AND require real generated bytes.
  for (const path of [
    "app/api/tenders/[id]/export/route.ts",
    "app/api/tenders/[id]/download/route.ts",
  ]) {
    it(`${path} narrows with filterFinalExportCandidateDocuments`, () => {
      const src = read(path);
      assert.ok(src.includes("filterFinalExportCandidateDocuments"),
        "the package builder must use the canonical selection");
    });
  }
});
