// Centralised exportable-text sanitiser (Gap 8).
//
// Strips AI provider names, internal tooling references, and other traces
// that must never appear in client-facing proposal text. Called by
// humanize.ts after the legacy AI_PATTERNS pass.
//
// The `preserveTenderQuotes` option (default false) prevents the replacer
// from touching text inside double-quoted spans — tender clauses are often
// reproduced verbatim and may legitimately contain these words.

type SanitizeOptions = {
  preserveTenderQuotes?: boolean;
};

// AI provider / tool names that must not leak into exported proposals.
const PROVIDER_PATTERNS: RegExp[] = [
  /\bAnthropic\b/g,
  /\bClaude\s+(AI|Opus|Sonnet|Haiku|claude-[\w.-]+)?\b/gi,
  /\bClaude\b/gi,
  /\bOpenAI\b/gi,
  /\bChatGPT\b/gi,
  /\bGPT-[34][\w.-]*/gi,
  /\bGemini\s*(Pro|Ultra|Flash|[\d.]+)?\b/gi,
  /\bGemini\b/gi,
  /\bGoogle\s+AI\b/gi,
  /\bco-?pilot\b/gi,
  /\bLLM\b/g,
  /\blarge\s+language\s+model\b/gi,
];

// AI-phrasing markers and engine-internal annotations that must be scrubbed
// from any text that ships in an exportable document.
const AI_PHRASING_PATTERNS: RegExp[] = [
  /\bas an ai\b/gi,
  /\blanguage model\b/gi,
  /\bgenerated by\b/gi,
  /\bdeterministic fallback\b/gi,
  /\bsubmission note:/gi,
  /\bprompt:\s*/gi,
];

// Placeholder tokens — TODO / TBD / FIXME / PLACEHOLDER (standalone).
// We match only standalone uppercase / titlecase variants so normal mixed-
// case prose (e.g. "the todo list") is unaffected.
const PLACEHOLDER_PATTERNS: RegExp[] = [
  /\bTODO\b/g,
  /\bFIXME\b/g,
  /\bPLACEHOLDER\b/g,
  /\bTBD\b/g,
];

// Internal markers that must not survive into exported documents.
const INTERNAL_MARKERS: RegExp[] = [
  /\bINTERNAL[\s:]+[^\n]*/gi,
  /\bINTERNAL_REVIEW_ONLY\b/gi,
  /\b\[INTERNAL[^\]]*\]/gi,
  /\bDO NOT EXPORT\b/gi,
];

// Em-dash normalization (was previously inlined in humanize.ts).
function normalizeEmDashes(text: string): string {
  return text.replace(/\s*—\s*/g, " — ");
}

function applyPatterns(text: string, patterns: RegExp[]): string {
  let out = text;
  for (const pattern of patterns) {
    out = out.replace(pattern, "");
  }
  return out;
}

function sanitizeSegment(segment: string): string {
  let out = applyPatterns(segment, PROVIDER_PATTERNS);
  out = applyPatterns(out, AI_PHRASING_PATTERNS);
  out = applyPatterns(out, PLACEHOLDER_PATTERNS);
  out = applyPatterns(out, INTERNAL_MARKERS);
  out = normalizeEmDashes(out);
  // Tidy spaces and trailing whitespace introduced by removals.
  out = out.replace(/[ \t]{2,}/g, " ");
  out = out.replace(/[ \t]+$/gm, "");
  return out;
}

export function sanitizeClientFacingText(text: string, options: SanitizeOptions = {}): string {
  if (!text) return text;
  const { preserveTenderQuotes = false } = options;

  if (!preserveTenderQuotes) {
    return sanitizeSegment(text);
  }

  // When preserveTenderQuotes is true, split into quoted/unquoted spans and
  // only sanitise the unquoted spans. Both straight quotes and smart quotes
  // are recognised; spans must contain at least 3 chars to avoid eating
  // apostrophes inside contractions ("don't").
  const segments = text.split(/(["“”][^"“”\n]{3,2000}["“”])/g);
  const processed = segments.map((seg, i) => {
    // Even indices are unquoted; odd indices are captured quoted spans.
    if (i % 2 === 1) return seg;
    return sanitizeSegment(seg);
  });
  return processed.join("");
}

/**
 * Audits a piece of exportable text for any banned traces. Returns a list
 * of unique substrings that should NOT have made it through. Useful as a
 * defensive assertion before persisting a generated document.
 */
export function findClientFacingViolations(input: string): string[] {
  if (!input) return [];
  const cleaned = sanitizeClientFacingText(input);
  if (cleaned === input) return [];
  const violations: string[] = [];
  const allPatterns: Array<{ patterns: RegExp[]; label: string }> = [
    { patterns: PROVIDER_PATTERNS, label: "vendor identifier" },
    { patterns: AI_PHRASING_PATTERNS, label: "AI-phrasing marker" },
    { patterns: PLACEHOLDER_PATTERNS, label: "placeholder token" },
    { patterns: INTERNAL_MARKERS, label: "internal marker" },
  ];
  for (const { patterns, label } of allPatterns) {
    for (const pattern of patterns) {
      const clone = new RegExp(pattern.source, pattern.flags);
      const m = clone.exec(input);
      if (m) violations.push(`${label}: ${m[0]}`);
    }
  }
  return violations;
}
