import { prisma, prismaReady } from "../prisma";
import { getStorageAdapter } from "../storage";
import { isValidClientName } from "./metadata-validators";
import {
  deriveDocumentOutputState,
  exportBlockReason,
  EXPORT_BLOCKING_STATES,
  isGenerated,
  isReviewReadyForExport,
  isValidationPassed,
  type DocumentOutputState,
} from "./document-output-state";
import { containsPricingLeakage } from "./pricing-hygiene";
import { checkExportFileByteReadiness } from "./export-byte-readiness";
import { detectSubmissionPackageMode } from "./submission-package-mode";

export type ExportReadyDocument = {
  id: string;
  name: string;
  exactFileName: string | null;
  exactOrder?: number | null;
  documentType?: string | null;
  format?: string | null;
  generationStatus: string;
  validationStatus: string;
  reviewStatus: string;
  fileContent?: string | null;
  storagePath?: string | null;
};

export type ExportReadinessFailure = {
  documentId: string;
  name: string;
  fileName: string;
  reasons: string[];
};

export type ExportReadinessResult = {
  ok: boolean;
  failures: ExportReadinessFailure[];
  tenderLevelBlockers?: Array<{ category: string; severity: string; title: string; recommendedAction?: string | null }>;
  advisoryWarnings?: Array<{ category: string; severity: string; title: string; recommendedAction?: string | null }>;
};

function generatedFileName(name: string): string {
  return `${name.replace(/[^a-zA-Z0-9]/g, "-")}.docx`;
}

function normalizeFileName(value: string | null | undefined): string {
  return (value ?? "").trim().replace(/\s+/g, " ").toLowerCase();
}

function looksLikeRequiredOutputFile(value: string): boolean {
  const clean = value.trim();
  if (clean.length < 4 || clean.length > 180) return false;
  return /\.(docx?|pdf|xlsx?|zip)$/i.test(clean) || /\b(technical|financial|proposal|annex|form|bid|quotation|eoi|rfp|rfq|declaration|rate card|cv|cover letter)\b/i.test(clean);
}

function parseRequiredFileList(value: string | null | undefined): string[] {
  if (!value) return [];
  let raw: string[] = [];
  try {
    const parsed = JSON.parse(value);
    if (Array.isArray(parsed)) raw = parsed.map(String);
  } catch {
    raw = value.split(/\n|,/).map((item) => item.trim());
  }
  return Array.from(new Set(raw.map((item) => item.trim()).filter(Boolean).filter(looksLikeRequiredOutputFile)));
}

function documentFileName(doc: ExportReadyDocument): string {
  return doc.exactFileName ?? generatedFileName(doc.name);
}

function looksLikePlainText(value: string): boolean {
  if (!value || value.length > 1_000_000) return false;
  const sample = value.slice(0, 2000);
  const nonPrintable = sample.replace(/[\t\n\r\x20-\x7E]/g, "").length;
  const printableRatio = 1 - (nonPrintable / Math.max(sample.length, 1));
  const alphaCount = (sample.match(/[a-zA-Z]/g) ?? []).length;
  return printableRatio > 0.92 && alphaCount >= 20;
}

function visibleXmlText(xml: string): string {
  return xml
    .replace(/<w:tab\/>/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function maybeBase64Docx(value: string | null | undefined, filename: string): boolean {
  if (!value || !filename.toLowerCase().endsWith(".docx")) return false;
  try {
    const buffer = Buffer.from(value, "base64");
    return buffer.length > 4 && buffer[0] === 0x50 && buffer[1] === 0x4b;
  } catch {
    return false;
  }
}

export async function extractDocxVisibleText(value: string | null | undefined, filename: string): Promise<string | null> {
  if (!maybeBase64Docx(value, filename) || !value) return null;
  try {
    const buffer = Buffer.from(value, "base64");
    const JSZip = (await import("jszip")).default;
    const zip = await JSZip.loadAsync(buffer);
    const documentXml = await zip.file("word/document.xml")?.async("string");
    return documentXml ? visibleXmlText(documentXml) : null;
  } catch {
    return null;
  }
}

export function documentHygieneIssues(text: string | null | undefined, doc?: Pick<ExportReadyDocument, "name" | "exactFileName" | "documentType" | "format">): string[] {
  if (!text || !looksLikePlainText(text)) return [];
  const issues: string[] = [];
  if (/\b(as an ai|ai language model|chatgpt|claude|gemini|prompt|generated by ai|deterministic fallback|bid-team action|submission note:)\b/i.test(text)) {
    issues.push("AI/meta-preparation trace text is present");
  }
  if (/\[(insert|add|fill|placeholder|todo|tbd|name of|date here|signature here|stamp here)[^\]]*\]/i.test(text) || /\b(TODO|TBD|FIXME|PLACEHOLDER)\b/i.test(text)) {
    issues.push("Placeholder or unresolved drafting instruction is present");
  }
  if (containsPricingLeakage(text, doc)) {
    issues.push("Possible financial/pricing language appears in a technical document");
  }
  return issues;
}

export function isReadyForFinalExport(doc: ExportReadyDocument): boolean {
  return isGenerated(doc.generationStatus) && isValidationPassed(doc.validationStatus) && isReviewReadyForExport(doc.reviewStatus) && deriveDocumentOutputState(doc) === "READY_FOR_EXPORT";
}

export function checkExportReadiness(docs: ExportReadyDocument[], opts: { requireFileContent?: boolean } = {}): ExportReadinessResult {
  const failures: ExportReadinessFailure[] = [];

  if (docs.length === 0) {
    failures.push({
      documentId: "__tender__",
      name: "No active generated documents",
      fileName: "NO_ACTIVE_GENERATED_DOCUMENTS",
      reasons: ["NO_ACTIVE_GENERATED_DOCUMENTS: final export requires at least one active generated document."],
    });
    return { ok: false, failures };
  }

  for (const doc of docs) {
    const reasons: string[] = [];
    const state = deriveDocumentOutputState(doc);
    if ((EXPORT_BLOCKING_STATES as readonly DocumentOutputState[]).includes(state)) {
      const blockReason = exportBlockReason(state);
      if (blockReason) reasons.push(`[${state}] ${blockReason}`);
    } else if (state !== "READY_FOR_EXPORT") {
      if (!isGenerated(doc.generationStatus)) reasons.push(`generationStatus is ${doc.generationStatus}, expected GENERATED`);
      if (!isValidationPassed(doc.validationStatus)) reasons.push(`validationStatus is ${doc.validationStatus}, expected PASSED or VALIDATED`);
      if (!isReviewReadyForExport(doc.reviewStatus)) reasons.push(`reviewStatus is ${doc.reviewStatus}, expected READY_FOR_EXPORT`);
    }
    if (/MARKDOWN|QUICK_DRAFT|DRAFT_ONLY|CONTROL|NOT_EXPORTABLE|REPLACE_WITH_ORIGINAL|PLANNED/i.test(`${doc.format ?? ""} ${doc.documentType ?? ""}`)) {
      reasons.push(`Document format/status (${doc.format ?? "UNKNOWN"}/${doc.documentType ?? "UNKNOWN"}) is not a final export package file.`);
    }
    if (opts.requireFileContent && !doc.fileContent && !doc.storagePath) reasons.push("fileContent is missing");
    for (const issue of documentHygieneIssues(doc.fileContent, doc)) reasons.push(issue);

    if (reasons.length > 0) failures.push({ documentId: doc.id, name: doc.name, fileName: documentFileName(doc), reasons });
  }

  return { ok: failures.length === 0, failures };
}

export async function checkDocxHygieneReadiness(docs: ExportReadyDocument[]): Promise<ExportReadinessFailure[]> {
  const failures: ExportReadinessFailure[] = [];
  const storage = getStorageAdapter();
  for (const doc of docs) {
    const fileName = documentFileName(doc);
    let content = doc.fileContent ?? null;
    if (!content && doc.storagePath) {
      try {
        const bytes = await storage.getFile({ storagePath: doc.storagePath, fileContent: doc.fileContent ?? null, fileName });
        content = bytes.toString("base64");
      } catch {
        failures.push({ documentId: doc.id, name: doc.name, fileName, reasons: ["Unable to inspect storage-backed document content for final export hygiene"] });
        continue;
      }
    }
    const text = await extractDocxVisibleText(content, fileName);
    const reasons = documentHygieneIssues(text, doc).map((issue) => `${issue} inside DOCX visible text`);
    if (reasons.length > 0) failures.push({ documentId: doc.id, name: doc.name, fileName, reasons });
  }
  return failures;
}

function mergeFailures(...groups: ExportReadinessFailure[][]): ExportReadinessFailure[] {
  const byDocument = new Map<string, ExportReadinessFailure>();
  for (const group of groups) {
    for (const failure of group) {
      const existing = byDocument.get(failure.documentId);
      if (!existing) {
        byDocument.set(failure.documentId, { ...failure, reasons: [...failure.reasons] });
        continue;
      }
      existing.reasons = Array.from(new Set([...existing.reasons, ...failure.reasons]));
    }
  }
  return Array.from(byDocument.values());
}

export function exportReadinessError(failures: ExportReadinessFailure[], tenderLevelBlockers?: ExportReadinessResult["tenderLevelBlockers"]): string {
  const out: string[] = [];
  if (failures.length > 0) {
    const summary = failures.length === 1 ? "Final export blocked: 1 document is not ready for export." : `Final export blocked: ${failures.length} documents are not ready for export.`;
    const details = failures.slice(0, 6).map((f) => `• ${f.fileName} — ${f.reasons.join("; ")}`).join("\n");
    const truncationNote = failures.length > 6 ? `\n• … and ${failures.length - 6} more` : "";
    out.push(`${summary}\n${details}${truncationNote}`);
  }
  if (tenderLevelBlockers && tenderLevelBlockers.length > 0) {
    const lines = tenderLevelBlockers.slice(0, 8).map((b) => {
      const action = b.recommendedAction ? ` — Action: ${b.recommendedAction}` : "";
      return `• [${b.severity}] ${b.title}${action}`;
    });
    out.push(`Tender-level blockers (${tenderLevelBlockers.length} unresolved):\n${lines.join("\n")}`);
  }
  return out.length === 0 ? "" : out.join("\n\n");
}

export function filePlanBlockersFromLists(docs: ExportReadyDocument[], exactFileNaming: string | null | undefined, exactFileOrder: string | null | undefined): NonNullable<ExportReadinessResult["tenderLevelBlockers"]> {
  const blockers: NonNullable<ExportReadinessResult["tenderLevelBlockers"]> = [];
  const requiredNames = parseRequiredFileList(exactFileNaming);
  const requiredOrder = parseRequiredFileList(exactFileOrder);
  const actualNames = docs.map((doc) => documentFileName(doc)).filter(Boolean);
  const actualNameSet = new Set(actualNames.map(normalizeFileName));

  const missingNames = requiredNames.filter((name) => !actualNameSet.has(normalizeFileName(name)));
  if (missingNames.length > 0) blockers.push({ category: "FILE_NAMING", severity: "HIGH", title: `Missing required generated file name(s): ${missingNames.slice(0, 5).join(", ")}${missingNames.length > 5 ? ` and ${missingNames.length - 5} more` : ""}`, recommendedAction: "Generate or rename documents to match the tender's exact required file names before final export." });
  const extraFiles = actualNames.filter((name) => requiredNames.length > 0 && !requiredNames.some((required) => normalizeFileName(required) === normalizeFileName(name)));
  if (extraFiles.length > 0) blockers.push({ category: "EXTRA_FILES", severity: "HIGH", title: `Generated package contains non-required file(s): ${extraFiles.slice(0, 5).join(", ")}${extraFiles.length > 5 ? ` and ${extraFiles.length - 5} more` : ""}`, recommendedAction: "Remove extra generated files not listed in the tender's exact file naming instructions before final export." });

  if (requiredOrder.length > 0) {
    const orderedActual = [...docs].sort((a, b) => (a.exactOrder ?? 9999) - (b.exactOrder ?? 9999)).map((doc) => normalizeFileName(documentFileName(doc)));
    const mismatches = requiredOrder.map((name, index) => ({ name, expected: normalizeFileName(name), actual: orderedActual[index] ?? "" })).filter((row) => row.actual && row.expected !== row.actual);
    if (mismatches.length > 0) blockers.push({ category: "FILE_ORDER", severity: "HIGH", title: `Generated file order does not match tender order near: ${mismatches.slice(0, 3).map((m) => m.name).join(", ")}`, recommendedAction: "Reorder the generated documents/export package to match the tender's required attachment order." });
  }

  return blockers;
}

function tenderBlocker(category: string, title: string, recommendedAction: string, severity: "HIGH" | "MEDIUM" | "LOW" = "HIGH") {
  return { category, severity, title, recommendedAction };
}

function hasStrategyOnlySignals(files: Array<{ originalFileName: string; extractedText?: string | null; classification?: string | null }>): boolean {
  if (files.length === 0) return false;
  const combined = files.map((f) => `${f.originalFileName}\n${f.classification ?? ""}\n${f.extractedText ?? ""}`).join("\n\n").toLowerCase();
  const strategyHits = /(compiled from|all information should be verified|master file|market intelligence|consultant interpretation|data current as of|directenders|2merkato|reporter newspaper|ethiopian herald)/i.test(combined);
  const officialHits = /(request for proposal|\brfp\b|terms of reference|instructions to bidders|bid data sheet|form of tender|addendum|procuring entity|official tender)/i.test(combined);
  return strategyHits && !officialHits;
}

export function donorSafeguardsExplicitlyRequired(sourceText: string): boolean {
  return /(?:tor|terms?\s+of\s+reference|mandatory|required|must|shall).{0,80}(?:esmp|logframe|results?\s+framework|m&e|monitoring.*evaluation|environmental|social.*safeguard)|deliverable.{0,40}(?:esmp|logframe|m&e|results?\s+framework)/i.test(sourceText);
}

export async function checkTenderLevelExportBlockers(tenderId: string, docs: ExportReadyDocument[] = []): Promise<{ blockers: NonNullable<ExportReadinessResult["tenderLevelBlockers"]>; advisoryWarnings: NonNullable<ExportReadinessResult["advisoryWarnings"]> }> {
  await prismaReady;
  const blockers: NonNullable<ExportReadinessResult["tenderLevelBlockers"]> = [];
  const advisoryWarnings: NonNullable<ExportReadinessResult["advisoryWarnings"]> = [];

  const tender = await prisma.tender.findUnique({
    where: { id: tenderId },
    include: {
      files: { select: { originalFileName: true, extractedText: true, classification: true } },
      requirements: true,
      expertMatches: { where: { isSelected: true }, include: { expert: { select: { trustLevel: true } } } },
      projectMatches: { where: { isSelected: true }, include: { project: { select: { trustLevel: true } } } },
    },
  });

  if (!tender) return { blockers: [tenderBlocker("TENDER_NOT_FOUND", "Tender not found for export readiness check.", "Reload the tender and run export readiness again.")], advisoryWarnings };

  const packageMode = detectSubmissionPackageMode({
    submissionMethod: tender.submissionMethod,
    submissionAddress: tender.submissionAddress,
    submissionEmails: tender.submissionEmails,
    exactFileNaming: tender.exactFileNaming,
    exactFileOrder: tender.exactFileOrder,
    analysisSummary: tender.analysisSummary,
    evaluationMethodology: tender.evaluationMethodology,
    notes: tender.notes,
    requirements: tender.requirements,
    files: tender.files,
  });
  if (packageMode.blockingForZip) {
    blockers.push(tenderBlocker(
      `PACKAGE_MODE_${packageMode.mode}`,
      `${packageMode.reason} Signal: ${packageMode.matchedSignals[0] ?? packageMode.mode}`,
      "Do not use the default final ZIP until the required submission package mode is implemented or manually prepared exactly as the tender instructs.",
      "HIGH",
    ));
  }

  if (docs.length === 0) blockers.push(tenderBlocker("NO_ACTIVE_GENERATED_DOCUMENTS", "No active generated documents exist for export.", "Generate, validate and review the required documents before final export."));
  if (!isValidClientName(tender.clientName)) blockers.push(tenderBlocker("CLIENT_NAME_REQUIRED", "Client/procuring entity name is missing or invalid.", "Edit Tender Detail and enter the exact official procuring entity name."));
  if ((tender.readinessScore ?? 0) <= 0 || /^(ANALYZED|DRAFT)$/i.test(tender.status) || /^(ANALYSIS|TENDER_INTAKE)$/i.test(tender.stage)) blockers.push(tenderBlocker("FULL_PROPOSAL_NOT_READY", `Tender is still at ${tender.status}/${tender.stage} with readiness score ${tender.readinessScore ?? 0}.`, "Run Engine, resolve readiness blockers, generate documents, then rerun export readiness."));
  if (hasStrategyOnlySignals(tender.files)) blockers.push(tenderBlocker("OFFICIAL_SOURCE_REQUIRED", "Uploaded source appears to be strategy/market-intelligence only, not an official RFP/ToR/forms package.", "Upload the official tender source package before final export."));

  const requiresExperts = tender.requirements.some((r) => r.requirementType === "EXPERT");
  const requiresProjects = tender.requirements.some((r) => r.requirementType === "PROJECT_EXPERIENCE");
  const reviewedSelectedExperts = tender.expertMatches.filter((m) => m.expert.trustLevel === "REVIEWED").length;
  const reviewedSelectedProjects = tender.projectMatches.filter((m) => m.project.trustLevel === "REVIEWED").length;
  if (requiresExperts && reviewedSelectedExperts === 0) blockers.push(tenderBlocker("NO_SELECTED_REVIEWED_EXPERTS", "Tender requires experts but no selected reviewed expert matches exist.", "Run Engine and select/review expert matches before export."));
  if (requiresProjects && reviewedSelectedProjects === 0) blockers.push(tenderBlocker("NO_SELECTED_REVIEWED_PROJECTS", "Tender requires project references but no selected reviewed project matches exist.", "Run Engine and select/review project matches before export."));

  const [complianceRows, totalExpertMatches, totalProjectMatches, plannedDocCount] = await Promise.all([
    prisma.complianceMatrix.count({ where: { tenderId } }),
    prisma.tenderExpertMatch.count({ where: { tenderId } }),
    prisma.tenderProjectMatch.count({ where: { tenderId } }),
    prisma.generatedDocument.count({ where: { tenderId, generationStatus: "PLANNED" } }),
  ]);
  if (tender.requirements.length > 0 && complianceRows === 0) blockers.push(tenderBlocker("EVIDENCE_NOT_ASSESSED", "Compliance/evidence matrix is empty.", "Run Engine successfully so requirement-linked evidence rows are created."));
  if (requiresExperts && totalExpertMatches === 0) blockers.push(tenderBlocker("NO_TENDER_SPECIFIC_EXPERT_MATCHES", "No tender-specific expert match rows exist.", "Run Engine to create expert matches from the reviewed vault."));
  if (requiresProjects && totalProjectMatches === 0) blockers.push(tenderBlocker("NO_TENDER_SPECIFIC_PROJECT_MATCHES", "No tender-specific project match rows exist.", "Run Engine to create project matches from the reviewed vault."));
  if (plannedDocCount > 0) blockers.push(tenderBlocker("UNGENERATED_PLANNED_DOCUMENTS", `${plannedDocCount} required submission document(s) are planned but not yet generated — the ZIP package would be incomplete.`, "Click 'Generate missing planned documents' to convert PLANNED rows into draft documents. For official-original rows (bid forms, tender templates) you must upload the real file via 'Attach official original'.", "HIGH"));

  const ungroundedMandatory = tender.requirements.filter((req) => req.priority === "MANDATORY" && !req.sectionReference && !req.sourceTenderFileId && !req.sourcePageNumber && !req.sourceExactQuote && (req.sourceConfidence ?? 0) <= 0);
  if (ungroundedMandatory.length > 0) blockers.push(tenderBlocker("SOURCE_REFERENCES_MISSING", `${ungroundedMandatory.length} mandatory requirement(s) lack source/page/quote traceability.`, "Run source extraction and review mandatory requirement references before export.", "HIGH"));

  blockers.push(...filePlanBlockersFromLists(docs, tender.exactFileNaming, tender.exactFileOrder));

  const highOpen = await prisma.evaluatorObjection.findMany({ where: { tenderId, status: "OPEN", severity: "HIGH" }, select: { id: true, title: true, severity: true, category: true, recommendedAction: true }, take: 20 });
  for (const o of highOpen) blockers.push({ category: `EVALUATOR_${o.category}`, severity: o.severity, title: o.title, recommendedAction: o.recommendedAction });

  const workbook = await prisma.pricingWorkbook.findUnique({ where: { tenderId }, select: { id: true, noPriceLeakage: true } });
  if (workbook && workbook.noPriceLeakage === false) blockers.push(tenderBlocker("PRICING_LEAKAGE", "Pricing leakage flag is set on the pricing workbook.", "Confirm no prices, rates, or fees appear in the technical proposal envelope."));

  // ── Donor / NGO safeguard checklist ──────────────────────────────────────
  // When the tender is NGO/donor-funded (detected by category or keyword
  // signals in description/analysis), verify that the three mandatory donor
  // safeguard artefacts are present in the submission plan requirements or
  // generated documents. Missing items are surfaced as MEDIUM blockers so the
  // user is reminded before final export — they do not hard-block, since some
  // donors accept a separate ESMP/logframe delivery milestone.
  const isDonorTender =
    /ngo|donor.?funded|world\s+bank|afdb|african\s+development|eu\s+funded|usaid|dfid|fcdo|giz|undp|unicef|wfp|unhcr|ifad|gfatm|global\s+fund/i.test(
      [tender.category, tender.description, tender.analysisSummary, tender.notes, tender.intakeSummary].filter(Boolean).join(" "),
    );
  if (isDonorTender) {
    const planText = tender.requirements.map((r) => `${r.title} ${r.description ?? ""}`).join(" ").toLowerCase();
    const docText = docs.map((d) => `${d.name} ${d.documentType ?? ""}`).join(" ").toLowerCase();
    const allText = `${planText} ${docText}`;
    const sourceText = [tender.description, tender.analysisSummary, tender.notes, tender.intakeSummary, ...tender.requirements.map((r) => `${r.title} ${r.description ?? ""}`)].filter(Boolean).join(" ").toLowerCase();
    const explicitlyRequired = donorSafeguardsExplicitlyRequired(sourceText);
    const addDonorIssue = (code: string, title: string, action: string) => {
      const issue = tenderBlocker(code, title, action, "MEDIUM");
      if (explicitlyRequired) blockers.push(issue);
      else advisoryWarnings.push(issue);
    };

    if (!/esmp|environmental.*social.*management|esia|safeguard.*plan|environmental.*management.*plan/i.test(allText)) {
      addDonorIssue(
        "DONOR_ESMP_MISSING",
        "NGO/donor tender: Environmental and Social Management Plan (ESMP) not detected in submission plan or generated documents.",
        "Add ESMP section/annex, or mark as not required by ToR / separate post-award deliverable / donor template provided.",
      );
    }
    if (!/logframe|log\s+frame|logical\s+framework|result[s]?\s+framework/i.test(allText)) {
      addDonorIssue(
        "DONOR_LOGFRAME_MISSING",
        "NGO/donor tender: Logical Framework (logframe / results framework) not detected in submission plan or generated documents.",
        "Add logframe/results framework, or mark as not required by ToR / separate post-award deliverable / donor template provided.",
      );
    }
    if (!/m&e\s+plan|monitoring.*evaluation|me\s+plan|m\s+and\s+e\s+plan|monitoring\s+plan/i.test(allText)) {
      addDonorIssue(
        "DONOR_ME_PLAN_MISSING",
        "NGO/donor tender: Monitoring & Evaluation (M&E) plan not detected in submission plan or generated documents.",
        "Add M&E plan, or mark as not required by ToR / separate post-award deliverable / donor template provided.",
      );
    }
  }

  return { blockers, advisoryWarnings };
}

export async function checkFullExportReadiness(opts: { tenderId: string; docs: ExportReadyDocument[]; requireFileContent?: boolean }): Promise<ExportReadinessResult> {
  const perDoc = checkExportReadiness(opts.docs, { requireFileContent: opts.requireFileContent });
  const docxHygieneFailures = await checkDocxHygieneReadiness(opts.docs);
  const byteFailures = await checkExportFileByteReadiness(opts.docs);
  const failures = mergeFailures(perDoc.failures, docxHygieneFailures, byteFailures);
  const tenderReadiness = await checkTenderLevelExportBlockers(opts.tenderId, opts.docs);
  return { ok: failures.length === 0 && tenderReadiness.blockers.length === 0, failures, tenderLevelBlockers: tenderReadiness.blockers, advisoryWarnings: tenderReadiness.advisoryWarnings };
}
