import { prisma, prismaReady } from "../prisma";
import { deriveDocumentOutputState, exportBlockReason, EXPORT_BLOCKING_STATES, type DocumentOutputState } from "./document-output-state";

export type ExportReadyDocument = {
  id: string;
  name: string;
  exactFileName: string | null;
  exactOrder?: number | null;
  generationStatus: string;
  validationStatus: string;
  reviewStatus: string;
  fileContent?: string | null;
};

export type ExportReadinessFailure = {
  documentId: string;
  name: string;
  fileName: string;
  reasons: string[];
};

export type ExportReadinessResult = {
  ok: boolean;
  failures: ExportReadinessFailure[];
  tenderLevelBlockers?: Array<{ category: string; severity: string; title: string; recommendedAction?: string | null }>;
};

function generatedFileName(name: string): string {
  return `${name.replace(/[^a-zA-Z0-9]/g, "-")}.docx`;
}

function normalizeFileName(value: string | null | undefined): string {
  return (value ?? "").trim().replace(/\s+/g, " ").toLowerCase();
}

function looksLikeRequiredOutputFile(value: string): boolean {
  const clean = value.trim();
  if (clean.length < 4 || clean.length > 180) return false;
  return /\.(docx?|pdf|xlsx?|zip)$/i.test(clean) || /\b(technical|financial|proposal|annex|form|bid|quotation|eoi|rfp|rfq|declaration|rate card|cv|cover letter)\b/i.test(clean);
}

function parseRequiredFileList(value: string | null | undefined): string[] {
  if (!value) return [];
  let raw: string[] = [];
  try {
    const parsed = JSON.parse(value);
    if (Array.isArray(parsed)) raw = parsed.map(String);
  } catch {
    raw = value.split(/\n|,/).map((item) => item.trim());
  }
  return Array.from(new Set(raw.map((item) => item.trim()).filter(Boolean).filter(looksLikeRequiredOutputFile)));
}

function documentFileName(doc: ExportReadyDocument): string {
  return doc.exactFileName ?? generatedFileName(doc.name);
}

function looksLikePlainText(value: string): boolean {
  if (!value || value.length > 1_000_000) return false;
  const sample = value.slice(0, 2000);
  const nonPrintable = sample.replace(/[\t\n\r\x20-\x7E]/g, "").length;
  const printableRatio = 1 - (nonPrintable / Math.max(sample.length, 1));
  const alphaCount = (sample.match(/[a-zA-Z]/g) ?? []).length;
  return printableRatio > 0.92 && alphaCount >= 20;
}

function visibleXmlText(xml: string): string {
  return xml
    .replace(/<w:tab\/>/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function maybeBase64Docx(value: string | null | undefined, filename: string): boolean {
  if (!value || !filename.toLowerCase().endsWith(".docx")) return false;
  try {
    const buffer = Buffer.from(value, "base64");
    return buffer.length > 4 && buffer[0] === 0x50 && buffer[1] === 0x4b;
  } catch {
    return false;
  }
}

async function extractDocxVisibleText(value: string | null | undefined, filename: string): Promise<string | null> {
  if (!maybeBase64Docx(value, filename) || !value) return null;
  try {
    const buffer = Buffer.from(value, "base64");
    const JSZip = (await import("jszip")).default;
    const zip = await JSZip.loadAsync(buffer);
    const documentXml = await zip.file("word/document.xml")?.async("string");
    return documentXml ? visibleXmlText(documentXml) : null;
  } catch {
    return null;
  }
}

function documentHygieneIssues(text: string | null | undefined): string[] {
  if (!text || !looksLikePlainText(text)) return [];
  const issues: string[] = [];
  if (/\b(as an ai|ai language model|chatgpt|claude|gemini|prompt|generated by ai|deterministic fallback|bid-team action|submission note:)\b/i.test(text)) {
    issues.push("AI/meta-preparation trace text is present");
  }
  if (/\[(insert|add|fill|placeholder|todo|tbd|name of|date here|signature here|stamp here)[^\]]*\]/i.test(text) || /\b(TODO|TBD|FIXME|PLACEHOLDER)\b/i.test(text)) {
    issues.push("Placeholder or unresolved drafting instruction is present");
  }
  if (/\b(?:EUR|USD|ETB|GBP|Birr|fee|rate|unit price|total price|financial proposal|price schedule)\b/i.test(text) && /\btechnical\b/i.test(text)) {
    issues.push("Possible financial/pricing language appears in a technical document");
  }
  return issues;
}

export function isReadyForFinalExport(doc: ExportReadyDocument): boolean {
  return doc.generationStatus === "GENERATED" && doc.validationStatus === "VALIDATED" && doc.reviewStatus === "READY_FOR_EXPORT";
}

export function checkExportReadiness(docs: ExportReadyDocument[], opts: { requireFileContent?: boolean } = {}): ExportReadinessResult {
  const failures: ExportReadinessFailure[] = [];

  for (const doc of docs) {
    const reasons: string[] = [];

    // ─── Gap 10 fix — derived output state ───────────────────────────
    // The state machine looks at (generationStatus, validationStatus,
    // reviewStatus, format, fileContent) and returns one canonical
    // state. Any export-blocking state (CONTROL_RECORD_ONLY,
    // ORIGINAL_REQUIRED, PDF_CONVERSION_REQUIRED, SUPERSEDED,
    // NEEDS_REVALIDATION) produces an explicit reason — replacing the
    // older "generationStatus is X, expected GENERATED" string lists
    // with actionable language ("Convert from DOCX or attach the actual
    // PDF before export", etc.).
    const state = deriveDocumentOutputState(doc);
    if ((EXPORT_BLOCKING_STATES as readonly DocumentOutputState[]).includes(state)) {
      const blockReason = exportBlockReason(state);
      if (blockReason) reasons.push(`[${state}] ${blockReason}`);
    } else if (state !== "READY_FOR_EXPORT") {
      // VALIDATED / DOCX_GENERATED / PDF_GENERATED — content exists but
      // hasn't passed the review-status check. Surface the legacy
      // column-by-column reasons so reviewers know exactly which sign-off
      // is missing.
      if (doc.generationStatus !== "GENERATED") reasons.push(`generationStatus is ${doc.generationStatus}, expected GENERATED`);
      if (doc.validationStatus !== "VALIDATED") reasons.push(`validationStatus is ${doc.validationStatus}, expected VALIDATED`);
      if (doc.reviewStatus !== "READY_FOR_EXPORT") reasons.push(`reviewStatus is ${doc.reviewStatus}, expected READY_FOR_EXPORT`);
    }
    if (opts.requireFileContent && !doc.fileContent) reasons.push("fileContent is missing");
    for (const issue of documentHygieneIssues(doc.fileContent)) reasons.push(issue);

    if (reasons.length > 0) {
      failures.push({
        documentId: doc.id,
        name: doc.name,
        fileName: documentFileName(doc),
        reasons,
      });
    }
  }

  return { ok: failures.length === 0, failures };
}

export async function checkDocxHygieneReadiness(docs: ExportReadyDocument[]): Promise<ExportReadinessFailure[]> {
  const failures: ExportReadinessFailure[] = [];
  for (const doc of docs) {
    const fileName = documentFileName(doc);
    const text = await extractDocxVisibleText(doc.fileContent, fileName);
    const reasons = documentHygieneIssues(text).map((issue) => `${issue} inside DOCX visible text`);
    if (reasons.length > 0) {
      failures.push({ documentId: doc.id, name: doc.name, fileName, reasons });
    }
  }
  return failures;
}

function mergeFailures(...groups: ExportReadinessFailure[][]): ExportReadinessFailure[] {
  const byDocument = new Map<string, ExportReadinessFailure>();
  for (const group of groups) {
    for (const failure of group) {
      const key = failure.documentId;
      const existing = byDocument.get(key);
      if (!existing) {
        byDocument.set(key, { ...failure, reasons: [...failure.reasons] });
        continue;
      }
      existing.reasons = Array.from(new Set([...existing.reasons, ...failure.reasons]));
    }
  }
  return Array.from(byDocument.values());
}

export function exportReadinessError(failures: ExportReadinessFailure[], tenderLevelBlockers?: ExportReadinessResult["tenderLevelBlockers"]): string {
  const out: string[] = [];
  if (failures.length > 0) {
    const summary = failures.length === 1
      ? "Final export blocked: 1 document is not ready for export."
      : `Final export blocked: ${failures.length} documents are not ready for export.`;
    const details = failures
      .slice(0, 6)
      .map((f) => `• ${f.fileName} — ${f.reasons.join("; ")}`)
      .join("\n");
    const truncationNote = failures.length > 6 ? `\n• … and ${failures.length - 6} more` : "";
    out.push(`${summary}\n${details}${truncationNote}`);
  }
  if (tenderLevelBlockers && tenderLevelBlockers.length > 0) {
    const lines = tenderLevelBlockers.slice(0, 8).map((b) => {
      const action = b.recommendedAction ? ` — Action: ${b.recommendedAction}` : "";
      return `• [${b.severity}] ${b.title}${action}`;
    });
    out.push(`Tender-level blockers (${tenderLevelBlockers.length} unresolved):\n${lines.join("\n")}`);
  }
  return out.length === 0 ? "" : out.join("\n\n");
}

function filePlanBlockersFromLists(docs: ExportReadyDocument[], exactFileNaming: string | null | undefined, exactFileOrder: string | null | undefined): NonNullable<ExportReadinessResult["tenderLevelBlockers"]> {
  const blockers: NonNullable<ExportReadinessResult["tenderLevelBlockers"]> = [];
  const requiredNames = parseRequiredFileList(exactFileNaming);
  const requiredOrder = parseRequiredFileList(exactFileOrder);
  const actualNames = docs.map((doc) => documentFileName(doc)).filter(Boolean);
  const actualNameSet = new Set(actualNames.map(normalizeFileName));

  const missingNames = requiredNames.filter((name) => !actualNameSet.has(normalizeFileName(name)));
  if (missingNames.length > 0) {
    blockers.push({
      category: "FILE_NAMING",
      severity: "HIGH",
      title: `Missing required generated file name(s): ${missingNames.slice(0, 5).join(", ")}${missingNames.length > 5 ? ` and ${missingNames.length - 5} more` : ""}`,
      recommendedAction: "Generate or rename documents to match the tender's exact required file names before final export.",
    });
  }

  if (requiredOrder.length > 0) {
    const orderedActual = [...docs]
      .sort((a, b) => (a.exactOrder ?? 9999) - (b.exactOrder ?? 9999))
      .map((doc) => normalizeFileName(documentFileName(doc)));
    const mismatches = requiredOrder
      .map((name, index) => ({ name, expected: normalizeFileName(name), actual: orderedActual[index] ?? "" }))
      .filter((row) => row.actual && row.expected !== row.actual);
    if (mismatches.length > 0) {
      blockers.push({
        category: "FILE_ORDER",
        severity: "MEDIUM",
        title: `Generated file order does not match tender order near: ${mismatches.slice(0, 3).map((m) => m.name).join(", ")}`,
        recommendedAction: "Reorder the generated documents/export package to match the tender's required attachment order.",
      });
    }
  }

  return blockers;
}

export async function checkTenderLevelExportBlockers(tenderId: string, docs: ExportReadyDocument[] = []): Promise<NonNullable<ExportReadinessResult["tenderLevelBlockers"]>> {
  await prismaReady;
  const blockers: NonNullable<ExportReadinessResult["tenderLevelBlockers"]> = [];

  const highOpen = await prisma.evaluatorObjection.findMany({
    where: { tenderId, status: "OPEN", severity: "HIGH" },
    select: { id: true, title: true, severity: true, category: true, recommendedAction: true },
    take: 20,
  });
  for (const o of highOpen) {
    blockers.push({
      category: `EVALUATOR_${o.category}`,
      severity: o.severity,
      title: o.title,
      recommendedAction: o.recommendedAction,
    });
  }

  const workbook = await prisma.pricingWorkbook.findUnique({
    where: { tenderId },
    select: { id: true, noPriceLeakage: true },
  });
  if (workbook && workbook.noPriceLeakage === false) {
    blockers.push({
      category: "PRICING_LEAKAGE",
      severity: "HIGH",
      title: "Pricing leakage flag is set on the pricing workbook",
      recommendedAction: "Confirm no prices, rates, or fees appear in the technical proposal envelope. Toggle noPriceLeakage=true once verified.",
    });
  }

  const tender = await prisma.tender.findUnique({
    where: { id: tenderId },
    select: { exactFileNaming: true, exactFileOrder: true },
  });
  blockers.push(...filePlanBlockersFromLists(docs, tender?.exactFileNaming, tender?.exactFileOrder));

  return blockers;
}

export async function checkFullExportReadiness(opts: { tenderId: string; docs: ExportReadyDocument[]; requireFileContent?: boolean }): Promise<ExportReadinessResult> {
  const perDoc = checkExportReadiness(opts.docs, { requireFileContent: opts.requireFileContent });
  const docxHygieneFailures = await checkDocxHygieneReadiness(opts.docs);
  const failures = mergeFailures(perDoc.failures, docxHygieneFailures);
  const tenderLevelBlockers = await checkTenderLevelExportBlockers(opts.tenderId, opts.docs);
  return {
    ok: failures.length === 0 && tenderLevelBlockers.length === 0,
    failures,
    tenderLevelBlockers,
  };
}
