import { buildSubmissionPlanWithDerivedFallback, submissionPlanFileKey, type SubmissionPlanFile } from "./submission-plan";
import { isFinalExportCandidateDocument, isExportReady, exportBlockReason } from "./document-output-state";

export type FinalPackageBlocker = { area: "requirements" | "evidence" | "documents" | "export"; code: string; title: string; documentName?: string; generatedDocumentId?: string | null; requirementId?: string | null; reason: string; nextAction: string };
export type RequirementEvidenceStatus = { requirementId: string; title: string; mandatory: boolean; selectedEvidenceCount: number; strongestEvidenceLevel: "FULL" | "SUBSTANTIAL" | "PARTIAL" | "WEAK" | "NONE"; hasTrustedTrace: boolean; hasReviewedExpert: boolean; hasReviewedProject: boolean; blockerReason: string | null };
export type PlannedPackageDocument = { key: string; displayName: string; required: boolean; envelope: "technical" | "financial" | "common"; expectedFormat: "DOCX" | "PDF" | "XLSX" | "CSV" | "ZIP" | "ORIGINAL"; sourceRequirementIds: string[]; generationMode: "generated" | "uploaded_original" | "manual_upload_required" | "not_applicable"; generatedDocumentId: string | null; status: "missing" | "generated" | "valid" | "approved" | "export_ready" | "blocked" | "not_applicable"; blockerReason: string | null };
export type GeneratedPackageDocument = { id: string; key: string | null; name: string; finalFileName: string; documentType: string; format: string; generationStatus: string; validationStatus: string; reviewStatus: string; plannedDocumentKey: string | null; exportReady: boolean; blockerReason: string | null; sizeBytes: number };
export type FinalZipManifest = { tenderId: string; files: Array<{ plannedDocumentKey: string; finalFileName: string; sourceDocumentId: string | null; sourceUploadId: string | null; format: string; sizeBytes: number; envelope: "technical" | "financial" | "common"; required: boolean; approved: boolean; exportReady: boolean; blockerReason: string | null }>; missingRequiredFiles: string[]; extraFilesExcluded: string[]; ready: boolean };
export type FinalPackageReadinessModel = { tenderId: string; requirementEvidenceStatuses: RequirementEvidenceStatus[]; projectMatchSummary: { selectedReviewed: number; highScoreSelected: number; belowThresholdSelected: number; missingComparableCoverage: number; explanation: string | null }; requirements: { total: number; mandatory: number; traced: number; mandatoryTraced: number; strongEvidence: number; weakEvidence: number; missingEvidence: number; coverageRatio: number; blockers: FinalPackageBlocker[] }; evidence: { rows: number; selected: number; strong: number; substantial: number; weak: number; missing: number; expertMatches: number; reviewedExpertMatches: number; projectMatches: number; reviewedProjectMatches: number; blockers: FinalPackageBlocker[] }; documents: { planned: PlannedPackageDocument[]; required: PlannedPackageDocument[]; generated: GeneratedPackageDocument[]; valid: GeneratedPackageDocument[]; approved: GeneratedPackageDocument[]; missingRequired: PlannedPackageDocument[]; extraGeneratedOutsidePlan: GeneratedPackageDocument[]; exportReady: GeneratedPackageDocument[]; blockers: FinalPackageBlocker[] }; export: { ready: boolean; zipReady: boolean; pdfRequired: boolean; pdfConversionAvailable: boolean; requiredPdfMissing: boolean; workspaceCount: number; exportCandidateCount: number; blockers: FinalPackageBlocker[]; manifest: FinalZipManifest }; summary: { status: "draft_ready" | "generation_ready" | "review_required" | "export_blocked" | "export_ready"; score: number; blockerCount: number; nextBestActions: string[] } };

const VALID = new Set(["PASSED", "VALIDATED", "APPROVED", "READY_FOR_EXPORT"]);
const APPROVED = new Set(["APPROVED", "READY_FOR_EXPORT"]);
function norm(v: unknown) { return String(v ?? "").trim().toUpperCase(); }
function bytes(doc: { fileContent?: string | null; storagePath?: string | null }) { return doc.fileContent ? Buffer.byteLength(doc.fileContent) : doc.storagePath ? 1 : 0; }
function envelope(v: string): PlannedPackageDocument["envelope"] { return v === "FINANCIAL" ? "financial" : v === "ADMIN" ? "common" : "technical"; }
function fmt(v?: string | null): PlannedPackageDocument["expectedFormat"] { const f = norm(v); return f === "PDF" || f === "XLSX" || f === "CSV" || f === "ZIP" || f === "ORIGINAL" ? f : "DOCX"; }
function keyForDoc(d: { exactFileName?: string | null; name?: string | null }) { return submissionPlanFileKey(d.exactFileName ?? d.name ?? ""); }
function levelRank(level: RequirementEvidenceStatus["strongestEvidenceLevel"]) { return { NONE: 0, WEAK: 1, PARTIAL: 2, SUBSTANTIAL: 3, FULL: 4 }[level]; }
function mapSupport(v: string | null | undefined): RequirementEvidenceStatus["strongestEvidenceLevel"] { const s = norm(v); if (s === "FULL") return "FULL"; if (s === "SUBSTANTIAL") return "SUBSTANTIAL"; if (s === "PARTIAL") return "PARTIAL"; if (s === "WEAK") return "WEAK"; return "NONE"; }

export function mapRequirementsToEvidence(requirements: any[], expertMatches: any[] = [], projectMatches: any[] = []): RequirementEvidenceStatus[] {
  return requirements.map((req) => {
    const links = req.complianceMatrixRows ?? [];
    const strongest = links.map((l: any) => mapSupport(l.supportLevel)).sort((a: any, b: any) => levelRank(b) - levelRank(a))[0] ?? "NONE";
    const mandatory = ["MANDATORY", "CRITICAL"].includes(norm(req.priority));
    const trusted = Boolean(req.sourceTenderFileId && req.sourcePageNumber && req.sourceExactQuote) && levelRank(strongest) >= levelRank("PARTIAL");
    const hasReviewedExpert = expertMatches.some((m) => m.isSelected && m.expert?.trustLevel === "REVIEWED");
    const hasReviewedProject = projectMatches.some((m) => m.isSelected && m.project?.trustLevel === "REVIEWED");
    const blockerReason = trusted ? null : links.length === 0 ? "No selected or linked evidence is traced to this requirement." : !req.sourceExactQuote ? "Requirement lacks source quote/page trace, so evidence is not trusted." : "Linked evidence is weaker than PARTIAL.";
    return { requirementId: req.id, title: req.title, mandatory, selectedEvidenceCount: links.length, strongestEvidenceLevel: strongest, hasTrustedTrace: trusted, hasReviewedExpert, hasReviewedProject, blockerReason };
  });
}

export function deriveRequiredPackageDocuments(tender: any, generated: any[] = []): PlannedPackageDocument[] {
  const plan = buildSubmissionPlanWithDerivedFallback({ ...tender, requirements: tender.requirements ?? [] });
  return plan.files.map((file: SubmissionPlanFile) => {
    const key = submissionPlanFileKey(file.exactFileName);
    const doc = generated.find((d) => keyForDoc(d) === key && norm(d.generationStatus) !== "SUPERSEDED");
    const valid = doc && VALID.has(norm(doc.validationStatus));
    const approved = doc && APPROVED.has(norm(doc.reviewStatus));
    const ready = doc && isExportReady(doc as any) && bytes(doc) > 0;
    let status: PlannedPackageDocument["status"] = !doc ? "missing" : ready ? "export_ready" : approved ? "approved" : valid ? "valid" : "generated";
    let blockerReason: string | null = null;
    if (file.required && !doc) blockerReason = `${file.exactFileName} is planned as required but has not been generated or uploaded.`;
    else if (file.required && doc && file.format === "PDF" && norm(doc.format) !== "PDF") { status = "blocked"; blockerReason = `${file.exactFileName} requires PDF but current document format is ${doc.format ?? "unknown"}. Upload an approved final PDF.`; }
    else if (file.required && doc && !ready) blockerReason = exportBlockReason(doc as any) ?? "Generated document is not approved/export-ready.";
    return { key, displayName: file.exactFileName, required: file.required, envelope: envelope(file.envelope), expectedFormat: fmt(file.format), sourceRequirementIds: file.sourceRequirementIds, generationMode: file.templateRequired ? "manual_upload_required" : "generated", generatedDocumentId: doc?.id ?? null, status, blockerReason };
  });
}

export function mapGeneratedDocumentsToSubmissionPlan(generated: any[], planned: PlannedPackageDocument[]): GeneratedPackageDocument[] {
  const planKeys = new Set(planned.map((p) => p.key));
  return generated.filter((d) => norm(d.generationStatus) !== "SUPERSEDED").map((d) => { const key = keyForDoc(d); const ready = isExportReady(d as any) && bytes(d) > 0; return { id: d.id, key, name: d.name ?? d.exactFileName ?? d.id, finalFileName: d.exactFileName ?? d.name ?? `${d.id}.docx`, documentType: d.documentType ?? "", format: norm(d.format) || "DOCX", generationStatus: d.generationStatus ?? "", validationStatus: d.validationStatus ?? "", reviewStatus: d.reviewStatus ?? "", plannedDocumentKey: planKeys.has(key) ? key : null, exportReady: ready, blockerReason: ready ? null : exportBlockReason(d as any) ?? (bytes(d) === 0 ? "Zero-byte or missing file content." : "Not export-ready."), sizeBytes: bytes(d) }; });
}
export function detectDocumentsOutsidePlan(generated: GeneratedPackageDocument[]) { return generated.filter((d) => !d.plannedDocumentKey); }
export function detectMissingRequiredDocuments(planned: PlannedPackageDocument[]) { return planned.filter((p) => p.required && p.status !== "generated" && p.status !== "valid" && p.status !== "approved" && p.status !== "export_ready"); }
export function detectPdfExportRequirements(planned: PlannedPackageDocument[], generated: GeneratedPackageDocument[]) { const requiredPdf = planned.filter((p) => p.required && p.expectedFormat === "PDF"); const missing = requiredPdf.filter((p) => !generated.some((g) => g.plannedDocumentKey === p.key && g.format === "PDF" && g.exportReady)); return { pdfRequired: requiredPdf.length > 0, pdfConversionAvailable: false, requiredPdfMissing: missing.length > 0, missing }; }

export function buildFinalZipManifestFromModel(tenderId: string, planned: PlannedPackageDocument[], generated: GeneratedPackageDocument[]): FinalZipManifest {
  const files = planned.filter((p) => p.status !== "not_applicable").map((p) => { const doc = generated.find((g) => g.plannedDocumentKey === p.key && g.exportReady) ?? generated.find((g) => g.plannedDocumentKey === p.key); const approved = doc ? APPROVED.has(norm(doc.reviewStatus)) : false; const exportReady = Boolean(doc?.exportReady && approved && doc.sizeBytes > 0 && doc.format === p.expectedFormat); return { plannedDocumentKey: p.key, finalFileName: p.displayName, sourceDocumentId: doc?.id ?? null, sourceUploadId: null, format: doc?.format ?? p.expectedFormat, sizeBytes: doc?.sizeBytes ?? 0, envelope: p.envelope, required: p.required, approved, exportReady, blockerReason: exportReady || !p.required ? null : p.blockerReason ?? `${p.displayName} is not ready for ZIP export.` }; });
  const names = new Set<string>(); const dupes: string[] = [];
  for (const f of files) { const n = f.finalFileName.toLowerCase(); if (names.has(n)) dupes.push(f.finalFileName); names.add(n); }
  const missingRequiredFiles = files.filter((f) => f.required && !f.exportReady).map((f) => f.finalFileName).concat(dupes.map((d) => `Duplicate filename: ${d}`));
  return { tenderId, files, missingRequiredFiles, extraFilesExcluded: generated.filter((g) => !g.plannedDocumentKey).map((g) => `${g.finalFileName}: outside submission plan`), ready: missingRequiredFiles.length === 0 };
}

export async function getFinalPackageReadinessModel(prisma: any, tenderId: string, userId: string): Promise<FinalPackageReadinessModel> {
  const tender = await prisma.tender.findFirst({ where: { id: tenderId, userId }, select: { id: true, title: true, exactFileNaming: true, exactFileOrder: true, pageLimit: true, submissionMethod: true, tenderCategory: true, analysisExtractionStatus: true, requirements: { include: { complianceMatrixRows: true } }, generatedDocuments: { orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }] }, expertMatches: { include: { expert: { select: { trustLevel: true } } } }, projectMatches: { include: { project: { select: { trustLevel: true } } } } } });
  if (!tender) throw new Error("Tender not found");
  const reqStatuses = mapRequirementsToEvidence(tender.requirements, tender.expertMatches, tender.projectMatches);
  const planned = deriveRequiredPackageDocuments(tender, tender.generatedDocuments);
  const generated = mapGeneratedDocumentsToSubmissionPlan(tender.generatedDocuments, planned);
  const missingRequired = detectMissingRequiredDocuments(planned);
  const outside = detectDocumentsOutsidePlan(generated);
  const pdf = detectPdfExportRequirements(planned, generated);
  const docBlockers: FinalPackageBlocker[] = planned.filter((p) => p.required && p.blockerReason).map((p) => ({ area: "documents", code: p.status === "missing" ? "PLANNED_DOCUMENT_MISSING" : "PLANNED_DOCUMENT_BLOCKED", title: p.displayName, documentName: p.displayName, generatedDocumentId: p.generatedDocumentId, reason: p.blockerReason!, nextAction: p.status === "missing" ? "Generate the planned document or upload the required original." : p.expectedFormat === "PDF" ? "Upload an approved final PDF mapped to this planned document." : "Validate, review, and approve this document." }));
  const reqBlockers: FinalPackageBlocker[] = reqStatuses.filter((r) => r.mandatory && !r.hasTrustedTrace).map((r) => ({ area: "requirements", code: "MANDATORY_REQUIREMENT_EVIDENCE_NOT_TRUSTED", title: r.title, requirementId: r.requirementId, reason: r.blockerReason ?? "Mandatory requirement lacks trusted traced evidence.", nextAction: `Add trusted traced evidence for mandatory requirement: ${r.title}` }));
  const manifest = buildFinalZipManifestFromModel(tenderId, planned, generated);
  const exportBlockers: FinalPackageBlocker[] = manifest.missingRequiredFiles.map((name) => ({ area: "export", code: "FINAL_ZIP_FILE_NOT_READY", title: name, documentName: name, reason: `${name} is missing, duplicate, wrong format, zero-byte, or unapproved.`, nextAction: "Resolve the document blocker and re-check final ZIP readiness." }));
  const selectedProjects = tender.projectMatches.filter((m: any) => m.isSelected);
  const reviewedSelectedProjects = selectedProjects.filter((m: any) => m.project?.trustLevel === "REVIEWED").length;
  const highScoreSelected = selectedProjects.filter((m: any) => Number(m.score) >= 90).length;
  const belowThresholdSelected = selectedProjects.filter((m: any) => Number(m.score) < 90).length;
  const blockerCount = reqBlockers.length + docBlockers.length + exportBlockers.length;
  const status = manifest.ready ? "export_ready" : missingRequired.length ? "generation_ready" : docBlockers.length ? "review_required" : "export_blocked";
  return { tenderId, requirementEvidenceStatuses: reqStatuses, projectMatchSummary: { selectedReviewed: reviewedSelectedProjects, highScoreSelected, belowThresholdSelected, missingComparableCoverage: tender.requirements.some((r: any) => norm(r.requirementType) === "PROJECT_EXPERIENCE") && reviewedSelectedProjects === 0 ? 1 : 0, explanation: reviewedSelectedProjects > 0 && highScoreSelected === 0 ? "Selected projects are reviewed but below 90% match; improve relevance or accept with justification." : null }, requirements: { total: reqStatuses.length, mandatory: reqStatuses.filter((r) => r.mandatory).length, traced: reqStatuses.filter((r) => r.hasTrustedTrace).length, mandatoryTraced: reqStatuses.filter((r) => r.mandatory && r.hasTrustedTrace).length, strongEvidence: reqStatuses.filter((r) => r.strongestEvidenceLevel === "FULL").length, weakEvidence: reqStatuses.filter((r) => ["WEAK", "PARTIAL"].includes(r.strongestEvidenceLevel)).length, missingEvidence: reqStatuses.filter((r) => r.strongestEvidenceLevel === "NONE").length, coverageRatio: reqStatuses.length ? reqStatuses.filter((r) => r.hasTrustedTrace).length / reqStatuses.length : 0, blockers: reqBlockers }, evidence: { rows: tender.requirements.reduce((s: number, r: any) => s + (r.complianceMatrixRows?.length ?? 0), 0), selected: tender.requirements.reduce((s: number, r: any) => s + (r.complianceMatrixRows?.length ?? 0), 0), strong: reqStatuses.filter((r) => r.strongestEvidenceLevel === "FULL").length, substantial: reqStatuses.filter((r) => r.strongestEvidenceLevel === "SUBSTANTIAL").length, weak: reqStatuses.filter((r) => ["WEAK", "PARTIAL"].includes(r.strongestEvidenceLevel)).length, missing: reqStatuses.filter((r) => r.strongestEvidenceLevel === "NONE").length, expertMatches: tender.expertMatches.length, reviewedExpertMatches: tender.expertMatches.filter((m: any) => m.isSelected && m.expert?.trustLevel === "REVIEWED").length, projectMatches: tender.projectMatches.length, reviewedProjectMatches: reviewedSelectedProjects, blockers: reqBlockers }, documents: { planned, required: planned.filter((p) => p.required), generated, valid: generated.filter((g) => VALID.has(norm(g.validationStatus))), approved: generated.filter((g) => APPROVED.has(norm(g.reviewStatus))), missingRequired, extraGeneratedOutsidePlan: outside, exportReady: generated.filter((g) => g.exportReady && g.plannedDocumentKey), blockers: docBlockers }, export: { ready: manifest.ready, zipReady: manifest.ready, pdfRequired: pdf.pdfRequired, pdfConversionAvailable: pdf.pdfConversionAvailable, requiredPdfMissing: pdf.requiredPdfMissing, workspaceCount: generated.length, exportCandidateCount: generated.filter((g) => g.plannedDocumentKey).length, blockers: exportBlockers, manifest }, summary: { status, score: Math.max(0, Math.min(100, Math.round(100 - blockerCount * 12 - missingRequired.length * 8))), blockerCount, nextBestActions: [...reqBlockers, ...docBlockers, ...exportBlockers].slice(0, 8).map((b) => b.nextAction) } };
}
