import { generateWithFallback, isAIEnabled } from "../ai";

// Patterns that signal AI-generated or template text
const AI_PATTERNS = [
  /\bas an ai\b/gi,
  /\bi am an ai\b/gi,
  /\blanguage model\b/gi,
  /\bcertainly[,!]?\s/gi,
  /\bof course[,!]?\s/gi,
  /\babsolutely[,!]?\s/gi,
  /\bplaceholder\b/gi,
  /\[insert [^\]]+\]/gi,
  /\{[^}]+\}/g,
  /\bTODO\b/g,
  /\bXXX\b/g,
  /\b\[TBD\]\b/gi,
  /\b\[NAME\]\b/gi,
  /\b\[DATE\]\b/gi,
  /\bsample text\b/gi,
  /\bexample text\b/gi,
  /\bgenerated by\b/gi,
  /^\s*note to (writer|editor|reviewer):.*$/gim,
  /^\s*\[.*?\]\s*$/gim,
];

function basicCleanup(text: string): string {
  let out = text;

  // Remove AI traces
  for (const pattern of AI_PATTERNS) {
    out = out.replace(pattern, "");
  }

  // Remove long em-dashes (AI writing habit)
  out = out.replace(/\s*—\s*/g, " — ");

  // Normalize multiple blank lines
  out = out.replace(/\n{3,}/g, "\n\n");

  // Remove trailing spaces
  out = out.replace(/ +$/gm, "");

  // Trim
  out = out.trim();

  return out;
}

const HUMANIZE_SYSTEM_PROMPT = `You are a senior proposal editor at a consultancy firm. You take draft proposal text written by a junior author or an AI assistant and rewrite it so it sounds like a senior consultant wrote it from scratch — professional, confident, business-grade, evidence-led, and free of AI traces. You preserve every fact in the source text. You never invent new claims, numbers, project names, or expert names. You return only the rewritten text — no commentary, no preamble, no explanation of what you changed.`;

/**
 * AI-powered humanization pass. Tries Claude first via the shared
 * generateWithFallback helper (which falls back to Gemini if Claude
 * fails AND Gemini is configured). Wrapped in try/catch by the caller
 * — if every provider fails, the deterministic basicCleanup result
 * is returned instead, so the proposal still ships.
 */
async function humanizeWithAI(text: string): Promise<string> {
  const prompt = `The following text was drafted for a tender proposal. Rewrite it to sound like it was written by a senior consultant — professional, confident, and business-grade.

Rules:
- Remove any AI traces ("As an AI...", "Certainly!", "Of course!", etc.)
- Remove any placeholder text ([INSERT NAME], {date}, TODO, etc.)
- Improve sentence flow and vary structure
- Keep all factual content intact — do not invent or remove facts
- Do not add new sections or headings not in the original
- Return only the rewritten text, no commentary

TEXT TO REWRITE:
${text.slice(0, 6000)}`;

  const result = await generateWithFallback(prompt, { systemPrompt: HUMANIZE_SYSTEM_PROMPT });
  return result || text;
}

export async function humanize(text: string): Promise<string> {
  const cleaned = basicCleanup(text);
  if (!isAIEnabled() || cleaned.length < 100) return cleaned;

  try {
    return await humanizeWithAI(cleaned);
  } catch {
    return cleaned;
  }
}
