import { isAIEnabled } from "../ai";

// Patterns that signal AI-generated or template text
const AI_PATTERNS = [
  /\bas an ai\b/gi,
  /\bi am an ai\b/gi,
  /\blanguage model\b/gi,
  /\bcertainly[,!]?\s/gi,
  /\bof course[,!]?\s/gi,
  /\babsolutely[,!]?\s/gi,
  /\bplaceholder\b/gi,
  /\[insert [^\]]+\]/gi,
  /\{[^}]+\}/g,
  /\bTODO\b/g,
  /\bXXX\b/g,
  /\b\[TBD\]\b/gi,
  /\b\[NAME\]\b/gi,
  /\b\[DATE\]\b/gi,
  /\bsample text\b/gi,
  /\bexample text\b/gi,
  /\bgenerated by\b/gi,
  /^\s*note to (writer|editor|reviewer):.*$/gim,
  /^\s*\[.*?\]\s*$/gim,
];

function basicCleanup(text: string): string {
  let out = text;

  // Remove AI traces
  for (const pattern of AI_PATTERNS) {
    out = out.replace(pattern, "");
  }

  // Remove long em-dashes (AI writing habit)
  out = out.replace(/\s*—\s*/g, " — ");

  // Normalize multiple blank lines
  out = out.replace(/\n{3,}/g, "\n\n");

  // Remove trailing spaces
  out = out.replace(/ +$/gm, "");

  // Trim
  out = out.trim();

  return out;
}

async function humanizeWithAI(text: string): Promise<string> {
  const Anthropic = (await import("@anthropic-ai/sdk")).default;
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY ?? "" });

  const message = await client.messages.create({
    model: "claude-3-5-haiku-20241022",
    max_tokens: 2048,
    messages: [
      {
        role: "user",
        content: `You are a professional proposal editor for a consultancy firm.
The following text was drafted for a tender proposal.
Rewrite it to sound like it was written by a senior consultant — professional, confident, and business-grade.

Rules:
- Remove any AI traces ("As an AI...", "Certainly!", "Of course!", etc.)
- Remove any placeholder text ([INSERT NAME], {date}, TODO, etc.)
- Improve sentence flow and vary structure
- Keep all factual content intact — do not invent or remove facts
- Do not add new sections or headings not in the original
- Return only the rewritten text, no commentary

TEXT TO REWRITE:
${text.slice(0, 6000)}`,
      },
    ],
  });

  const block = message.content[0];
  return (block?.type === "text" ? block.text : null) || text;
}

export async function humanize(text: string): Promise<string> {
  const cleaned = basicCleanup(text);
  if (!isAIEnabled() || cleaned.length < 100) return cleaned;

  try {
    return await humanizeWithAI(cleaned);
  } catch {
    return cleaned;
  }
}
