import { generateWithFallback, isAIEnabled } from "../ai";

// Patterns that signal AI-generated or template text
const AI_PATTERNS = [
  /\bas an ai\b/gi,
  /\bi am an ai\b/gi,
  /\blanguage model\b/gi,
  /\bcertainly[,!]?\s/gi,
  /\bof course[,!]?\s/gi,
  /\babsolutely[,!]?\s/gi,
  /\bplaceholder\b/gi,
  /\[insert [^\]]+\]/gi,
  /\{[^}]+\}/g,
  /\bTODO\b/g,
  /\bXXX\b/g,
  /\b\[TBD\]\b/gi,
  /\b\[NAME\]\b/gi,
  /\b\[DATE\]\b/gi,
  /\bsample text\b/gi,
  /\bexample text\b/gi,
  /\bgenerated by\b/gi,
  /^\s*note to (writer|editor|reviewer):.*$/gim,
  /^\s*\[.*?\]\s*$/gim,
];

function basicCleanup(text: string): string {
  let out = text;

  // Remove AI traces
  for (const pattern of AI_PATTERNS) {
    out = out.replace(pattern, "");
  }

  // Remove long em-dashes (AI writing habit)
  out = out.replace(/\s*—\s*/g, " — ");

  // Normalize multiple blank lines
  out = out.replace(/\n{3,}/g, "\n\n");

  // Remove trailing spaces
  out = out.replace(/ +$/gm, "");

  // Trim
  out = out.trim();

  return out;
}

// Deterministic-only humanization (no AI call).
//
// This is the FAST path used inside generate-elite.ts on every proposal.
// It runs the same AI-trace pattern stripper as the full humanize()
// function, but does NOT call Claude for a stylistic rewrite — so it
// adds ~1ms per proposal instead of ~15-30s.
//
// The full AI-rewrite path remains available via humanize() below for
// callers who want a senior-editor-quality stylistic pass; that path
// is opt-in via PROPOSAL_HUMANIZE_AI=true so Vercel Hobby tier users
// don't blow their 60s function budget on a 6th Claude call.
export function humanizeDeterministic(text: string): string {
  return basicCleanup(text);
}

const HUMANIZE_SYSTEM_PROMPT = `You are a senior proposal editor at a consultancy firm. You take draft proposal text written by a junior author or an AI assistant and rewrite it so it sounds like a senior consultant wrote it from scratch — professional, confident, business-grade, evidence-led, and free of AI traces. You preserve every fact in the source text. You never invent new claims, numbers, project names, or expert names. You return only the rewritten text — no commentary, no preamble, no explanation of what you changed.`;

/**
 * AI-powered humanization pass. Tries Claude first via the shared
 * generateWithFallback helper (which falls back to Gemini if Claude
 * fails AND Gemini is configured). Wrapped in try/catch by the caller
 * — if every provider fails, the deterministic basicCleanup result
 * is returned instead, so the proposal still ships.
 */
async function humanizeWithAI(text: string): Promise<string> {
  const prompt = `The following text was drafted for a tender proposal. Rewrite it to sound like it was written by a senior consultant — professional, confident, and business-grade.

Rules:
- Remove any AI traces ("As an AI...", "Certainly!", "Of course!", etc.)
- Remove any placeholder text ([INSERT NAME], {date}, TODO, etc.)
- Improve sentence flow and vary structure
- Keep all factual content intact — do not invent or remove facts
- Do not add new sections or headings not in the original
- Return only the rewritten text, no commentary

TEXT TO REWRITE:
${text.slice(0, 6000)}`;

  const result = await generateWithFallback(prompt, { systemPrompt: HUMANIZE_SYSTEM_PROMPT });
  return result || text;
}

export async function humanize(text: string): Promise<string> {
  const cleaned = basicCleanup(text);
  if (!isAIEnabled() || cleaned.length < 100) return cleaned;

  try {
    return await humanizeWithAI(cleaned);
  } catch {
    return cleaned;
  }
}

// Targeted opening-sections humanizer.
//
// Extracts the Cover Letter and Executive Summary from a full proposal
// markdown, sends only those two sections (~1500–3000 tokens) to the AI
// for a senior-editor polish pass, and stitches the result back into the
// full proposal. Always-on — no env var gate. The small token budget means
// it costs ~8–15s on Vercel Hobby instead of the 25–45s a whole-proposal
// humanization would cost. Falls back silently to the untouched sections
// if the AI call fails.
//
// WHY ONLY THESE TWO SECTIONS
// ────────────────────────────
// Evaluators read the Cover Letter first and the Executive Summary second.
// These sections decide whether the proposal stays in the "serious
// contender" pile. AI-trace phrases ("Certainly!", "As an AI…") or
// awkward transitions in those two sections cost disproportionately more
// points than the same issues deep in Section C. Humanizing them
// specifically — with a ~500-token budget each — is the highest-ROI
// Claude call in the pipeline.

const OPENING_HUMANIZE_SYSTEM_PROMPT = `You are a senior bid director with 25 years of proposal writing experience. You polish the opening two sections of a technical proposal — the Cover Letter and Executive Summary — so they read as if a confident, evidence-led senior consultant wrote them from scratch. You never invent facts. You remove all AI traces. You return ONLY the polished text with the same headings — no commentary, no preamble.`;

function extractSection(markdown: string, headingPattern: RegExp): { text: string; start: number; end: number } | null {
  const lines = markdown.split("\n");
  let startLine = -1;
  for (let i = 0; i < lines.length; i++) {
    if (headingPattern.test(lines[i])) { startLine = i; break; }
  }
  if (startLine < 0) return null;

  // Find the next top-level heading (# ) that isn't this one.
  let endLine = lines.length;
  for (let i = startLine + 1; i < lines.length; i++) {
    if (/^# /.test(lines[i])) { endLine = i; break; }
  }

  const text = lines.slice(startLine, endLine).join("\n");
  const start = lines.slice(0, startLine).join("\n").length + (startLine > 0 ? 1 : 0);
  const end = start + text.length;
  return { text, start, end };
}

export async function humanizeOpeningSections(markdown: string): Promise<string> {
  if (!isAIEnabled()) return markdown;

  const coverSection = extractSection(markdown, /^#\s+Cover\s+Letter/i);
  const execSection = extractSection(markdown, /^#\s+Executive\s+Summary/i);

  if (!coverSection && !execSection) return markdown;

  const combined = [coverSection?.text, execSection?.text].filter(Boolean).join("\n\n");
  if (combined.trim().length < 100) return markdown;

  const prompt = `Polish the Cover Letter and Executive Summary below. Keep every fact, project name, expert name, contract value, and client name exactly as-is. Remove AI traces and awkward phrasing. Vary sentence length. Return the same two headings with the polished text under each — nothing else.

${combined.slice(0, 5000)}`;

  try {
    const polished = await generateWithFallback(prompt, { systemPrompt: OPENING_HUMANIZE_SYSTEM_PROMPT });
    if (!polished || polished.trim().length < 50) return markdown;

    // Stitch polished sections back in by replacing the original text spans.
    // Work from last to first so character offsets stay valid.
    let result = markdown;
    const polishedCover = extractSection(polished, /^#\s+Cover\s+Letter/i);
    const polishedExec = extractSection(polished, /^#\s+Executive\s+Summary/i);

    // Replace exec first (further down), then cover (start of doc).
    if (execSection && polishedExec) {
      const before = result.slice(0, execSection.start);
      const after = result.slice(execSection.end);
      result = before + polishedExec.text + after;
    }
    if (coverSection && polishedCover) {
      const before = result.slice(0, coverSection.start);
      const after = result.slice(coverSection.end);
      result = before + polishedCover.text + after;
    }
    return result;
  } catch {
    return markdown;
  }
}
