export type TenderRequirementLite = { title: string; description: string; priority: string; requirementType: string };
export type TenderLite = { title: string; reference?: string | null; clientName?: string | null; country?: string | null; description?: string | null; intakeSummary?: string | null; analysisSummary?: string | null; evaluationMethodology?: string | null; deadline?: Date | string | null; submissionMethod?: string | null; submissionAddress?: string | null };
export type CompanyLite = { name: string; legalName?: string | null; description?: string | null; profileSummary?: string | null; serviceLines: string; sectors: string; email?: string | null; phone?: string | null; website?: string | null; address?: string | null };
export type ExpertLite = { fullName: string; title?: string | null; yearsExperience?: number | null; disciplines: string; sectors: string; certifications: string; profile?: string | null };
export type ProjectLite = { name: string; clientName?: string | null; country?: string | null; sector?: string | null; serviceAreas: string; contractValue?: number | null; currency?: string | null; summary?: string | null };
export type ProposalTheme = { code: string; label: string; triggers: RegExp[]; proofTerms: RegExp[]; methodologyBullets: string[] };
export type ProposalIntelligence = { tenderText: string; clientName: string; assignmentName: string; primarySector: string; requiredSections: string[]; evaluationCriteria: string[]; submissionRules: string[]; differentiators: string[]; themes: ProposalTheme[]; topProjects: ProjectLite[]; topExperts: ExpertLite[]; gapsToAddressInNarrative: string[] };

export function safeParseArr(value: string | null | undefined): string[] { if (!value) return []; try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.map(String).filter(Boolean) : []; } catch { return value.split(/[,;|]/).map((item) => item.trim()).filter(Boolean); } }
function clean(value: string | null | undefined): string { return (value ?? "").replace(/\s+/g, " ").trim(); }
function textOf(...values: Array<string | null | undefined>): string { return values.map(clean).filter(Boolean).join("\n"); }
function money(value?: number | null, currency?: string | null): string | null { if (!value) return null; const label = currency || "ETB"; if (value >= 1_000_000_000) return `${label} ${(value / 1_000_000_000).toFixed(1)}B`; if (value >= 1_000_000) return `${label} ${(value / 1_000_000).toFixed(1)}M`; return `${label} ${value.toLocaleString()}`; }

export const PROPOSAL_THEMES: ProposalTheme[] = [
  { code: "HEALTHCARE", label: "Healthcare facility design and clinical workflow", triggers: [/health/i, /hospital/i, /medical/i, /clinic/i, /pharmacy/i, /radiology/i, /laboratory/i, /in[- ]?patient/i, /out[- ]?patient/i, /emergency/i], proofTerms: [/hospital/i, /health/i, /medical/i, /clinic/i, /radiology/i, /laboratory/i, /pharmacy/i, /patient/i], methodologyBullets: ["clinical zoning for emergency, OPD, in-patient, laboratory, imaging/radiology and pharmacy functions", "clean/dirty flow separation, patient/staff/supply movement mapping, and IPC-compliant layout development", "radiation shielding coordination for imaging areas and medical-equipment spatial clearances", "Ethiopian health regulatory approval documentation supported by coordinated architectural, structural and MEP drawings"] },
  { code: "RENOVATION_ADAPTATION", label: "Existing facility assessment and renovation conversion", triggers: [/renovation/i, /modification/i, /existing/i, /premises/i, /facility identification/i, /shortlisted properties/i, /assessment/i, /retrofit/i], proofTerms: [/renovation/i, /modification/i, /assessment/i, /retrofit/i, /existing/i, /museum/i], methodologyBullets: ["site assessment matrix covering structural suitability, spatial flexibility, utilities, accessibility and expansion potential", "technical due diligence before design commitment to avoid selecting a building that cannot serve the intended function", "renovation drawings, BOQ, cost estimates and implementation oversight after the preferred premises are selected"] },
  { code: "MEP_BIOMEDICAL", label: "MEP, biomedical, medical gas and equipment coordination", triggers: [/MEP/i, /biomedical/i, /bio-medical/i, /medical gas/i, /equipment/i, /electrical load/i, /IT systems/i, /telehealth/i, /HVAC/i], proofTerms: [/MEP/i, /electrical/i, /sanitary/i, /mechanical/i, /medical gas/i, /equipment/i, /HVAC/i, /power/i], methodologyBullets: ["medical-grade electrical load planning, UPS/generator backup assumptions and equipment power coordination", "medical gas, water supply, drainage, clinical waste and fire protection coordination", "ICT, telehealth, PACS-ready data pathways and building services coordination from schematic design stage"] },
  { code: "WATER_INFRASTRUCTURE", label: "Water, hydraulic and infrastructure capability", triggers: [/water/i, /pump/i, /borehole/i, /sanitary/i, /hydraulic/i, /irrigation/i, /pipeline/i], proofTerms: [/water/i, /sanitary/i, /hydraulic/i, /borehole/i, /pump/i, /pipeline/i], methodologyBullets: ["hydraulic assessment and service capacity verification", "water supply, drainage, fire suppression and operational resilience planning", "field investigation, design, BOQ and supervision integration"] },
  { code: "DONOR_COMPLIANCE", label: "Donor, quality, ESG and compliance documentation", triggers: [/World Bank/i, /UNDP/i, /ESF/i, /environmental/i, /social/i, /safeguard/i, /quality/i, /compliance/i, /certification/i], proofTerms: [/World Bank/i, /UNDP/i, /ESF/i, /British Council/i, /quality/i, /ISO/i, /environmental/i, /social/i], methodologyBullets: ["project-specific quality plan, document control and staged design review", "environmental, social, safety and ethics safeguards integrated into delivery planning", "client-facing reporting and approval records managed through formal revision control"] },
];

function scoreTextAgainstTheme(text: string, theme: ProposalTheme): number { let score = 0; for (const p of theme.proofTerms) if (p.test(text)) score += 2; for (const p of theme.triggers) if (p.test(text)) score += 1; return score; }
function projectScore(project: ProjectLite, themes: ProposalTheme[], tenderText: string): number { const text = textOf(project.name, project.clientName, project.country, project.sector, project.summary, ...safeParseArr(project.serviceAreas)); let score = 0; for (const t of themes) score += scoreTextAgainstTheme(text, t); if (/hospital|health|medical|clinic/i.test(text) && /hospital|health|medical|clinic/i.test(tenderText)) score += 12; if (/renovation|modification|assessment|existing/i.test(text) && /renovation|premises|existing|assessment/i.test(tenderText)) score += 6; if (project.contractValue) score += Math.min(5, Math.log10(project.contractValue)); return score; }
function expertScore(expert: ExpertLite, themes: ProposalTheme[], tenderText: string): number { const text = textOf(expert.fullName, expert.title, expert.profile, ...safeParseArr(expert.disciplines), ...safeParseArr(expert.sectors), ...safeParseArr(expert.certifications)); let score = 0; for (const t of themes) score += scoreTextAgainstTheme(text, t); if (/architect/i.test(text) && /architect|design|layout/i.test(tenderText)) score += 8; if (/MEP|electrical|mechanical|sanitary/i.test(text) && /MEP|electrical|medical gas|equipment|sanitary/i.test(tenderText)) score += 8; if (/biomedical|bio-medical/i.test(text) && /biomedical|bio-medical|medical equipment/i.test(tenderText)) score += 10; if (/structural/i.test(text) && /structural|adequacy|building/i.test(tenderText)) score += 6; if (expert.yearsExperience) score += Math.min(5, expert.yearsExperience / 5); return score; }
function detectRequiredSections(tenderText: string): string[] { const sections = [/company profile/i.test(tenderText) ? "SECTION A: COMPANY PROFILE" : null, /relevant experience|portfolio|similar/i.test(tenderText) ? "SECTION B: RELEVANT EXPERIENCE" : null, /technical approach|methodology|understanding/i.test(tenderText) ? "SECTION C: TECHNICAL APPROACH" : null, /additional information|value[- ]?added|certifications|awards/i.test(tenderText) ? "SECTION D: ADDITIONAL INFORMATION" : null].filter(Boolean) as string[]; return sections.length ? sections : ["Technical Proposal", "Company Profile", "Relevant Experience", "Technical Approach", "Compliance Statement"]; }
function detectEvaluationCriteria(tenderText: string): string[] { return [/healthcare project experience|relevant .*experience/i.test(tenderText) ? "Relevant healthcare / similar project experience" : null, /portfolio/i.test(tenderText) ? "Quality and relevance of portfolio" : null, /technical understanding|healthcare facility design/i.test(tenderText) ? "Technical understanding of facility design" : null, /professional team|multidisciplinary team|strength of.*team/i.test(tenderText) ? "Strength of professional team" : null, /submission requirements|compliance/i.test(tenderText) ? "Compliance with submission requirements" : null].filter(Boolean) as string[]; }
function detectSubmissionRules(tender: TenderLite, tenderText: string): string[] { const rules: string[] = []; if (/financial proposal.*not|required.*technical proposal only|technical proposal only|no financial/i.test(tenderText)) rules.push("Technical proposal only — do not include a financial proposal."); const emails = Array.from(tenderText.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)).map((m) => m[0]); if (emails.length) rules.push(`Submission email recipients: ${Array.from(new Set(emails)).join(", ")}.`); const subject = tenderText.match(/Subject Line:\s*["“]([^"”]+)["”]/i) ?? tenderText.match(/subject[^\n.]*["“]([^"”]+)["”]/i); if (subject?.[1]) rules.push(`Exact subject line: "${subject[1]}".`); if (tender.deadline) rules.push(`Deadline: ${new Date(tender.deadline).toLocaleString("en-US", { year: "numeric", month: "short", day: "numeric" })}.`); if (tender.submissionMethod) rules.push(`Submission method: ${tender.submissionMethod}.`); if (tender.submissionAddress) rules.push(`Submission address/portal: ${tender.submissionAddress}.`); return Array.from(new Set(rules)); }
function detectThemes(tenderText: string): ProposalTheme[] { const matched = PROPOSAL_THEMES.filter((t) => t.triggers.some((p) => p.test(tenderText))); return matched.length ? matched : [PROPOSAL_THEMES[4]]; }
function inferSector(tenderText: string): string { if (/health|hospital|medical|clinic/i.test(tenderText)) return "Healthcare / Medical Facility"; if (/water|pump|borehole|sanitary|hydraulic/i.test(tenderText)) return "Water Infrastructure"; if (/road|bridge|transport/i.test(tenderText)) return "Transport Infrastructure"; if (/urban|master plan|municipal/i.test(tenderText)) return "Urban Planning / Municipal Infrastructure"; return "General Consultancy"; }
function makeDifferentiators(company: CompanyLite, projects: ProjectLite[], experts: ExpertLite[], themes: ProposalTheme[]): string[] { const allProjectText = projects.map((p) => textOf(p.name, p.summary, p.sector, p.clientName)).join("\n"); const allExpertText = experts.map((e) => textOf(e.fullName, e.title, e.profile, ...safeParseArr(e.disciplines))).join("\n"); const serviceText = safeParseArr(company.serviceLines).join(", "); const items: string[] = []; if (/hospital|health|medical/i.test(allProjectText)) items.push("Direct healthcare facility design / renovation experience should lead the proposal narrative."); if (/World Bank|ESF|UNDP|British Council/i.test(textOf(company.profileSummary, company.description, allProjectText))) items.push("Donor-grade documentation and compliance experience should be positioned as a risk-reduction advantage."); if (/geotechnical|drilling|laboratory/i.test(textOf(company.profileSummary, company.description, serviceText))) items.push("In-house geotechnical and laboratory capability should be framed as a schedule and due-diligence advantage."); if (/MEP|electrical|sanitary|mechanical/i.test(allExpertText)) items.push("Multidisciplinary in-house MEP capability should be linked directly to the tender technical systems risk."); if (themes.some((t) => t.code === "HEALTHCARE")) items.push("Proposal must show not just architecture, but clinical workflow, patient safety, IPC, imaging, laboratory and pharmacy understanding."); return Array.from(new Set(items)).slice(0, 7); }

export function buildProposalIntelligence(params: { tender: TenderLite; company: CompanyLite; requirements: TenderRequirementLite[]; experts: ExpertLite[]; projects: ProjectLite[] }): ProposalIntelligence { const { tender, company, requirements, experts, projects } = params; const tenderText = textOf(tender.title, tender.reference, tender.clientName, tender.description, tender.intakeSummary, tender.analysisSummary, tender.evaluationMethodology, tender.submissionAddress, ...requirements.map((r) => `${r.title} ${r.description} ${r.requirementType} ${r.priority}`)); const themes = detectThemes(tenderText); const topProjects = [...projects].sort((a, b) => projectScore(b, themes, tenderText) - projectScore(a, themes, tenderText)).slice(0, 9); const topExperts = [...experts].sort((a, b) => expertScore(b, themes, tenderText) - expertScore(a, themes, tenderText)).slice(0, 14); const gaps: string[] = []; if (themes.some((t) => t.code === "HEALTHCARE") && !topProjects.some((p) => /hospital|health|medical|clinic/i.test(textOf(p.name, p.summary, p.sector)))) gaps.push("Healthcare tender detected but no clearly healthcare-specific reviewed project was selected; use the closest renovation/MEP projects and flag healthcare evidence for review."); if (/biomedical|bio-medical/i.test(tenderText) && !topExperts.some((e) => /biomedical|bio-medical/i.test(textOf(e.title, e.profile, ...safeParseArr(e.disciplines))))) gaps.push("Tender requires biomedical expertise; proposal should include a named biomedical specialist or a clear engagement plan."); if (/photo|drawing/i.test(tenderText)) gaps.push("Tender asks for photos/drawings; generated proposal should list them in appendices, not only describe projects."); return { tenderText, clientName: tender.clientName || (/pharo/i.test(tenderText) ? "Pharo Ventures" : "Client"), assignmentName: tender.title, primarySector: inferSector(tenderText), requiredSections: detectRequiredSections(tenderText), evaluationCriteria: detectEvaluationCriteria(tenderText), submissionRules: detectSubmissionRules(tender, tenderText), differentiators: makeDifferentiators(company, topProjects, topExperts, themes), themes, topProjects, topExperts, gapsToAddressInNarrative: gaps }; }
export function projectProofLine(project: ProjectLite): string { const value = money(project.contractValue, project.currency); const parts = [project.clientName, project.country, project.sector, value].filter(Boolean); const summary = clean(project.summary).slice(0, 360); return `${project.name}${parts.length ? ` — ${parts.join(" | ")}` : ""}${summary ? `. ${summary}` : ""}`; }
export function expertProofLine(expert: ExpertLite): string { const disciplines = safeParseArr(expert.disciplines).slice(0, 4).join(", "); const certs = safeParseArr(expert.certifications).slice(0, 3).join(", "); return `${expert.fullName}${expert.title ? ` — ${expert.title}` : ""}${expert.yearsExperience ? ` | ${expert.yearsExperience}+ years` : ""}${disciplines ? ` | ${disciplines}` : ""}${certs ? ` | ${certs}` : ""}`; }
