import { NextResponse } from "next/server";
import { getSession } from "../../../../../lib/auth";
import { prisma, prismaReady } from "../../../../../lib/prisma";
import { generateProposal, isAIEnabled } from "../../../../../lib/ai";

function safeParseArr(v: unknown): string[] {
  try { return JSON.parse(v as string) as string[]; } catch { return []; }
}

function fallbackNotice(reason: "AI_DISABLED" | "AI_UNAVAILABLE") {
  if (reason === "AI_DISABLED") {
    return "> Draft generated by deterministic benchmark fallback because the AI writer is not configured. The final tender engine can still generate a structured proposal from reviewed tender and company evidence.";
  }
  return "> Draft generated by deterministic benchmark fallback because the AI writer was temporarily unavailable. The system has hidden provider error details and used the local proposal engine instead.";
}

function fallbackProposal(params: {
  tenderTitle: string;
  tenderDescription: string;
  requirements: string[];
  companyName: string;
  companyProfile: string;
  serviceLines: string;
  reason: "AI_DISABLED" | "AI_UNAVAILABLE";
}) {
  const reqText = params.requirements.length
    ? params.requirements.map((r) => `- ${r}`).join("\n")
    : "- No detailed requirements have been extracted yet. Run analysis or add tender requirements before final submission.";

  return [
    fallbackNotice(params.reason),
    "",
    "## Executive Summary",
    `${params.companyName} submits this technical proposal for ${params.tenderTitle}. The response is based on uploaded tender information, extracted requirements, reviewed company evidence, and the company knowledge vault.`,
    "",
    "## Benchmark Proposal Logic",
    "- Lead the final proposal with the strongest comparable project evidence available in the app.",
    "- Carry the same lead evidence through the cover letter, executive summary, relevant experience, and methodology sections.",
    "- Map proposed experts to tender risks, previous comparable assignments, and delivery responsibilities.",
    "- Keep unsupported claims as bid-team confirmation items instead of inventing missing evidence.",
    "",
    "## Understanding of Requirements",
    params.tenderDescription || "The tender documents require a compliant technical and administrative response. The proposal team should verify all submission instructions, mandatory forms, deadline, file naming rules, and evaluation criteria before submission.",
    "",
    "## Extracted Requirements Checklist",
    reqText,
    "",
    "## Technical Approach",
    "The proposed approach is to review the tender requirements in detail, confirm mandatory eligibility and compliance items, assign best-fit experts and relevant project references, prepare a scope-by-scope technical methodology, and validate the final package against every submission instruction.",
    "",
    "## Company Qualifications",
    params.companyProfile || `${params.companyName} maintains reusable company knowledge, expert CVs, project references, registration evidence, financial documents, and policy/manual records in the tender knowledge vault.`,
    params.serviceLines ? `\nService lines: ${params.serviceLines}` : "",
    "",
    "## Evidence and Appendix Discipline",
    "- Attach or confirm company registration/licence, tax/legal records, certificates, CVs, project references, photos/drawings, testimony/completion evidence, and tender-specific declarations where required.",
    "- Remove, soften, or mark any unsupported project, expert, value, award, licence, or client claim before final submission.",
    "",
    "## Why Choose Us",
    "The proposal is supported by structured company knowledge, reviewed expert and project records, compliance checks, and document generation controls designed to reduce missed requirements and improve tender readiness.",
    "",
    "## Next Actions Before Submission",
    "- Run the full tender engine and confirm any gaps.",
    "- Use reviewed experts/projects or manually approve alternatives with evidence.",
    "- Validate all generated documents, filenames, appendices, and submission order.",
  ].filter(Boolean).join("\n");
}

export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const userId = await getSession();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  await prismaReady;
  const { id } = await params;

  const [tender, company] = await Promise.all([
    prisma.tender.findFirst({
      where: { id, userId },
      include: { requirements: true },
    }),
    prisma.company.findUnique({ where: { userId } }),
  ]);

  if (!tender) return NextResponse.json({ error: "Tender not found" }, { status: 404 });

  const requirementLines = tender.requirements.map((r) => `${r.title}: ${r.description}`);
  const companyName = company?.name ?? "Our Company";
  const companyProfile = company?.profileSummary ?? company?.description ?? "";
  const serviceLines = safeParseArr((company as { serviceLines?: unknown })?.serviceLines).join(", ");

  try {
    let proposal: string;
    let fallback = false;

    if (isAIEnabled()) {
      try {
        proposal = await generateProposal({
          tenderTitle: tender.title,
          tenderDescription: tender.description ?? tender.intakeSummary ?? "",
          requirements: requirementLines.map((r) => `- ${r}`).join("\n"),
          companyName,
          companyProfile,
          serviceLines,
        });
      } catch (aiError) {
        console.error("AI proposal failed; deterministic fallback used:", aiError);
        fallback = true;
        proposal = fallbackProposal({
          tenderTitle: tender.title,
          tenderDescription: tender.description ?? tender.intakeSummary ?? "",
          requirements: requirementLines,
          companyName,
          companyProfile,
          serviceLines,
          reason: "AI_UNAVAILABLE",
        });
      }
    } else {
      fallback = true;
      proposal = fallbackProposal({
        tenderTitle: tender.title,
        tenderDescription: tender.description ?? tender.intakeSummary ?? "",
        requirements: requirementLines,
        companyName,
        companyProfile,
        serviceLines,
        reason: "AI_DISABLED",
      });
    }

    await prisma.tender.update({
      where: { id },
      data: {
        intakeSummary: proposal,
        notes: tender.notes,
      },
    });

    return NextResponse.json({ success: true, proposal, fallback });
  } catch (error) {
    console.error("Proposal generation route error:", error);
    return NextResponse.json({ error: "Proposal generation failed" }, { status: 500 });
  }
}
