import { NextResponse } from "next/server";
import { getSession } from "../../../../../lib/auth";
import { prisma, prismaReady } from "../../../../../lib/prisma";
import { generateProposal, isAIEnabled } from "../../../../../lib/ai";

function safeParseArr(v: unknown): string[] {
  try { return JSON.parse(v as string) as string[]; } catch { return []; }
}

function fallbackProposal(params: {
  tenderTitle: string;
  tenderDescription: string;
  requirements: string[];
  companyName: string;
  companyProfile: string;
  serviceLines: string;
  aiError?: string;
}) {
  const reqText = params.requirements.length
    ? params.requirements.map((r) => `- ${r}`).join("\n")
    : "- No detailed requirements have been extracted yet. Run analysis or add tender requirements before final submission.";

  return [
    params.aiError ? `> Draft generated by deterministic fallback because AI proposal generation failed: ${params.aiError}` : "> Draft generated by deterministic fallback because AI is not configured.",
    "",
    "## Executive Summary",
    `${params.companyName} submits this technical proposal for ${params.tenderTitle}. The response is based on the uploaded tender information, extracted requirements, and the company knowledge vault.`,
    "",
    "## Understanding of Requirements",
    params.tenderDescription || "The tender documents require a compliant technical and administrative response. The proposal team should verify all submission instructions, mandatory forms, deadline, file naming rules, and evaluation criteria before submission.",
    "",
    "## Extracted Requirements Checklist",
    reqText,
    "",
    "## Technical Approach",
    "The proposed approach is to review the tender requirements in detail, confirm mandatory eligibility and compliance items, assign best-fit experts and relevant project references, prepare the required technical methodology, and validate the final package against every submission instruction.",
    "",
    "## Company Qualifications",
    params.companyProfile || `${params.companyName} maintains reusable company knowledge, expert CVs, project references, registration evidence, financial documents, and policy/manual records in the tender knowledge vault.`,
    params.serviceLines ? `\nService lines: ${params.serviceLines}` : "",
    "",
    "## Why Choose Us",
    "The proposal is supported by structured company knowledge, reviewed expert and project records, compliance checks, and document generation controls designed to reduce missed requirements and improve tender readiness.",
    "",
    "## Next Actions Before Submission",
    "- Run the tender engine and confirm any gaps.",
    "- Use only experts/projects scoring at least 90% or manually approve alternatives.",
    "- Validate all generated documents, filenames, and submission order.",
  ].filter(Boolean).join("\n");
}

export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const userId = await getSession();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  await prismaReady;
  const { id } = await params;

  const [tender, company] = await Promise.all([
    prisma.tender.findFirst({
      where: { id, userId },
      include: { requirements: true },
    }),
    prisma.company.findUnique({ where: { userId } }),
  ]);

  if (!tender) return NextResponse.json({ error: "Tender not found" }, { status: 404 });

  const requirementLines = tender.requirements.map((r) => `${r.title}: ${r.description}`);
  const companyName = company?.name ?? "Our Company";
  const companyProfile = company?.profileSummary ?? company?.description ?? "";
  const serviceLines = safeParseArr((company as { serviceLines?: unknown })?.serviceLines).join(", ");

  try {
    let proposal: string;
    let fallback = false;

    if (isAIEnabled()) {
      try {
        proposal = await generateProposal({
          tenderTitle: tender.title,
          tenderDescription: tender.description ?? tender.intakeSummary ?? "",
          requirements: requirementLines.map((r) => `- ${r}`).join("\n"),
          companyName,
          companyProfile,
          serviceLines,
        });
      } catch (aiError) {
        const msg = aiError instanceof Error ? aiError.message : String(aiError);
        console.error("AI proposal failed; deterministic fallback used:", aiError);
        fallback = true;
        proposal = fallbackProposal({
          tenderTitle: tender.title,
          tenderDescription: tender.description ?? tender.intakeSummary ?? "",
          requirements: requirementLines,
          companyName,
          companyProfile,
          serviceLines,
          aiError: msg.slice(0, 240),
        });
      }
    } else {
      fallback = true;
      proposal = fallbackProposal({
        tenderTitle: tender.title,
        tenderDescription: tender.description ?? tender.intakeSummary ?? "",
        requirements: requirementLines,
        companyName,
        companyProfile,
        serviceLines,
      });
    }

    await prisma.tender.update({
      where: { id },
      data: {
        intakeSummary: proposal,
        notes: tender.notes,
      },
    });

    return NextResponse.json({ success: true, proposal, fallback });
  } catch (error) {
    console.error("Proposal generation route error:", error);
    return NextResponse.json({ error: error instanceof Error ? error.message : "Proposal generation failed" }, { status: 500 });
  }
}
