import { prisma } from "./prisma";
import { logger } from "./observability";

export type AuditAction =
  | "LOGIN" | "LOGOUT"
  | "COMPANY_DOCUMENT_UPLOAD" | "COMPANY_DOCUMENT_DELETE" | "COMPANY_DOCUMENT_REEXTRACT" | "COMPANY_KNOWLEDGE_REPAIR" | "COMPANY_KNOWLEDGE_REPROCESS"
  | "COMPANY_KNOWLEDGE_REPAIR_BLOCKED" | "COMPANY_KNOWLEDGE_REPAIR_SUCCESS"
  | "COMPANY_ASSET_UPLOAD" | "COMPANY_ASSET_DELETE"
  | "TENDER_CREATE" | "TENDER_UPDATE" | "TENDER_DELETE"
  | "TENDER_FILE_UPLOAD"
  | "TENDER_FILE_EXTRACTION"
  | "TENDER_ANALYSIS_RUN" | "TENDER_ANALYZED" | "TENDER_MATCHED" | "TENDER_GENERATED" | "TENDER_VALIDATED" | "TENDER_EXPORTED"
  | "TENDER_WORKFLOW_RUN"
  | "TENDER_FACT_LEDGER_SYNC"
  | "ENGINE_RUN" | "AI_ANALYZE" | "AI_PROPOSAL"
  | "EXPORT_PACKAGE_CREATE" | "EXPORT_PACKAGE_DOWNLOAD" | "EXPORT_PACKAGE_REPAIR"
  | "OVERRIDE" | "GAP_RESOLVED"
  | "CREATE" | "UPDATE" | "DELETE"
  | "DOCUMENT_REVIEW"
  | "DOCUMENT_COMMENT" | "DOCUMENT_COMMENT_UPDATE"
  | "EVALUATOR_SIMULATION_RUN"
  | "AI_REMATCH_RUN"
  | "TENDER_DUPLICATE"
  | "TENDER_ENGINE_RUN_STARTED"
  | "TENDER_ENGINE_RUN_COMPLETED"
  | "TENDER_ENGINE_RUN_FAILED"
  | "TENDER_ENGINE_DOCUMENTS_SUPERSEDED"
  | "TENDER_BID_DECISION_APPLIED"
  | "TENDER_COPILOT_QUESTION"
  | "EVALUATOR_COMMITTEE_RESULT"
  | "EVALUATOR_OBJECTION_RESOLVED"
  | "EVALUATOR_OBJECTION_WAIVED"
  | "TENDER_CONTROL_ADDENDUM"
  | "TENDER_CONTROL_CLARIFICATION"
  | "TENDER_CONTROL_QUESTION"
  | "TENDER_CONTROL_MILESTONE"
  | "TENDER_CONTROL_TASK"
  | "TENDER_CONTROL_RISK"
  | "TENDER_CONTROL_COMMERCIAL_ASSUMPTION"
  | "TENDER_CONTROL_SUGGESTION_REJECTED"
  | "TENDER_BID_OUTCOME_SET"
  | "EXPERT_CV_REGENERATE"
  | "AI_PROPOSAL_PERSIST_BLOCKED"
  | "TENDER_DOCS_RECONCILED"
  | "TENDER_DEEP_REASONING_RUN"
  | "DOCUMENT_GENERATE"
  | "VAULT_EVIDENCE_LINKED"
  | "OUTSIDE_PLAN_SUPERSEDED"
  | "AUTO_FINALIZE_RUN"
  | "ADVISORY_RESOLUTION"
  | "ANALYSIS_REGEX_FALLBACK_APPROVED"
  | "ANALYSIS_REGEX_FALLBACK_REVOKED"
  | "GENERATION_BLOCKED_REGEX_FALLBACK"
  | "QUALITY_REASSESSMENT"
  | "AI_PROVIDER_FAILOVER"
  | "EXPERT_CREATE" | "EXPERT_UPDATE" | "EXPERT_DELETE" | "EXPERT_BULK_DELETE" | "EXPERT_REVIEW" | "EXPERT_TRUST_INVALIDATED"
  | "PROJECT_CREATE" | "PROJECT_UPDATE" | "PROJECT_DELETE" | "PROJECT_BULK_DELETE" | "PROJECT_REVIEW" | "PROJECT_TRUST_INVALIDATED"
  | "LEGAL_RECORD_CREATE" | "LEGAL_RECORD_REVIEW"
  | "FINANCIAL_RECORD_CREATE" | "FINANCIAL_RECORD_REVIEW"
  | "COMPLIANCE_RECORD_CREATE" | "COMPLIANCE_RECORD_REVIEW"
  | "DOCUMENT_RECLASSIFY"
  | "DOCUMENT_DEDUPLICATE"
  | "SUBMISSION_PLAN_ROW_ACTION"
  | "SUBMISSION_PLAN_BUILT"
  | "SUBMISSION_PLAN_CONFIRMED"
  | "SUBMISSION_PLAN_AUTO_CLASSIFY"
  | "TENDER_PLAN_BUILT"
  | "REQUIREMENT_EVIDENCE_CONFIRMED"
  | "REQUIREMENT_EVIDENCE_SUGGESTION_REJECTED"
  | "REQUIREMENT_COVERAGE_MANUALLY_CONFIRMED"
  | "REQUIREMENT_SUPPORT_LEVEL_SET"
  | "TENDER_METADATA_REPAIRED"
  | "TENDER_METADATA_MANUAL_CONFIRMED"
  | "LOGIN_FAILED"
  | "COMPANY_PROFILE_UPDATED"
  | "SETTINGS_UPDATED"
  | "TENDER_METADATA_OVERRIDE"
  | "TENDER_EVIDENCE_SELECT" | "TENDER_EVIDENCE_CONFIRM" | "TENDER_EVIDENCE_NOT_APPLICABLE" | "ADMIN_RELEASE_STUCK_JOBS"
  | "ADMIN_REPAIR_EXECUTED"
  | "VALIDATE_DOCUMENTS";

export async function logAction(opts: {
  userId?: string;
  action: AuditAction;
  entityType?: string;
  entityId?: string;
  description: string;
  metadata?: Record<string, unknown>;
  requestId?: string;
}) {
  try {
    const meta = opts.requestId
      ? { ...opts.metadata, requestId: opts.requestId }
      : (opts.metadata ?? {});
    await prisma.auditLog.create({
      data: {
        userId: opts.userId ?? null,
        action: opts.action,
        entityType: opts.entityType ?? null,
        entityId: opts.entityId ?? null,
        description: opts.description,
        metadata: JSON.stringify(meta),
      },
    });
  } catch (e) {
    // Never let audit logging crash the main flow — but surface the failure so
    // operators can detect audit-trail gaps (which may indicate DB outages or,
    // worse, evidence-tampering detection gaps). Previously this was a bare
    // `catch {}` and audit failures were invisible.
    logger.warn("[audit] write failed — audit trail gap possible", {
      detail: e,
      action: opts.action,
      entityType: opts.entityType ?? null,
      entityId: opts.entityId ?? null,
    });
  }
}
