import { prisma } from "./prisma";
import { logger } from "./observability";
import { getStorageAdapter, type StorageAdapter } from "./storage";
import {
  inspectActualFileBytes,
  requireVerifiedPersistedFileBytes,
} from "./engine/persisted-byte-integrity";

export type GeneratedContentSource = "storage" | "legacy";

type GeneratedDocumentContentLike = {
  id: string;
  name: string;
  exactFileName?: string | null;
  storagePath?: string | null;
  fileContent?: string | null;
  contentSha256?: string | null;
  contentByteLength?: number | null;
  contentMimeType?: string | null;
  detectedFormat?: string | null;
  integrityStatus?: string | null;
};

type GeneratedDocumentStorageClient = {
  generatedDocument: {
    findUnique(args: unknown): Promise<{
      id: string;
      name: string;
      exactFileName: string | null;
      storagePath: string | null;
    } | null>;
    update(args: unknown): Promise<unknown>;
  };
};

function normalizeGeneratedFileName(name: string): string {
  const cleaned = name
    .replace(/[^a-zA-Z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return `${cleaned || "generated-document"}.docx`;
}

function inferMimeType(filename: string): string {
  const lower = filename.toLowerCase();
  if (lower.endsWith(".pdf")) return "application/pdf";
  if (lower.endsWith(".docx")) {
    return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
  }
  if (lower.endsWith(".doc")) return "application/msword";
  if (lower.endsWith(".xlsx")) {
    return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
  }
  if (lower.endsWith(".xls")) return "application/vnd.ms-excel";
  return "application/octet-stream";
}

export async function readGeneratedDocumentContent(
  doc: GeneratedDocumentContentLike,
  options: { requireVerifiedIntegrity?: boolean } = {},
): Promise<{
  buffer: Buffer;
  base64: string;
  filename: string;
  mimeType: string;
  source: GeneratedContentSource;
}> {
  const filename = doc.exactFileName ?? normalizeGeneratedFileName(doc.name);
  const mimeType = inferMimeType(filename);

  const verifyWhenRequired = (buffer: Buffer) => {
    if (!options.requireVerifiedIntegrity) return;
    // Verify against the MIME recorded when the bytes were pinned (the hash
    // comparison anchors it) — the extension-inferred guess cannot resolve
    // extensionless or legacy-named tender-required files.
    requireVerifiedPersistedFileBytes({
      bytes: buffer,
      filename,
      claimedMimeType: doc.contentMimeType ?? mimeType,
      persisted: {
        contentSha256: doc.contentSha256 ?? null,
        contentByteLength: doc.contentByteLength ?? null,
        contentMimeType: doc.contentMimeType ?? null,
        detectedFormat: doc.detectedFormat ?? null,
        integrityStatus: doc.integrityStatus ?? "UNKNOWN",
      },
    });
  };

  if (doc.storagePath) {
    try {
      const adapter = getStorageAdapter();
      const buffer = await adapter.getFile({
        storagePath: doc.storagePath,
        fileContent: doc.fileContent ?? null,
        fileName: filename,
      });
      verifyWhenRequired(buffer);
      return {
        buffer,
        base64: buffer.toString("base64"),
        filename,
        mimeType,
        source: "storage",
      };
    } catch (e) {
      // Storage read failed — fall through to legacy fileContent if available.
      // Surface the failure so storage outages don't silently degrade document
      // generation to legacy fileContent (which may be stale or absent).
      // Previously bare `catch {}` — storage read failures were invisible.
      logger.warn("[generated-document-content] storage read failed — falling through to legacy fileContent", {
        detail: e,
        filename,
        docId: doc.id,
      });
    }
  }

  if (doc.fileContent) {
    const buffer = Buffer.from(doc.fileContent, "base64");
    verifyWhenRequired(buffer);
    return {
      buffer,
      base64: doc.fileContent,
      filename,
      mimeType,
      source: "legacy",
    };
  }

  throw new Error(
    `Generated document ${doc.id} has neither storagePath nor fileContent`,
  );
}

export function generatedDocumentHasContent(doc: {
  storagePath?: string | null;
  fileContent?: string | null;
}): boolean {
  return Boolean(
    (doc.storagePath && doc.storagePath.trim().length > 0)
      || (doc.fileContent && doc.fileContent.trim().length > 0),
  );
}

/**
 * Persist generated bytes with storage/database compensation.
 *
 * Storage is necessarily outside the database transaction. Therefore:
 * - if the database update fails, the newly uploaded object is deleted;
 * - after a successful replacement, the previous external object is deleted;
 * - database-base64 storage needs no separate cleanup because the row update
 *   replaces the old inline value atomically.
 */
export async function persistGeneratedDocumentContent(args: {
  docId: string;
  buffer: Buffer;
  filename: string;
  mimeType: string;
  prismaClient: GeneratedDocumentStorageClient;
  storageAdapter: StorageAdapter;
}) {
  const integrity = inspectActualFileBytes({
    bytes: args.buffer,
    filename: args.filename,
    claimedMimeType: args.mimeType,
  });
  if (integrity.integrityStatus !== "VERIFIED") {
    throw new Error(
      integrity.integrityFailureCode ?? "FILE_INTEGRITY_NOT_VERIFIED",
    );
  }

  // Read the prior external pointer before the upload. Do not select inline
  // base64 content: it is replaced transactionally and can be very large.
  const previous = await args.prismaClient.generatedDocument.findUnique({
    where: { id: args.docId },
    select: {
      id: true,
      name: true,
      exactFileName: true,
      storagePath: true,
    },
  });
  if (!previous) {
    throw new Error("GENERATED_DOCUMENT_NOT_FOUND");
  }

  const saved = await args.storageAdapter.putFile(args.buffer, {
    fileName: args.filename,
    mimeType: args.mimeType,
  });

  try {
    await args.prismaClient.generatedDocument.update({
      where: { id: args.docId },
      data: {
        storagePath: saved.storagePath,
        fileContent: saved.fileContent ?? null,
        exactFileName: args.filename,
        contentSha256: integrity.contentSha256,
        contentByteLength: integrity.contentByteLength,
        contentMimeType: integrity.contentMimeType,
        detectedFormat: integrity.detectedFormat,
        integrityStatus: integrity.integrityStatus,
        integrityVerifiedAt: integrity.integrityVerifiedAt,
        integrityFailureCode: integrity.integrityFailureCode,
        // Legacy final-ZIP digest columns — the download route's verifier
        // reads these; leaving them null blocks export with FILE_DIGEST_MISSING.
        sha256: integrity.contentSha256,
        byteSize: integrity.contentByteLength,
      },
    });
  } catch (error) {
    // The database did not adopt the new object. Remove it so a failed write
    // cannot create an unreferenced Blob/local file.
    await args.storageAdapter.deleteFile({
      storagePath: saved.storagePath,
      fileContent: saved.fileContent ?? null,
      fileName: args.filename,
    }).catch((cleanupError) => {
      logger.error("[generated-content] failed to compensate rejected storage write", {
        documentId: args.docId,
        provider: saved.provider,
        errorName:
          cleanupError instanceof Error
            ? cleanupError.constructor.name
            : typeof cleanupError,
      });
    });
    throw error;
  }

  // The new row is durable. Remove only a different previous external object.
  // Blob/local providers always generate unique paths; the database fallback
  // uses an empty path and was replaced atomically above.
  if (
    previous.storagePath
    && previous.storagePath !== saved.storagePath
  ) {
    await args.storageAdapter.deleteFile({
      storagePath: previous.storagePath,
      fileContent: null,
      fileName:
        previous.exactFileName
        ?? previous.name
        ?? "previous-generated-document",
    }).catch((cleanupError) => {
      // Replacement itself succeeded, so cleanup failure is operational debt,
      // not permission to roll back the now-current document row.
      logger.warn("[generated-content] previous storage object cleanup failed", {
        documentId: args.docId,
        errorName:
          cleanupError instanceof Error
            ? cleanupError.constructor.name
            : typeof cleanupError,
      });
    });
  }

  return {
    ...saved,
    bytes: args.buffer.byteLength,
    integrity,
  };
}

export async function writeGeneratedDocumentContent(
  docId: string,
  buffer: Buffer,
  filename: string,
  mimeType: string,
) {
  return persistGeneratedDocumentContent({
    docId,
    buffer,
    filename,
    mimeType,
    prismaClient: prisma as unknown as GeneratedDocumentStorageClient,
    storageAdapter: getStorageAdapter(),
  });
}
