import { NextResponse } from "next/server";
import { Document, Packer, Paragraph, TextRun } from "docx";
import { forbiddenResponse, requireRole, unauthorizedResponse } from "../../../../../lib/auth";
import { prisma, prismaReady } from "../../../../../lib/prisma";
import { filterFinalExportCandidateDocuments } from "../../../../../lib/engine/document-output-state";
import { checkFullExportReadiness, documentHygieneIssues, extractDocxVisibleText } from "../../../../../lib/engine/export-readiness";
import { generateWithFallback } from "../../../../../lib/ai";
import { applyActiveUploadedLetterheadToTenderDocuments } from "../../../../../lib/engine/apply-active-letterhead";
import { buildSubmissionPlan } from "../../../../../lib/engine/submission-plan";
import { rateLimit, MUTATION_RATE_LIMIT } from "../../../../../lib/rate-limit";
import { extractRequestId } from "../../../../../lib/request-id";
import { logAction } from "../../../../../lib/audit";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const PRICING_PATTERNS = [/\b(price|pricing|fee|fees|rate|rates|commercial offer|financial proposal|contract value|usd|etb|eur)\b/gi, /\b\d+[\d,]*(\.\d+)?\s*(usd|etb|eur|dollar|birr|%)\b/gi];
const META_PATTERNS = [/chatgpt|claude|gemini|openai|deepseek|regex fallback|generated by|ai provider|prompt|model|deterministic fallback|benchmark|preparation trace/gi, /\b(TODO|TBD|FIXME|PLACEHOLDER)\b/gi, /\[(insert[^\]]*|name|date|signature|stamp)\]/gi];

function cleanLine(line: string, technical: boolean): string {
  let out = line.replace(/[—–]/g, "-").replace(/\s+/g, " ").trim();
  for (const rx of META_PATTERNS) out = out.replace(rx, "").trim();
  if (!out) return "";
  if (technical) {
    const hasPricing = PRICING_PATTERNS.some((rx) => rx.test(out));
    if (hasPricing && /method|approach|implementation|capacity|experience|team/i.test(out)) {
      return "The proposal demonstrates organizational capacity, relevant experience, staffing readiness, and implementation methodology. Financial submissions, where required, are handled separately according to the tender instructions.";
    }
    if (hasPricing) return "";
  }
  return out;
}

async function polishWithAI(text: string, technical: boolean): Promise<string> {
  const prompt = `Rewrite this tender document content to be client-ready, factual, concise, and professional. Remove AI/meta traces and placeholders.${technical ? " Remove pricing/commercial/financial wording from technical envelope content and keep technical meaning." : ""}\n\nCONTENT:\n${text.slice(0, 12000)}`;
  try { return await generateWithFallback(prompt, { systemPrompt: "You are a senior tender editor. Keep facts, improve quality, no inventions." }); } catch { return text; }
}

async function toDocx(title: string, text: string): Promise<string> {
  const lines = text.split(/\n+/).map((l) => l.trim()).filter(Boolean);
  const buffer = await Packer.toBuffer(new Document({ sections: [{ children: [new Paragraph({ children: [new TextRun({ text: title, bold: true, size: 28 })] }), ...lines.map((l) => new Paragraph({ children: [new TextRun({ text: l, size: 22 })] }))] }] }));
  return buffer.toString("base64");
}

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  let actor;
  try { actor = await requireRole("ADMIN", "PROPOSAL_MANAGER"); } catch (e) { return e instanceof Error && e.message === "Forbidden" ? forbiddenResponse() : unauthorizedResponse(); }
  const requestId = extractRequestId(req);
  const rl = rateLimit(`auto-finalize:${actor.id}`, MUTATION_RATE_LIMIT);
  if (!rl.allowed) return NextResponse.json({ error: "Rate limit exceeded", retryAfter: Math.ceil((rl.resetAt - Date.now()) / 1000) }, { status: 429, headers: { "Retry-After": String(Math.ceil((rl.resetAt - Date.now()) / 1000)) } });
  await prismaReady;
  const { id: tenderId } = await params;
  const tender = await prisma.tender.findFirst({ where: { id: tenderId, userId: actor.id }, include: { requirements: true, generatedDocuments: { where: { generationStatus: { not: "SUPERSEDED" } }, orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }] } } });
  if (!tender) return NextResponse.json({ error: "Tender not found" }, { status: 404 });

  const plan = buildSubmissionPlan(tender);
  const planEmpty = plan.files.length === 0;
  const plannedNames = new Set(plan.files.map((f) => (f.exactFileName ?? "").trim().toLowerCase()));

  // Reconcile old wrong rows: submission rules + outside-plan supersede
  for (const doc of tender.generatedDocuments) {
    const name = (doc.exactFileName ?? doc.name ?? "").toLowerCase();
    if (/submission formatting|packaging rules|submission method|deadline|delivery rules|submission rules/.test(name)) {
      await prisma.generatedDocument.update({ where: { id: doc.id }, data: { format: "CONTROL", reviewStatus: "NOT_EXPORTABLE", reviewNotes: "Submission control metadata; excluded from final export." } });
      continue;
    }
    if (!planEmpty && !plannedNames.has((doc.exactFileName ?? doc.name ?? "").trim().toLowerCase())) {
      await prisma.generatedDocument.update({ where: { id: doc.id }, data: { generationStatus: "SUPERSEDED", validationStatus: "SUPERSEDED", reviewStatus: "NOT_EXPORTABLE", reviewNotes: "Superseded as outside submission plan." } });
    }
  }

  const refreshedAll = await prisma.generatedDocument.findMany({ where: { tenderId, generationStatus: { not: "SUPERSEDED" } }, orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }] });
  const candidates = filterFinalExportCandidateDocuments(refreshedAll as any[]).filter((d) => d.reviewStatus !== "READY_FOR_EXPORT" || d.validationStatus === "FAILED");

  const batch = candidates.slice(0, 3);
  let processed = 0;
  for (const doc of batch) {
    if (doc.reviewStatus === "REPLACE_WITH_ORIGINAL") continue;
    const fileName = doc.exactFileName ?? doc.name;
    const technical = /technical|methodology|workplan|approach|strategic/i.test(`${fileName} ${doc.documentType ?? ""}`);
    const visible = await extractDocxVisibleText(doc.fileContent, fileName);
    const baseText = (visible ?? "").split(/\n+/).map((line) => cleanLine(line, technical)).filter(Boolean).join("\n");
    const polished = await polishWithAI(baseText || `Document: ${fileName}`, technical);
    const cleaned = polished.split(/\n+/).map((line) => cleanLine(line, technical)).filter(Boolean).join("\n");
    const rebuilt = await toDocx(fileName, cleaned || `${fileName}\nPrepared for submission.`);
    const issues = documentHygieneIssues(cleaned, { name: doc.name, exactFileName: doc.exactFileName, documentType: doc.documentType ?? undefined, format: "DOCX" });
    const ready = issues.length === 0 && rebuilt.length > 0;
    const priorStatus = doc.reviewStatus;
    await prisma.generatedDocument.update({ where: { id: doc.id }, data: { fileContent: rebuilt, format: "DOCX", generationStatus: "GENERATED", validationStatus: ready ? "VALIDATED" : "PENDING", reviewStatus: ready ? "READY_FOR_EXPORT" : "PENDING", reviewedBy: actor.id, reviewedAt: new Date(), reviewNotes: ready ? "Auto-finalized for print/submission." : `Auto-finalized but needs review: ${issues.join("; ")}` } });
    if (ready && priorStatus !== "READY_FOR_EXPORT") await prisma.documentReview.create({ data: { documentId: doc.id, reviewerId: actor.id, action: "READY_FOR_EXPORT", notes: "Auto-finalized for print/submission.", priorStatus, newStatus: "READY_FOR_EXPORT" } });
    processed += 1;
  }

  await applyActiveUploadedLetterheadToTenderDocuments(tenderId, actor.id);
  const finalAll = await prisma.generatedDocument.findMany({ where: { tenderId, generationStatus: { not: "SUPERSEDED" } }, orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }] });
  const finalDocs = filterFinalExportCandidateDocuments(finalAll as any[]);
  const readiness = await checkFullExportReadiness({ tenderId, docs: finalDocs as any[], requireFileContent: false });

  const warning = planEmpty ? "Submission plan empty; outside-plan supersede skipped." : null;
  await logAction({ userId: actor.id, action: "EXPORT_PACKAGE_REPAIR", entityType: "Tender", entityId: tenderId, description: `Auto-finalize processed ${processed} document(s) for ${tender.title}.`, metadata: { tenderId, processed, remaining: Math.max(0, candidates.length - processed), readinessOk: readiness.ok, warning }, requestId });
  return NextResponse.json({ success: true, status: readiness.ok ? "COMPLETED" : "IN_PROGRESS", processedCount: processed, remainingCount: Math.max(0, candidates.length - processed), nextAction: candidates.length - processed > 0 ? "CONTINUE_AUTO_FINALIZE" : "RECHECK_EXPORT_READINESS", readinessOk: readiness.ok, warning });
}
