import { NextResponse } from "next/server";
import { inspectActualFileBytes } from "../../../../../lib/engine/persisted-byte-integrity";
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import { forbiddenResponse, requireRole, unauthorizedResponse } from "../../../../../lib/auth";
import { prisma, prismaReady } from "../../../../../lib/prisma";
import { filterFinalExportCandidateDocuments } from "../../../../../lib/engine/document-output-state";
import { checkFullExportReadiness, documentHygieneIssues, extractDocxVisibleText } from "../../../../../lib/engine/export-readiness";
import { containsPricingLeakage } from "../../../../../lib/engine/pricing-hygiene";
import { generateWithFallback } from "../../../../../lib/ai";
import { applyActiveUploadedLetterheadToTenderDocuments } from "../../../../../lib/engine/apply-active-letterhead";
import { applyActiveSignatureAndStampToTenderDocuments } from "../../../../../lib/engine/apply-signature-stamp";
import { getCurrentConfirmedBuildPlan, type BuildPlanItem } from "../../../../../lib/engine/build-plan";
import { assessExtractionQuality } from "../../../../../lib/extraction-quality";
import { isExtractionAcceptableForGeneration, isExtractionAcceptableForExport } from "../../../../../lib/engine/extraction-quality-gate";
import { rateLimit, MUTATION_RATE_LIMIT } from "../../../../../lib/rate-limit";
import { extractRequestId } from "../../../../../lib/request-id";
import { logAction } from "../../../../../lib/audit";
import { summarizeSevenPassForReviewNotes, evaluateSevenPassForDocument } from "../../../../../lib/engine/seven-pass-generation-wiring";
import { assessGeneratedDocumentQuality } from "../../../../../lib/engine/document-quality-gate";
import { detectAnalysisSourceWithApproval } from "../../../../../lib/engine/analysis-source";
import { assertTenderReadyForGenerationAndExport } from "../../../../../lib/engine/generation-readiness-gate";
import { containsMetadataPlaceholder } from "../../../../../lib/engine/metadata-validators";
import { validateDocumentQuality } from "../../../../../lib/engine/document-quality-validator";
import { POLISH_TIMEOUT_MS } from "../../../../../lib/timeout-config";
import { resolveTenderOperationGate } from "../../../../../lib/engine/tender-operation-gate";
import { logger } from "../../../../../lib/observability";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

// AI/meta trace patterns — reset lastIndex on each use (global flag caveat)
const META_PATTERNS: RegExp[] = [
  /chatgpt|claude|gemini|openai|deepseek|regex fallback|generated by ai|ai provider|ai language model|as an ai|deterministic fallback|benchmark|preparation trace/gi,
  /\b(TODO|TBD|FIXME|PLACEHOLDER)\b/gi,
  /\[(insert[^\]]*|name here|date here|signature here|stamp here|add here|fill in|placeholder)[^\]]*\]/gi,
];

// Targeted rewrite rules for mixed technical/financial phrases.
// These rewrite the offending phrase in place rather than dropping the whole line,
// preserving technical meaning while removing financial leakage.
const TECHNICAL_PHRASE_REWRITES: Array<[RegExp, string]> = [
  [/\bcost\s+control\s+methodology\b/gi, "resource and implementation control methodology"],
  [/\bcost[- ]effective\s+methodology\b/gi, "implementation-focused methodology"],
  [/\bcost[- ]effective\b/gi, "efficient"],
  [/\bbudget[- ]friendly\b/gi, "efficient implementation"],
  [/\bvalue\s+for\s+money\b/gi, "efficient, accountable delivery"],
  [/\bcommercial\s+proposal\s+(?:will\s+be|is|shall\s+be)\s+submitted\s+separately[^.]*\./gi, ""],
  [/\bfinancial\s+proposal\s+(?:will\s+be|is|shall\s+be)\s+submitted\s+separately[^.]*\./gi, ""],
  // "contract value" in project experience context → "project scope"
  [/\bcontract\s+value\b/gi, "project scope"],
  // Currency amounts with numbers
  [/(?:\b(?:USD|ETB|EUR|GBP|Birr|dollar|euro)\s*[0-9][0-9,]*(?:\.\d+)?(?:[KkMmBb](?:illion)?)?\b|\b[0-9][0-9,]*(?:\.\d+)?(?:[KkMmBb](?:illion)?)?\s*(?:USD|ETB|EUR|GBP|Birr|dollar|euro)\b|[$€£]\s*[0-9][0-9,]*(?:\.\d+)?(?:[KkMmBb](?:illion)?)?)/gi, "[scope]"],
  // Rate/fee amounts
  [/\b(?:daily|monthly|hourly|consultancy|professional|service)\s+(?:rate|fee)[:\s]+[$€£]?\s*[0-9][0-9,]*(?:\.\d+)?(?:\s*(?:USD|ETB|EUR|GBP|Birr|dollar|euro))?\b/gi, "[rate on file]"],
  // Standalone percentage fee references
  [/\b(?:fee|charge|commission)\s+of\s+\d+\s*%/gi, "[fee structure on file]"],
  [/\b\d+\s*%\s+(?:fee|charge|commission)\b/gi, "[fee structure on file]"],
];

// Pure financial lines — entire line is a financial header with no technical content worth keeping
const PURE_FINANCIAL_LINE_RX = /^\s*(?:total\s+price|unit\s+price|price\s+schedule|fee\s+schedule|commercial\s+offer|financial\s+proposal|lump\s+sum\s+price?|bill\s+of\s+quantities|BoQ|quoted\s+price|payment\s+schedule|invoice\s+schedule|price\s+breakdown|cost\s+breakdown|budget\s+breakdown)[:\s]/i;

function rewriteFinancialPhrases(sentence: string): string {
  if (PURE_FINANCIAL_LINE_RX.test(sentence)) return "";
  let out = sentence;
  for (const [rx, replacement] of TECHNICAL_PHRASE_REWRITES) {
    out = out.replace(rx, replacement);
  }
  return out.replace(/\s{2,}/g, " ").trim();
}

function cleanLine(line: string, technical: boolean): string {
  let out = line.replace(/[—–]/g, "-").replace(/\s+/g, " ").trim();
  for (const rx of META_PATTERNS) {
    rx.lastIndex = 0;
    out = out.replace(rx, "").trim();
  }
  if (!out) return "";
  if (technical) {
    out = rewriteFinancialPhrases(out);
  }
  return out;
}


async function polishWithAI(text: string, technical: boolean): Promise<string> {
  const prompt = `Rewrite this tender document content to be client-ready, factual, concise, and professional. Remove AI/meta traces and placeholders.${technical ? " Remove pricing/commercial/financial wording from technical envelope content. If a sentence mixes technical content with financial phrasing, keep the technical substance but remove the financial reference. Do not delete entire sections unless they are purely financial." : ""}\n\nCONTENT:\n${text.slice(0, 12000)}`;
  const timeout = new Promise<string>((_, reject) =>
    setTimeout(() => reject(new Error("polish timeout")), POLISH_TIMEOUT_MS)
  );
  try {
    return await Promise.race([
      generateWithFallback(prompt, { systemPrompt: "You are a senior tender editor. Keep facts, improve quality, no inventions." }),
      timeout,
    ]);
  } catch {
    return text;
  }
}

function isHeadingLine(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed || trimmed.length > 120) return false;
  if (/[^.!?]:\s*$/.test(trimmed)) return true;
  const letters = trimmed.replace(/[^a-zA-Z]/g, "");
  return letters.length >= 3 && letters === letters.toUpperCase();
}

function isBulletLine(line: string): boolean {
  return /^\s*[-•*]\s+/.test(line) || /^\s*\d+[.)]\s+/.test(line);
}

async function toDocx(title: string, text: string): Promise<string> {
  const rawLines = text.split(/\n+/).map((l) => l.trim()).filter(Boolean);
  const children: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: title, bold: true })],
      spacing: { after: 200 },
    }),
  ];
  for (const line of rawLines) {
    if (isHeadingLine(line)) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: line.replace(/:\s*$/, "").trim(), bold: true })],
        spacing: { before: 200, after: 100 },
      }));
    } else if (isBulletLine(line)) {
      children.push(new Paragraph({
        bullet: { level: 0 },
        children: [new TextRun({ text: line.replace(/^\s*[-•*]\s+/, "").replace(/^\s*\d+[.)]\s+/, "").trim(), size: 22 })],
        spacing: { after: 80 },
      }));
    } else {
      children.push(new Paragraph({
        children: [new TextRun({ text: line, size: 22 })],
        spacing: { after: 120 },
      }));
    }
  }
  const buffer = await Packer.toBuffer(new Document({ sections: [{ children }] }));
  return buffer.toString("base64");
}

// Documents that must never be auto-approved — they require human upload of
// the official tender-issued original or auditor-signed evidence.
// Pattern must stay in sync with isSensitiveFinancialOrLegalDoc in pricing-hygiene.ts.
const SENSITIVE_DOC_RX = /\b(audited|financial\s+statement|tax\s+clearance|vat\s+cert|vat\s+certificate|tin\s+cert|tin\s+certificate|bank\s+statement|bid\s+form|tender\s+form|declaration\s+form|undertaking\s+form|integrity\s+pact|rate\s+card|business\s+license|registration\s+cert|incorporation|annual\s+report)\b/i;

function isSensitiveDocument(doc: { name?: string | null; exactFileName?: string | null; documentType?: string | null }): boolean {
  const label = `${doc.name ?? ""} ${doc.exactFileName ?? ""} ${doc.documentType ?? ""}`;
  return SENSITIVE_DOC_RX.test(label);
}

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  let actor;
  try { actor = await requireRole("ADMIN", "PROPOSAL_MANAGER"); } catch (e) { return e instanceof Error && e.message === "Forbidden" ? forbiddenResponse() : unauthorizedResponse(); }
  const requestId = extractRequestId(req);
  const rl = rateLimit(`auto-finalize:${actor.id}`, MUTATION_RATE_LIMIT);
  if (!rl.allowed) return NextResponse.json({ error: "Rate limit exceeded", retryAfter: Math.ceil((rl.resetAt - Date.now()) / 1000) }, { status: 429, headers: { "Retry-After": String(Math.ceil((rl.resetAt - Date.now()) / 1000)) } });
  await prismaReady;
  const { id: tenderId } = await params;
  // generatedDocuments select excludes fileContent — the reconcile loop only
  // needs id, name, exactFileName to mark rows as CONTROL/NOT_EXPORTABLE or SUPERSEDED.
  const tender = await prisma.tender.findFirst({
    where: { id: tenderId, userId: actor.id },
    include: {
      requirements: true,
      files: {
        select: {
          id: true, originalFileName: true, fileName: true, extractedText: true,
          extractionScore: true, totalPages: true, extractedPages: true, ocrPages: true, failedPages: true,
        },
      },
      generatedDocuments: {
        where: { generationStatus: { not: "SUPERSEDED" } },
        orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }],
        select: { id: true, name: true, exactFileName: true, generationStatus: true, validationStatus: true, reviewStatus: true, documentType: true, format: true, exactOrder: true, storagePath: true },
      },
    },
  });
  if (!tender) return NextResponse.json({ error: "Tender not found" }, { status: 404 });

  // ── Pre-flight gates (same contract as generate-missing-plan-files) ──────
  // Gate 1: extraction quality — auto-finalize must not mark docs READY_FOR_EXPORT
  // when the underlying tender was never reliably extracted. Because auto-finalize
  // produces export-ready output, both the generation and the (stricter) export
  // extraction bars must pass.
  const effectiveFiles = tender.files.map((file) => {
    const quality = assessExtractionQuality(file.extractedText, file.originalFileName || file.fileName);
    return { ...file, extractionScore: Math.min(file.extractionScore ?? quality.score, quality.score), quality };
  });
  if (effectiveFiles.length > 0 && (!isExtractionAcceptableForGeneration(effectiveFiles) || !isExtractionAcceptableForExport(effectiveFiles))) {
    return NextResponse.json({
      error: "Auto-finalize blocked: tender extraction is not reliable enough. Re-extract or run OCR first.",
      code: "EXTRACTION_QUALITY_INSUFFICIENT",
      nextAction: "OPEN_EXTRACTION_QUALITY",
    }, { status: 422 });
  }

  // Gate 2: metadata contamination — NOT a hard block for draft work.
  // Auto-finalize marks documents READY_FOR_EXPORT which is a FINAL operation,
  // so contamination IS checked here — but as a warning that prevents
  // auto-finalize (not a 422 that blocks all work). The user can still
  // generate drafts and review exports.
  // NOTE: auto-finalize is FINAL_SUBMISSION_CHECK — strict is correct here.

  // Gate 2b: client display name — for FINAL submission, a client name IS required.
  // This is a final-submission gate, not a draft gate.
  const clientDisplayName = tender.clientName || tender.procuringEntityName;
  if (!clientDisplayName) {
    return NextResponse.json({
      error: "Auto-finalize blocked: client/procuring entity name is missing. Provide client details before finalizing.",
      code: "MISSING_CLIENT_DETAILS",
      nextAction: "FILL_CLIENT_METADATA",
    }, { status: 422 });
  }
  // Reject names that pass the null check but contain embedded placeholder language.
  if (containsMetadataPlaceholder(clientDisplayName)) {
    return NextResponse.json({
      error: "Auto-finalize blocked: client/procuring entity name contains placeholder text. Correct the client name before finalizing.",
      code: "PLACEHOLDER_CLIENT_NAME",
      nextAction: "FILL_CLIENT_METADATA",
    }, { status: 422 });
  }

  // Gate 3: analysis extraction status — auto-finalize must not mark documents
  // READY_FOR_EXPORT when AI Analyze was skipped or ran on a degraded extraction.
  // Note: "EXTRACTION_CORRUPTED_AI_SKIPPED" is tender.status (job status);
  // analysisExtractionStatus is "OCR_REQUIRED" in that case.
  const badAnalysisStatuses = [
    "OCR_REQUIRED",
    "REGEX_FALLBACK_FROM_WEAK_EXTRACTION",
    "EXTRACTION_WEAK_REVIEW_REQUIRED",
    "PARTIAL_EXTRACTION_AI_ANALYZED",
  ] as const;
  const currentAnalysisStatus = tender.analysisExtractionStatus;
  if (currentAnalysisStatus && badAnalysisStatuses.includes(currentAnalysisStatus as (typeof badAnalysisStatuses)[number])) {
    return NextResponse.json({
      error: `Auto-finalize blocked: AI analysis was performed on degraded extraction (${currentAnalysisStatus}). Re-run AI Analyze after fixing extraction quality before finalizing documents.`,
      code: "ANALYSIS_FROM_DEGRADED_EXTRACTION",
      analysisExtractionStatus: currentAnalysisStatus,
      nextAction: currentAnalysisStatus === "OCR_REQUIRED" ? "RUN_OCR_OR_UPLOAD_CLEARER_SCAN" : "RERUN_AI_ANALYZE",
    }, { status: 422 });
  }

  // Resolve analysis source once (includes DB approval check) so the seven-pass
  // gate correctly honours human approval of regex-fallback analyses.
  const resolvedAnalysisSource = await detectAnalysisSourceWithApproval(prisma, tenderId, tender);

  // ── Central readiness gate (MANDATORY) ───────────────────────────────────
  // Auto-finalize marks documents as READY_FOR_EXPORT — a release-grade
  // status. It MUST NOT run unless the tender passes the central gate
  // (confirmed BuildPlan, AI_SUCCEEDED analysis, grounded mandatory
  // requirements, critical metadata, etc.). Without this, auto-finalize
  // could mark docs as export-ready on a tender with no confirmed BuildPlan
  // or on a human-approved-fallback analysis (audit-only).
  const centralGate = await assertTenderReadyForGenerationAndExport({
    prisma,
    tenderId,
    userId: actor.id,
    purpose: "final-zip",
  });
  if (!centralGate.ok) {
    return NextResponse.json({
      error: `Auto-finalize blocked: ${centralGate.blockerDetail ?? centralGate.blockerCode}`,
      code: centralGate.blockerCode,
      blockers: [centralGate.blockerDetail ?? "Tender is not ready for finalization."],
      nextAction: centralGate.blockerCode === "BUILD_PLAN_NOT_CONFIRMED" ? "BUILD_SUBMISSION_PLAN" : "RERUN_AI_ANALYZE",
    }, { status: 422 });
  }

  // ─── AUTHORITATIVE: use the current CONFIRMED BuildPlan only ──────────
  const confirmedPlan = await getCurrentConfirmedBuildPlan(prisma, tenderId, actor.id);
  const planItems: BuildPlanItem[] = confirmedPlan.ok ? confirmedPlan.items : [];
  const plan = { files: planItems, warnings: confirmedPlan.ok ? [] : [confirmedPlan.blocker] } as any;
  const planEmpty = plan.files.length === 0;
  const plannedNames = new Set(plan.files.map((f: any) => (f.exactFileName ?? "").trim().toLowerCase()));

  // ── Operation gate (FINAL_SUBMISSION_READY) — authoritative metadata check ─
  // The operation gate enforces tender-derived final-submission requirements:
  // critical fields present, requirements extracted, confirmed BuildPlan,
  // endpoint matches method, no contamination, no degraded extraction.
  // This is the source-driven authority for what the tender itself requires.
  const autoFinalizeOperationGate = resolveTenderOperationGate({
    tender: {
      id: tender.id,
      title: tender.title,
      reference: tender.reference,
      clientName: tender.clientName,
      deadline: tender.deadline,
      submissionMethod: tender.submissionMethod,
      submissionEmails: tender.submissionEmails,
      submissionAddress: tender.submissionAddress,
      country: tender.country,
      metadataContaminated: tender.metadataContaminated,
      analysisExtractionStatus: tender.analysisExtractionStatus,
    },
    requirements: (tender.requirements ?? []).map((r: any) => ({
      priority: r.priority,
      sourceTenderFileId: r.sourceTenderFileId,
    })),
    overrides: [],
    buildPlan: { ok: confirmedPlan.ok, items: planItems },
    operation: "FINAL_SUBMISSION_READY",
  });
  if (autoFinalizeOperationGate.warnings.length > 0) {
    logger.info(`[auto-finalize] tender=${tenderId} operation-gate warnings: ${autoFinalizeOperationGate.warnings.join("; ")}`);
  }
  if (autoFinalizeOperationGate.blockers.length > 0) {
    return NextResponse.json({
      error: `Auto-finalize blocked by operation gate: ${autoFinalizeOperationGate.blockers.join("; ")}`,
      code: "OPERATION_GATE_BLOCKED",
      blockers: autoFinalizeOperationGate.blockers,
      warnings: autoFinalizeOperationGate.warnings,
      nextAction: "RESOLVE_FINAL_SUBMISSION_BLOCKERS",
    }, { status: 422 });
  }

  // Reconcile old wrong rows: submission rules + outside-plan supersede.
  // Wrap the loop in a transaction so a partial failure cannot leave the
  // tender with a mix of reconciled and stale document states. The later
  // per-document finalization at lines 455-461 is separately wrapped in its
  // own $transaction — this transaction covers only the reconciliation pass.
  await prisma.$transaction(async (tx) => {
    for (const doc of tender.generatedDocuments) {
      const name = (doc.exactFileName ?? doc.name ?? "").toLowerCase();
      if (/submission formatting|packaging rules|submission method|deadline|delivery rules|submission rules/.test(name)) {
        await tx.generatedDocument.update({ where: { id: doc.id }, data: { format: "CONTROL", reviewStatus: "NOT_EXPORTABLE", reviewNotes: "Submission control metadata; excluded from final export." } });
        continue;
      }
      if (!planEmpty && !plannedNames.has((doc.exactFileName ?? doc.name ?? "").trim().toLowerCase())) {
        await tx.generatedDocument.update({ where: { id: doc.id }, data: { generationStatus: "SUPERSEDED", validationStatus: "SUPERSEDED", reviewStatus: "NOT_EXPORTABLE", reviewNotes: "Superseded as outside submission plan." } });
      }
    }
  });

  // Explicit select — fileContent is included here because the finalization loop
  // calls extractDocxVisibleText(doc.fileContent, ...) to read the existing content
  // before rebuilding the DOCX. All other batch fetches exclude fileContent.
  const refreshedAll = await prisma.generatedDocument.findMany({
    where: { tenderId, generationStatus: { not: "SUPERSEDED" } },
    orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }],
    select: {
      id: true,
      tenderId: true,
      name: true,
      documentType: true,
      format: true,
      exactFileName: true,
      exactOrder: true,
      generationStatus: true,
      validationStatus: true,
      reviewStatus: true,
      storagePath: true,
      contentSummary: true,
      // fileContent included — needed to read existing bytes before DOCX rebuild
      fileContent: true,
    },
  });
  const candidates = filterFinalExportCandidateDocuments(refreshedAll as any[]).filter((d) => d.reviewStatus !== "READY_FOR_EXPORT" || d.validationStatus === "FAILED");

  // ── Seven-pass gate: load evidence context once for the whole batch ───────
  const [reviewedExpertCount, reviewedProjectCount] = await Promise.all([
    prisma.tenderExpertMatch.count({ where: { tenderId, isSelected: true, expert: { trustLevel: "REVIEWED" } } }),
    prisma.tenderProjectMatch.count({ where: { tenderId, isSelected: true, project: { trustLevel: "REVIEWED" } } }),
  ]);
  const requiredExpertCount = tender.requirements.filter((r) => r.requirementType === "EXPERT").length;
  const requiredProjectCount = tender.requirements.filter((r) => r.requirementType === "PROJECT_EXPERIENCE").length;
  const totalMandatory = tender.requirements.filter((r) => r.priority === "MANDATORY").length;
  const sourcedMandatory = tender.requirements.filter((r) => r.priority === "MANDATORY" && ((r.sourceConfidence ?? 0) > 0 || (r.sectionReference ?? "").trim().length > 0)).length;

  const batch = candidates.slice(0, 3);
  let processed = 0;
  for (const doc of batch) {
    if (doc.reviewStatus === "REPLACE_WITH_ORIGINAL") continue;
    if (isSensitiveDocument(doc)) continue; // audited statements, bid forms, tax/legal certs — require manual upload
    // The rebuild reads ONLY inline bytes. A storage-backed row's canonical
    // bytes live in the storage object — rebuilding from the absent (or
    // possibly stale) inline copy would replace real content with a hollow
    // shell built from just the filename. Skip; manual review handles these.
    if (!doc.fileContent || doc.storagePath) continue;
    const fileName = doc.exactFileName ?? doc.name;
    const technical = /technical|methodology|workplan|approach|strategic/i.test(`${fileName} ${doc.documentType ?? ""}`);
    const docMeta = { name: doc.name, exactFileName: doc.exactFileName, documentType: doc.documentType ?? undefined, format: "DOCX" as const };
    const visible = await extractDocxVisibleText(doc.fileContent, fileName);
    const baseText = (visible ?? "").split(/\n+/).map((line) => cleanLine(line, technical)).filter(Boolean).join("\n");
    const polished = await polishWithAI(baseText || `Document: ${fileName}`, technical);
    // Second pass: apply phrase rewrites after AI polish to catch anything AI missed
    const cleaned = polished.split(/\n+/).map((line) => cleanLine(line, technical)).filter(Boolean).join("\n");
    const rebuilt = await toDocx(fileName, cleaned || `${fileName}\nPrepared for submission.`);

    // ── Phase 3: Server-enforced quality validation ───────────────────────────
    const qualityValidation = validateDocumentQuality({
      name: doc.name,
      documentType: doc.documentType,
      fileContent: cleaned,
      storagePath: doc.storagePath,
    });

    // Re-check pricing leakage on visible text AFTER cleaning — only mark READY_FOR_EXPORT if genuinely clean
    const stillHasPricingLeakage = technical && containsPricingLeakage(cleaned, docMeta);
    const issues = documentHygieneIssues(cleaned, docMeta);
    const hygieneReady = issues.length === 0 &&
                  !stillHasPricingLeakage &&
                  rebuilt.length > 0 &&
                  qualityValidation.status !== "BLOCKED";

    // ── Self-review score (deterministic) ─────────────────────────────────────
    // Run the document quality gate on the cleaned text to produce a real
    // selfReviewScore (0–100). This replaces the null sentinel so the
    // SELF_REVIEW_SCORING pass in the seven-pass gate actually enforces the ≥80
    // threshold rather than skipping it.
    const qualityReport = assessGeneratedDocumentQuality({
      doc: { name: doc.name, exactFileName: doc.exactFileName, documentType: doc.documentType, format: "DOCX" },
      visibleText: cleaned,
      requirements: tender.requirements,
    });
    const selfReviewScore = qualityReport.score;

    // ── Seven-pass gate check ───────────────────────────────────────────────
    const gateEvaluation = evaluateSevenPassForDocument({
      tenderNotes: tender.notes,
      resolvedAnalysisSource,
      tenderReference: tender.reference ?? null,
      visibleText: cleaned,
      reviewedExpertCount,
      reviewedProjectCount,
      requiredExpertCount,
      requiredProjectCount,
      totalMandatoryRequirements: totalMandatory,
      sourcedMandatoryRequirements: sourcedMandatory,
      documentType: doc.documentType,
      documentName: doc.name,
      exactFileName: doc.exactFileName,
      currentReviewStatus: doc.reviewStatus,
      selfReviewScore,
    });
    // A document can only be READY_FOR_EXPORT if both hygiene AND the seven-pass gate allow it.
    // Pin the rebuilt bytes' integrity. A rebuild whose bytes do not verify
    // must never be auto-marked READY_FOR_EXPORT (fail closed to review).
    const rebuiltIntegrity = inspectActualFileBytes({ bytes: Buffer.from(rebuilt, "base64"), filename: doc.exactFileName ?? `${fileName}.docx`, claimedMimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
    const ready = hygieneReady && gateEvaluation.finalApprovalAllowed && rebuiltIntegrity.integrityStatus === "VERIFIED";

    const hygieneNotes = hygieneReady ? "" : `hygiene: ${[...issues, ...(stillHasPricingLeakage ? ["pricing leakage detected"] : [])].join("; ")}`;
    const gateNotes = summarizeSevenPassForReviewNotes(gateEvaluation);
    // If integrity is the only blocker, the notes must say so — otherwise the
    // audit trail claims every check passed on a NEEDS_REVIEW document.
    const integrityNotes = rebuiltIntegrity.integrityStatus === "VERIFIED"
      ? ""
      : `byte-integrity: ${rebuiltIntegrity.integrityFailureCode ?? rebuiltIntegrity.integrityStatus}`;
    const reviewNotes = ready
      ? `Auto-finalized for print/submission. ${gateNotes}`
      : `Auto-finalized but needs review. ${[hygieneNotes, integrityNotes, gateNotes].filter(Boolean).join(" | ")}`;

    // Wrap update in a transaction so the byte integrity and status stay
    // atomic. Gap 1: automation must never write reviewedBy, reviewedAt,
    // or a human READY_FOR_EXPORT reviewStatus, and never create a
    // DocumentReview record. The auto-finalize route now only writes
    // machine-safe state: generationStatus, validationStatus (PENDING —
    // the Document Validator owns VALIDATED per Gap 2), and reviewNotes
    // carrying the machine-repair provenance. The human reviewStatus
    // (READY_FOR_EXPORT / NEEDS_REVIEW) is NOT set by automation.
    await prisma.$transaction(async (tx) => {
      await tx.generatedDocument.update({ where: { id: doc.id }, data: { fileContent: rebuilt, ...rebuiltIntegrity, sha256: rebuiltIntegrity.contentSha256, byteSize: rebuiltIntegrity.contentByteLength, storagePath: null, format: "DOCX", generationStatus: "GENERATED", validationStatus: "PENDING", reviewNotes: `machine:auto-finalize — ${reviewNotes.slice(0, 3800)}` } });
      // No DocumentReview row is created — that is a human-review record.
    });
    processed += 1;
  }

  await applyActiveUploadedLetterheadToTenderDocuments(tenderId, actor.id);
  // Auto-apply company signature and stamp images after letterhead
  await applyActiveSignatureAndStampToTenderDocuments(tenderId, actor.id);
  // The readiness check verifies actual bytes and persisted integrity
  // (checkExportFileByteReadiness). Fetching without fileContent/integrity
  // columns made it report false MISSING_FILE_BYTES / unverified-integrity
  // failures for documents that were just verified above.
  const finalAll = await prisma.generatedDocument.findMany({
    where: { tenderId, generationStatus: { not: "SUPERSEDED" } },
    orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }],
    select: {
      id: true,
      tenderId: true,
      name: true,
      documentType: true,
      format: true,
      exactFileName: true,
      exactOrder: true,
      generationStatus: true,
      reviewStatus: true,
      validationStatus: true,
      contentSummary: true,
      storagePath: true,
      reviewedBy: true,
      reviewedAt: true,
      reviewNotes: true,
      createdAt: true,
      updatedAt: true,
      fileContent: true,
      contentSha256: true,
      contentByteLength: true,
      contentMimeType: true,
      detectedFormat: true,
      integrityStatus: true,
    },
  });
  const finalDocs = filterFinalExportCandidateDocuments(finalAll as any[]);
  const readiness = await checkFullExportReadiness({ tenderId, docs: finalDocs as any[], requireFileContent: false });

  const warning = planEmpty ? "Submission plan empty; outside-plan supersede skipped." : null;
  await logAction({ userId: actor.id, action: "AUTO_FINALIZE_RUN", entityType: "Tender", entityId: tenderId, description: `Auto-finalize processed ${processed} document(s) for ${tender.title}.`, metadata: { tenderId, processed, remaining: Math.max(0, candidates.length - processed), readinessOk: readiness.ok, warning }, requestId });
  return NextResponse.json({ success: true, status: readiness.ok ? "COMPLETED" : "IN_PROGRESS", processedCount: processed, remainingCount: Math.max(0, candidates.length - processed), nextAction: candidates.length - processed > 0 ? "CONTINUE_AUTO_FINALIZE" : "RECHECK_EXPORT_READINESS", readinessOk: readiness.ok, warning });
}
