import { NextResponse } from "next/server";
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import { forbiddenResponse, requireRole, unauthorizedResponse } from "../../../../../lib/auth";
import { prisma, prismaReady } from "../../../../../lib/prisma";
import { filterFinalExportCandidateDocuments } from "../../../../../lib/engine/document-output-state";
import { checkFullExportReadiness, documentHygieneIssues, extractDocxVisibleText } from "../../../../../lib/engine/export-readiness";
import { containsPricingLeakage } from "../../../../../lib/engine/pricing-hygiene";
import { generateWithFallback } from "../../../../../lib/ai";
import { applyActiveUploadedLetterheadToTenderDocuments } from "../../../../../lib/engine/apply-active-letterhead";
import { buildSubmissionPlan } from "../../../../../lib/engine/submission-plan";
import { rateLimit, MUTATION_RATE_LIMIT } from "../../../../../lib/rate-limit";
import { extractRequestId } from "../../../../../lib/request-id";
import { logAction } from "../../../../../lib/audit";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const META_PATTERNS: RegExp[] = [
  /chatgpt|claude|gemini|openai|deepseek|regex fallback|generated by ai|ai provider|ai language model|as an ai|deterministic fallback|benchmark|preparation trace/gi,
  /\b(TODO|TBD|FIXME|PLACEHOLDER)\b/gi,
  /\[(insert[^\]]*|name here|date here|signature here|stamp here|add here|fill in|placeholder)[^\]]*\]/gi,
];

// Targeted rewrite rules for mixed technical/financial phrases.
// These rewrite the offending phrase in place rather than dropping the whole line.
const TECHNICAL_PHRASE_REWRITES: Array<[RegExp, string]> = [
  [/\bcost\s+control\s+methodology\b/gi, "resource and implementation control methodology"],
  [/\bcost[- ]effective\s+methodology\b/gi, "implementation-focused methodology"],
  [/\bbudget[- ]friendly\b/gi, "efficient implementation"],
  [/\bbudget\s+friendly\b/gi, "efficient implementation"],
  [/\bvalue\s+for\s+money\b/gi, "efficient, accountable delivery"],
  [/\bcommercial\s+proposal\s+(?:will\s+be|is|shall\s+be)\s+submitted\s+separately[^.]*\./gi, ""],
  [/\bfinancial\s+proposal\s+(?:will\s+be|is|shall\s+be)\s+submitted\s+separately[^.]*\./gi, ""],
  // "contract value" in project experience context → "project scope"
  [/\bcontract\s+value\b/gi, "project scope"],
  // Currency amounts with numbers: USD 10,000 / ETB 50,000 / $10K / €5M
  [/(?:\b(?:USD|ETB|EUR|GBP|Birr|dollar|euro)\s*[0-9][0-9,]*(?:\.\d+)?(?:[KkMmBb](?:illion)?)?\b|\b[0-9][0-9,]*(?:\.\d+)?(?:[KkMmBb](?:illion)?)?\s*(?:USD|ETB|EUR|GBP|Birr|dollar|euro)\b|[$€£]\s*[0-9][0-9,]*(?:\.\d+)?(?:[KkMmBb](?:illion)?)?)/gi, "[scope]"],
  // Rate/fee amounts: "daily rate: $200", "consultancy fee $X"
  [/\b(?:daily|monthly|hourly|consultancy|professional|service)\s+(?:rate|fee)[:\s]+[$€£]?\s*[0-9][0-9,]*(?:\.\d+)?(?:\s*(?:USD|ETB|EUR|GBP|Birr|dollar|euro))?\b/gi, "[rate on file]"],
  // Standalone percentage fee references: "fee of 10%", "5% fee"
  [/\b(?:fee|charge|commission)\s+of\s+\d+\s*%/gi, "[fee structure on file]"],
  [/\b\d+\s*%\s+(?:fee|charge|commission)\b/gi, "[fee structure on file]"],
];

// Pure financial sentence markers — entire sentence/line is financial with no technical content worth keeping
const PURE_FINANCIAL_LINE_RX = /^\s*(?:total\s+price|unit\s+price|price\s+schedule|fee\s+schedule|commercial\s+offer|financial\s+proposal|lump\s+sum\s+price?|bill\s+of\s+quantities|BoQ|quoted\s+price|payment\s+schedule|invoice\s+schedule|price\s+breakdown|cost\s+breakdown|budget\s+breakdown)[:\s]/i;

/**
 * Apply targeted phrase rewrites to a sentence. Returns the rewritten sentence,
 * or empty string if the line is a pure financial header with no technical content.
 */
function rewriteFinancialPhrases(sentence: string): string {
  // Drop pure-financial headers entirely
  if (PURE_FINANCIAL_LINE_RX.test(sentence)) return "";
  let out = sentence;
  for (const [rx, replacement] of TECHNICAL_PHRASE_REWRITES) {
    out = out.replace(rx, replacement);
  }
  return out.replace(/\s{2,}/g, " ").trim();
}

function cleanLine(line: string, technical: boolean): string {
  let out = line.replace(/[—–]/g, "-").replace(/\s+/g, " ").trim();
  for (const rx of META_PATTERNS) {
    rx.lastIndex = 0;
    out = out.replace(rx, "").trim();
  }
  if (!out) return "";
  if (technical) {
    out = rewriteFinancialPhrases(out);
  }
  return out;
}

async function polishWithAI(text: string, technical: boolean): Promise<string> {
  const prompt = `Rewrite this tender document content to be client-ready, factual, concise, and professional. Remove AI/meta traces and placeholders.${technical ? " Remove pricing/commercial/financial wording from technical envelope content. If a sentence mixes technical content with financial phrasing, keep the technical substance but remove the financial reference. Do not delete entire sections unless they are purely financial." : ""}\n\nCONTENT:\n${text.slice(0, 12000)}`;
  try { return await generateWithFallback(prompt, { systemPrompt: "You are a senior tender editor. Keep facts, improve quality, no inventions." }); } catch { return text; }
}

/** Detect heading-like lines: ALL CAPS with reasonable length, or ends with a colon */
function isHeadingLine(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed) return false;
  if (trimmed.length > 120) return false;
  // Line ending with colon, no sentence-ending punctuation before it
  if (/[^.!?]:\s*$/.test(trimmed)) return true;
  // All uppercase with at least 3 chars, no lowercase letters
  const letters = trimmed.replace(/[^a-zA-Z]/g, "");
  return letters.length >= 3 && letters === letters.toUpperCase();
}

/** Detect bullet-like lines */
function isBulletLine(line: string): boolean {
  return /^\s*[-•*]\s+/.test(line) || /^\s*\d+[.)]\s+/.test(line);
}

async function toDocx(title: string, text: string): Promise<string> {
  const rawLines = text.split(/\n+/).map((l) => l.trim()).filter(Boolean);
  const children: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: title, bold: true })],
      spacing: { after: 200 },
    }),
  ];
  for (const line of rawLines) {
    if (isHeadingLine(line)) {
      // Strip trailing colon for heading display
      const headingText = line.replace(/:\s*$/, "").trim();
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: headingText, bold: true })],
          spacing: { before: 200, after: 100 },
        }),
      );
    } else if (isBulletLine(line)) {
      // Strip leading bullet character
      const bulletText = line.replace(/^\s*[-•*]\s+/, "").replace(/^\s*\d+[.)]\s+/, "").trim();
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun({ text: bulletText, size: 22 })],
          spacing: { after: 80 },
        }),
      );
    } else {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 22 })],
          spacing: { after: 120 },
        }),
      );
    }
  }
  const buffer = await Packer.toBuffer(new Document({ sections: [{ children }] }));
  return buffer.toString("base64");
}

/**
 * Documents that must never be auto-approved — they require human upload of
 * the official tender-issued original or auditor-signed evidence.
 * Pattern must stay in sync with isSensitiveFinancialOrLegalDoc in pricing-hygiene.ts.
 */
const SENSITIVE_DOC_RX = /\b(audited|financial\s+statement|tax\s+clearance|vat\s+cert|vat\s+certificate|tin\s+cert|tin\s+certificate|bank\s+statement|bid\s+form|tender\s+form|declaration\s+form|undertaking\s+form|integrity\s+pact|rate\s+card|business\s+license|registration\s+cert|incorporation|annual\s+report)\b/i;

function isSensitiveDocument(doc: { name?: string | null; exactFileName?: string | null; documentType?: string | null }): boolean {
  const label = `${doc.name ?? ""} ${doc.exactFileName ?? ""} ${doc.documentType ?? ""}`;
  return SENSITIVE_DOC_RX.test(label);
}

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  let actor;
  try { actor = await requireRole("ADMIN", "PROPOSAL_MANAGER"); } catch (e) { return e instanceof Error && e.message === "Forbidden" ? forbiddenResponse() : unauthorizedResponse(); }
  const requestId = extractRequestId(req);
  const rl = rateLimit(`auto-finalize:${actor.id}`, MUTATION_RATE_LIMIT);
  if (!rl.allowed) return NextResponse.json({ error: "Rate limit exceeded", retryAfter: Math.ceil((rl.resetAt - Date.now()) / 1000) }, { status: 429, headers: { "Retry-After": String(Math.ceil((rl.resetAt - Date.now()) / 1000)) } });
  await prismaReady;
  const { id: tenderId } = await params;
  const tender = await prisma.tender.findFirst({ where: { id: tenderId, userId: actor.id }, include: { requirements: true, generatedDocuments: { where: { generationStatus: { not: "SUPERSEDED" } }, orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }] } } });
  if (!tender) return NextResponse.json({ error: "Tender not found" }, { status: 404 });

  const plan = buildSubmissionPlan(tender);
  const planEmpty = plan.files.length === 0;
  const plannedNames = new Set(plan.files.map((f) => (f.exactFileName ?? "").trim().toLowerCase()));

  // Reconcile old wrong rows: submission rules + outside-plan supersede
  for (const doc of tender.generatedDocuments) {
    const name = (doc.exactFileName ?? doc.name ?? "").toLowerCase();
    if (/submission formatting|packaging rules|submission method|deadline|delivery rules|submission rules/.test(name)) {
      await prisma.generatedDocument.update({ where: { id: doc.id }, data: { format: "CONTROL", reviewStatus: "NOT_EXPORTABLE", reviewNotes: "Submission control metadata; excluded from final export." } });
      continue;
    }
    if (!planEmpty && !plannedNames.has((doc.exactFileName ?? doc.name ?? "").trim().toLowerCase())) {
      await prisma.generatedDocument.update({ where: { id: doc.id }, data: { generationStatus: "SUPERSEDED", validationStatus: "SUPERSEDED", reviewStatus: "NOT_EXPORTABLE", reviewNotes: "Superseded as outside submission plan." } });
    }
  }

  const refreshedAll = await prisma.generatedDocument.findMany({ where: { tenderId, generationStatus: { not: "SUPERSEDED" } }, orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }] });
  const candidates = filterFinalExportCandidateDocuments(refreshedAll as any[]).filter((d) => d.reviewStatus !== "READY_FOR_EXPORT" || d.validationStatus === "FAILED");

  const batch = candidates.slice(0, 3);
  let processed = 0;
  for (const doc of batch) {
    if (doc.reviewStatus === "REPLACE_WITH_ORIGINAL") continue;
    if (isSensitiveDocument(doc)) continue; // audited statements, bid forms, tax/legal certs — require manual upload
    const fileName = doc.exactFileName ?? doc.name;
    const technical = /technical|methodology|workplan|approach|strategic/i.test(`${fileName} ${doc.documentType ?? ""}`);
    const visible = await extractDocxVisibleText(doc.fileContent, fileName);
    const baseText = (visible ?? "").split(/\n+/).map((line) => cleanLine(line, technical)).filter(Boolean).join("\n");
    const polished = await polishWithAI(baseText || `Document: ${fileName}`, technical);
    // Second pass: apply phrase rewrites after AI polish to catch anything the AI missed
    const cleaned = polished.split(/\n+/).map((line) => cleanLine(line, technical)).filter(Boolean).join("\n");
    const rebuilt = await toDocx(fileName, cleaned || `${fileName}\nPrepared for submission.`);
    // Re-check pricing leakage AFTER cleaning — only mark ready if genuinely clean
    const docMeta = { name: doc.name, exactFileName: doc.exactFileName, documentType: doc.documentType ?? undefined, format: "DOCX" as const };
    const stillHasPricingLeakage = technical && containsPricingLeakage(cleaned, docMeta);
    const issues = [
      ...documentHygieneIssues(cleaned, docMeta),
      ...(stillHasPricingLeakage ? [] : []), // already included via documentHygieneIssues
    ].filter((v, i, arr) => arr.indexOf(v) === i);
    const ready = issues.length === 0 && rebuilt.length > 0;
    const priorStatus = doc.reviewStatus;
    await prisma.generatedDocument.update({ where: { id: doc.id }, data: { fileContent: rebuilt, format: "DOCX", generationStatus: "GENERATED", validationStatus: ready ? "VALIDATED" : "PENDING", reviewStatus: ready ? "READY_FOR_EXPORT" : "PENDING", reviewedBy: actor.id, reviewedAt: new Date(), reviewNotes: ready ? "Auto-finalized for print/submission." : `Auto-finalized but needs review: ${issues.join("; ")}` } });
    if (ready && priorStatus !== "READY_FOR_EXPORT") await prisma.documentReview.create({ data: { documentId: doc.id, reviewerId: actor.id, action: "READY_FOR_EXPORT", notes: "Auto-finalized for print/submission.", priorStatus, newStatus: "READY_FOR_EXPORT" } });
    processed += 1;
  }

  await applyActiveUploadedLetterheadToTenderDocuments(tenderId, actor.id);
  const finalAll = await prisma.generatedDocument.findMany({ where: { tenderId, generationStatus: { not: "SUPERSEDED" } }, orderBy: [{ exactOrder: "asc" }, { createdAt: "asc" }] });
  const finalDocs = filterFinalExportCandidateDocuments(finalAll as any[]);
  const readiness = await checkFullExportReadiness({ tenderId, docs: finalDocs as any[], requireFileContent: false });

  const warning = planEmpty ? "Submission plan empty; outside-plan supersede skipped." : null;
  await logAction({ userId: actor.id, action: "AUTO_FINALIZE_RUN", entityType: "Tender", entityId: tenderId, description: `Auto-finalize processed ${processed} document(s) for ${tender.title}.`, metadata: { tenderId, processed, remaining: Math.max(0, candidates.length - processed), readinessOk: readiness.ok, warning }, requestId });
  return NextResponse.json({ success: true, status: readiness.ok ? "COMPLETED" : "IN_PROGRESS", processedCount: processed, remainingCount: Math.max(0, candidates.length - processed), nextAction: candidates.length - processed > 0 ? "CONTINUE_AUTO_FINALIZE" : "RECHECK_EXPORT_READINESS", readinessOk: readiness.ok, warning });
}
