export const SECURITY_ROLES = ["ADMIN", "PROPOSAL_MANAGER", "REVIEWER", "VIEWER"] as const;
export type SecurityRole = (typeof SECURITY_ROLES)[number];

export type Action =
  | "TENDER_READ"
  | "TENDER_UPDATE"
  | "TENDER_DELETE"
  | "AI_ANALYZE_TRIGGER"
  | "GENERATION_TRIGGER"
  | "REVIEW"
  | "APPROVAL"
  | "FINAL_EXPORT"
  | "COMPANY_KNOWLEDGE_MGMT"
  | "USER_ADMIN"
  | "OPERATIONAL_DIAGNOSTICS"
  | "DATA_REPAIR";

export const ROLE_PERMISSIONS: Readonly<Record<SecurityRole, ReadonlySet<Action>>> = {
  ADMIN: new Set(["TENDER_READ", "TENDER_UPDATE", "TENDER_DELETE", "AI_ANALYZE_TRIGGER", "GENERATION_TRIGGER", "REVIEW", "APPROVAL", "FINAL_EXPORT", "COMPANY_KNOWLEDGE_MGMT", "USER_ADMIN", "OPERATIONAL_DIAGNOSTICS", "DATA_REPAIR"]),
  PROPOSAL_MANAGER: new Set(["TENDER_READ", "TENDER_UPDATE", "TENDER_DELETE", "AI_ANALYZE_TRIGGER", "GENERATION_TRIGGER", "REVIEW", "APPROVAL", "FINAL_EXPORT", "COMPANY_KNOWLEDGE_MGMT"]),
  REVIEWER: new Set(["TENDER_READ", "REVIEW"]),
  VIEWER: new Set(["TENDER_READ"]),
};

export function canPerform(role: string, action: Action): boolean {
  return SECURITY_ROLES.includes(role as SecurityRole) && ROLE_PERMISSIONS[role as SecurityRole].has(action);
}
